<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrAccountFlags {
    public int $value;

    const AUTH_REQUIRED_FLAG = 1;
    const AUTH_REVOCABLE_FLAG = 2;
    const AUTH_IMMUTABLE_FLAG = 4;
    const AUTH_CLAWBACK_ENABLED_FLAG = 8;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function AUTH_REQUIRED_FLAG(): XdrAccountFlags {
        return new XdrAccountFlags(XdrAccountFlags::AUTH_REQUIRED_FLAG);
    }

    public static function AUTH_REVOCABLE_FLAG(): XdrAccountFlags {
        return new XdrAccountFlags(XdrAccountFlags::AUTH_REVOCABLE_FLAG);
    }

    public static function AUTH_IMMUTABLE_FLAG(): XdrAccountFlags {
        return new XdrAccountFlags(XdrAccountFlags::AUTH_IMMUTABLE_FLAG);
    }

    public static function AUTH_CLAWBACK_ENABLED_FLAG(): XdrAccountFlags {
        return new XdrAccountFlags(XdrAccountFlags::AUTH_CLAWBACK_ENABLED_FLAG);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrAccountFlags {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 1:
            case 2:
            case 4:
            case 8:
                return new XdrAccountFlags($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
