<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrBucketEntry {

    public XdrBucketEntryType $type;
    public ?XdrLedgerEntry $liveEntry = null;
    public ?XdrLedgerKey $deadEntry = null;
    public ?XdrBucketMetadata $metaEntry = null;

    public function __construct(?XdrBucketEntryType $type = null) {
        if ($type !== null) {
            $this->type = $type;
        }
    }

    public function encode(): string {
        $bytes = $this->type->encode();
        switch ($this->type->getValue()) {
            case XdrBucketEntryType::LIVEENTRY:
            case XdrBucketEntryType::INITENTRY:
                $bytes .= $this->liveEntry->encode();
                break;
            case XdrBucketEntryType::DEADENTRY:
                $bytes .= $this->deadEntry->encode();
                break;
            case XdrBucketEntryType::METAENTRY:
                $bytes .= $this->metaEntry->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrBucketEntry {
        $result = new XdrBucketEntry(XdrBucketEntryType::decode($xdr));
        switch ($result->type->getValue()) {
            case XdrBucketEntryType::LIVEENTRY:
            case XdrBucketEntryType::INITENTRY:
                $result->liveEntry = XdrLedgerEntry::decode($xdr);
                break;
            case XdrBucketEntryType::DEADENTRY:
                $result->deadEntry = XdrLedgerKey::decode($xdr);
                break;
            case XdrBucketEntryType::METAENTRY:
                $result->metaEntry = XdrBucketMetadata::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getType(): XdrBucketEntryType { return $this->type; }
    public function setType(XdrBucketEntryType $type): void { $this->type = $type; }
    public function getLiveEntry(): ?XdrLedgerEntry { return $this->liveEntry; }
    public function setLiveEntry(?XdrLedgerEntry $liveEntry): void { $this->liveEntry = $liveEntry; }
    public function getDeadEntry(): ?XdrLedgerKey { return $this->deadEntry; }
    public function setDeadEntry(?XdrLedgerKey $deadEntry): void { $this->deadEntry = $deadEntry; }
    public function getMetaEntry(): ?XdrBucketMetadata { return $this->metaEntry; }
    public function setMetaEntry(?XdrBucketMetadata $metaEntry): void { $this->metaEntry = $metaEntry; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): mixed {
        return match ($this->type->getValue()) {
            XdrBucketEntryType::LIVEENTRY => ['liveentry' => $this->liveEntry->toJsonValue()],
            XdrBucketEntryType::INITENTRY => ['initentry' => $this->liveEntry->toJsonValue()],
            XdrBucketEntryType::DEADENTRY => ['deadentry' => $this->deadEntry->toJsonValue()],
            XdrBucketEntryType::METAENTRY => ['metaentry' => $this->metaEntry->toJsonValue()],
            // @codeCoverageIgnoreStart
            default => throw new \InvalidArgumentException(
                'Unknown discriminant for type on XdrBucketEntryType'
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        // @sep51-union XdrBucketEntry shape=non_void
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value) || count($value) !== 1) {
            throw new \InvalidArgumentException(
                'Expected single-key object for XdrBucketEntry, got ' . get_debug_type($value)
            );
        }
        $key = array_key_first($value);
        if (!is_string($key)) {
            throw new \InvalidArgumentException(
                'Expected string arm key for XdrBucketEntry, got ' . get_debug_type($key)
            );
        }
        $arm = $value[$key];
        return match ($key) {
            'liveentry' => (static function () use ($arm) { $r = new static(new XdrBucketEntryType(XdrBucketEntryType::LIVEENTRY)); $r->liveEntry = XdrLedgerEntry::fromJsonValue($arm); return $r; })(),
            'initentry' => (static function () use ($arm) { $r = new static(new XdrBucketEntryType(XdrBucketEntryType::INITENTRY)); $r->liveEntry = XdrLedgerEntry::fromJsonValue($arm); return $r; })(),
            'deadentry' => (static function () use ($arm) { $r = new static(new XdrBucketEntryType(XdrBucketEntryType::DEADENTRY)); $r->deadEntry = XdrLedgerKey::fromJsonValue($arm); return $r; })(),
            'metaentry' => (static function () use ($arm) { $r = new static(new XdrBucketEntryType(XdrBucketEntryType::METAENTRY)); $r->metaEntry = XdrBucketMetadata::fromJsonValue($arm); return $r; })(),
            default => throw new \InvalidArgumentException(
                'Unknown arm key for XdrBucketEntry: ' . XdrJsonHelper::safePreview($key)
            ),
        };
    }

    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
