<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrBucketEntryType {
    public int $value;

    const METAENTRY = -1;
    const LIVEENTRY = 0;
    const DEADENTRY = 1;
    const INITENTRY = 2;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function METAENTRY(): XdrBucketEntryType {
        return new XdrBucketEntryType(XdrBucketEntryType::METAENTRY);
    }

    public static function LIVEENTRY(): XdrBucketEntryType {
        return new XdrBucketEntryType(XdrBucketEntryType::LIVEENTRY);
    }

    public static function DEADENTRY(): XdrBucketEntryType {
        return new XdrBucketEntryType(XdrBucketEntryType::DEADENTRY);
    }

    public static function INITENTRY(): XdrBucketEntryType {
        return new XdrBucketEntryType(XdrBucketEntryType::INITENTRY);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrBucketEntryType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case -1:
            case 0:
            case 1:
            case 2:
                return new XdrBucketEntryType($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
