<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrClaimAtom {

    public XdrClaimAtomType $type;
    public ?XdrClaimOfferAtomV0 $v0 = null;
    public ?XdrClaimOfferAtom $orderBook = null;
    public ?XdrClaimLiquidityAtom $liquidityPool = null;

    public function __construct(?XdrClaimAtomType $type = null) {
        if ($type !== null) {
            $this->type = $type;
        }
    }

    public function encode(): string {
        $bytes = $this->type->encode();
        switch ($this->type->getValue()) {
            case XdrClaimAtomType::V0:
                $bytes .= $this->v0->encode();
                break;
            case XdrClaimAtomType::ORDER_BOOK:
                $bytes .= $this->orderBook->encode();
                break;
            case XdrClaimAtomType::LIQUIDITY_POOL:
                $bytes .= $this->liquidityPool->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrClaimAtom {
        $result = new XdrClaimAtom(XdrClaimAtomType::decode($xdr));
        switch ($result->type->getValue()) {
            case XdrClaimAtomType::V0:
                $result->v0 = XdrClaimOfferAtomV0::decode($xdr);
                break;
            case XdrClaimAtomType::ORDER_BOOK:
                $result->orderBook = XdrClaimOfferAtom::decode($xdr);
                break;
            case XdrClaimAtomType::LIQUIDITY_POOL:
                $result->liquidityPool = XdrClaimLiquidityAtom::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getType(): XdrClaimAtomType { return $this->type; }
    public function setType(XdrClaimAtomType $type): void { $this->type = $type; }
    public function getV0(): ?XdrClaimOfferAtomV0 { return $this->v0; }
    public function setV0(?XdrClaimOfferAtomV0 $v0): void { $this->v0 = $v0; }
    public function getOrderBook(): ?XdrClaimOfferAtom { return $this->orderBook; }
    public function setOrderBook(?XdrClaimOfferAtom $orderBook): void { $this->orderBook = $orderBook; }
    public function getLiquidityPool(): ?XdrClaimLiquidityAtom { return $this->liquidityPool; }
    public function setLiquidityPool(?XdrClaimLiquidityAtom $liquidityPool): void { $this->liquidityPool = $liquidityPool; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
