<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrContractEventType {
    public int $value;

    const CONTRACT_EVENT_TYPE_SYSTEM = 0;
    const CONTRACT_EVENT_TYPE_CONTRACT = 1;
    const CONTRACT_EVENT_TYPE_DIAGNOSTIC = 2;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SYSTEM(): XdrContractEventType {
        return new XdrContractEventType(XdrContractEventType::CONTRACT_EVENT_TYPE_SYSTEM);
    }

    public static function CONTRACT(): XdrContractEventType {
        return new XdrContractEventType(XdrContractEventType::CONTRACT_EVENT_TYPE_CONTRACT);
    }

    public static function DIAGNOSTIC(): XdrContractEventType {
        return new XdrContractEventType(XdrContractEventType::CONTRACT_EVENT_TYPE_DIAGNOSTIC);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrContractEventType {
        $value = $xdr->readInteger32();
        return new XdrContractEventType($value);
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
