<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrContractCodeEntryV1 {

    public XdrExtensionPoint $ext;
    public XdrContractCodeCostInputs $costInputs;

    public function __construct(XdrExtensionPoint $ext, XdrContractCodeCostInputs $costInputs) {
        $this->ext = $ext;
        $this->costInputs = $costInputs;
    }

    public function encode(): string {
        $bytes = $this->ext->encode();
        $bytes .= $this->costInputs->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrContractCodeEntryV1 {
        $ext = XdrExtensionPoint::decode($xdr);
        $costInputs = XdrContractCodeCostInputs::decode($xdr);
        return new XdrContractCodeEntryV1($ext, $costInputs);
    }

    public function getExt(): XdrExtensionPoint { return $this->ext; }
    public function setExt(XdrExtensionPoint $ext): void { $this->ext = $ext; }
    public function getCostInputs(): XdrContractCodeCostInputs { return $this->costInputs; }
    public function setCostInputs(XdrContractCodeCostInputs $costInputs): void { $this->costInputs = $costInputs; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'ext' => $this->ext->toJsonValue(),
            'cost_inputs' => $this->costInputs->toJsonValue(),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrContractCodeEntryV1 JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('ext', $value)) {
            throw new InvalidArgumentException(
                'Missing required field ext for XdrContractCodeEntryV1'
            );
        }
        $ext = XdrExtensionPoint::fromJsonValue($value['ext']);
        if (!array_key_exists('cost_inputs', $value)) {
            throw new InvalidArgumentException(
                'Missing required field cost_inputs for XdrContractCodeEntryV1'
            );
        }
        $costInputs = XdrContractCodeCostInputs::fromJsonValue($value['cost_inputs']);
        return new static($ext, $costInputs);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
