<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrConfigSettingContractLedgerCostV0 {

    public int $ledgerMaxDiskReadLedgerEntries;
    public int $ledgerMaxDiskReadBytes;
    public int $ledgerMaxWriteLedgerEntries;
    public int $ledgerMaxWriteBytes;
    public int $txMaxDiskReadEntries;
    public int $txMaxDiskReadBytes;
    public int $txMaxWriteLedgerEntries;
    public int $txMaxWriteBytes;
    public int $feeDiskReadLedgerEntry;
    public int $feeWriteLedgerEntry;
    public int $feeDiskRead1KB;
    public int $sorobanStateTargetSizeBytes;
    public int $rentFee1KBSorobanStateSizeLow;
    public int $rentFee1KBSorobanStateSizeHigh;
    public int $sorobanStateRentFeeGrowthFactor;

    public function __construct(int $ledgerMaxDiskReadLedgerEntries, int $ledgerMaxDiskReadBytes, int $ledgerMaxWriteLedgerEntries, int $ledgerMaxWriteBytes, int $txMaxDiskReadEntries, int $txMaxDiskReadBytes, int $txMaxWriteLedgerEntries, int $txMaxWriteBytes, int $feeDiskReadLedgerEntry, int $feeWriteLedgerEntry, int $feeDiskRead1KB, int $sorobanStateTargetSizeBytes, int $rentFee1KBSorobanStateSizeLow, int $rentFee1KBSorobanStateSizeHigh, int $sorobanStateRentFeeGrowthFactor) {
        $this->ledgerMaxDiskReadLedgerEntries = $ledgerMaxDiskReadLedgerEntries;
        $this->ledgerMaxDiskReadBytes = $ledgerMaxDiskReadBytes;
        $this->ledgerMaxWriteLedgerEntries = $ledgerMaxWriteLedgerEntries;
        $this->ledgerMaxWriteBytes = $ledgerMaxWriteBytes;
        $this->txMaxDiskReadEntries = $txMaxDiskReadEntries;
        $this->txMaxDiskReadBytes = $txMaxDiskReadBytes;
        $this->txMaxWriteLedgerEntries = $txMaxWriteLedgerEntries;
        $this->txMaxWriteBytes = $txMaxWriteBytes;
        $this->feeDiskReadLedgerEntry = $feeDiskReadLedgerEntry;
        $this->feeWriteLedgerEntry = $feeWriteLedgerEntry;
        $this->feeDiskRead1KB = $feeDiskRead1KB;
        $this->sorobanStateTargetSizeBytes = $sorobanStateTargetSizeBytes;
        $this->rentFee1KBSorobanStateSizeLow = $rentFee1KBSorobanStateSizeLow;
        $this->rentFee1KBSorobanStateSizeHigh = $rentFee1KBSorobanStateSizeHigh;
        $this->sorobanStateRentFeeGrowthFactor = $sorobanStateRentFeeGrowthFactor;
    }

    public function encode(): string {
        $bytes = XdrEncoder::unsignedInteger32($this->ledgerMaxDiskReadLedgerEntries);
        $bytes .= XdrEncoder::unsignedInteger32($this->ledgerMaxDiskReadBytes);
        $bytes .= XdrEncoder::unsignedInteger32($this->ledgerMaxWriteLedgerEntries);
        $bytes .= XdrEncoder::unsignedInteger32($this->ledgerMaxWriteBytes);
        $bytes .= XdrEncoder::unsignedInteger32($this->txMaxDiskReadEntries);
        $bytes .= XdrEncoder::unsignedInteger32($this->txMaxDiskReadBytes);
        $bytes .= XdrEncoder::unsignedInteger32($this->txMaxWriteLedgerEntries);
        $bytes .= XdrEncoder::unsignedInteger32($this->txMaxWriteBytes);
        $bytes .= XdrEncoder::integer64($this->feeDiskReadLedgerEntry);
        $bytes .= XdrEncoder::integer64($this->feeWriteLedgerEntry);
        $bytes .= XdrEncoder::integer64($this->feeDiskRead1KB);
        $bytes .= XdrEncoder::integer64($this->sorobanStateTargetSizeBytes);
        $bytes .= XdrEncoder::integer64($this->rentFee1KBSorobanStateSizeLow);
        $bytes .= XdrEncoder::integer64($this->rentFee1KBSorobanStateSizeHigh);
        $bytes .= XdrEncoder::unsignedInteger32($this->sorobanStateRentFeeGrowthFactor);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrConfigSettingContractLedgerCostV0 {
        $ledgerMaxDiskReadLedgerEntries = $xdr->readUnsignedInteger32();
        $ledgerMaxDiskReadBytes = $xdr->readUnsignedInteger32();
        $ledgerMaxWriteLedgerEntries = $xdr->readUnsignedInteger32();
        $ledgerMaxWriteBytes = $xdr->readUnsignedInteger32();
        $txMaxDiskReadEntries = $xdr->readUnsignedInteger32();
        $txMaxDiskReadBytes = $xdr->readUnsignedInteger32();
        $txMaxWriteLedgerEntries = $xdr->readUnsignedInteger32();
        $txMaxWriteBytes = $xdr->readUnsignedInteger32();
        $feeDiskReadLedgerEntry = $xdr->readInteger64();
        $feeWriteLedgerEntry = $xdr->readInteger64();
        $feeDiskRead1KB = $xdr->readInteger64();
        $sorobanStateTargetSizeBytes = $xdr->readInteger64();
        $rentFee1KBSorobanStateSizeLow = $xdr->readInteger64();
        $rentFee1KBSorobanStateSizeHigh = $xdr->readInteger64();
        $sorobanStateRentFeeGrowthFactor = $xdr->readUnsignedInteger32();
        return new XdrConfigSettingContractLedgerCostV0($ledgerMaxDiskReadLedgerEntries, $ledgerMaxDiskReadBytes, $ledgerMaxWriteLedgerEntries, $ledgerMaxWriteBytes, $txMaxDiskReadEntries, $txMaxDiskReadBytes, $txMaxWriteLedgerEntries, $txMaxWriteBytes, $feeDiskReadLedgerEntry, $feeWriteLedgerEntry, $feeDiskRead1KB, $sorobanStateTargetSizeBytes, $rentFee1KBSorobanStateSizeLow, $rentFee1KBSorobanStateSizeHigh, $sorobanStateRentFeeGrowthFactor);
    }

    public function getLedgerMaxDiskReadLedgerEntries(): int { return $this->ledgerMaxDiskReadLedgerEntries; }
    public function setLedgerMaxDiskReadLedgerEntries(int $ledgerMaxDiskReadLedgerEntries): void { $this->ledgerMaxDiskReadLedgerEntries = $ledgerMaxDiskReadLedgerEntries; }
    public function getLedgerMaxDiskReadBytes(): int { return $this->ledgerMaxDiskReadBytes; }
    public function setLedgerMaxDiskReadBytes(int $ledgerMaxDiskReadBytes): void { $this->ledgerMaxDiskReadBytes = $ledgerMaxDiskReadBytes; }
    public function getLedgerMaxWriteLedgerEntries(): int { return $this->ledgerMaxWriteLedgerEntries; }
    public function setLedgerMaxWriteLedgerEntries(int $ledgerMaxWriteLedgerEntries): void { $this->ledgerMaxWriteLedgerEntries = $ledgerMaxWriteLedgerEntries; }
    public function getLedgerMaxWriteBytes(): int { return $this->ledgerMaxWriteBytes; }
    public function setLedgerMaxWriteBytes(int $ledgerMaxWriteBytes): void { $this->ledgerMaxWriteBytes = $ledgerMaxWriteBytes; }
    public function getTxMaxDiskReadEntries(): int { return $this->txMaxDiskReadEntries; }
    public function setTxMaxDiskReadEntries(int $txMaxDiskReadEntries): void { $this->txMaxDiskReadEntries = $txMaxDiskReadEntries; }
    public function getTxMaxDiskReadBytes(): int { return $this->txMaxDiskReadBytes; }
    public function setTxMaxDiskReadBytes(int $txMaxDiskReadBytes): void { $this->txMaxDiskReadBytes = $txMaxDiskReadBytes; }
    public function getTxMaxWriteLedgerEntries(): int { return $this->txMaxWriteLedgerEntries; }
    public function setTxMaxWriteLedgerEntries(int $txMaxWriteLedgerEntries): void { $this->txMaxWriteLedgerEntries = $txMaxWriteLedgerEntries; }
    public function getTxMaxWriteBytes(): int { return $this->txMaxWriteBytes; }
    public function setTxMaxWriteBytes(int $txMaxWriteBytes): void { $this->txMaxWriteBytes = $txMaxWriteBytes; }
    public function getFeeDiskReadLedgerEntry(): int { return $this->feeDiskReadLedgerEntry; }
    public function setFeeDiskReadLedgerEntry(int $feeDiskReadLedgerEntry): void { $this->feeDiskReadLedgerEntry = $feeDiskReadLedgerEntry; }
    public function getFeeWriteLedgerEntry(): int { return $this->feeWriteLedgerEntry; }
    public function setFeeWriteLedgerEntry(int $feeWriteLedgerEntry): void { $this->feeWriteLedgerEntry = $feeWriteLedgerEntry; }
    public function getFeeDiskRead1KB(): int { return $this->feeDiskRead1KB; }
    public function setFeeDiskRead1KB(int $feeDiskRead1KB): void { $this->feeDiskRead1KB = $feeDiskRead1KB; }
    public function getSorobanStateTargetSizeBytes(): int { return $this->sorobanStateTargetSizeBytes; }
    public function setSorobanStateTargetSizeBytes(int $sorobanStateTargetSizeBytes): void { $this->sorobanStateTargetSizeBytes = $sorobanStateTargetSizeBytes; }
    public function getRentFee1KBSorobanStateSizeLow(): int { return $this->rentFee1KBSorobanStateSizeLow; }
    public function setRentFee1KBSorobanStateSizeLow(int $rentFee1KBSorobanStateSizeLow): void { $this->rentFee1KBSorobanStateSizeLow = $rentFee1KBSorobanStateSizeLow; }
    public function getRentFee1KBSorobanStateSizeHigh(): int { return $this->rentFee1KBSorobanStateSizeHigh; }
    public function setRentFee1KBSorobanStateSizeHigh(int $rentFee1KBSorobanStateSizeHigh): void { $this->rentFee1KBSorobanStateSizeHigh = $rentFee1KBSorobanStateSizeHigh; }
    public function getSorobanStateRentFeeGrowthFactor(): int { return $this->sorobanStateRentFeeGrowthFactor; }
    public function setSorobanStateRentFeeGrowthFactor(int $sorobanStateRentFeeGrowthFactor): void { $this->sorobanStateRentFeeGrowthFactor = $sorobanStateRentFeeGrowthFactor; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
