<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrClawbackClaimableBalanceResultCode {
    public int $value;

    const SUCCESS = 0;
    const DOES_NOT_EXIST = -1;
    const NOT_ISSUER = -2;
    const NOT_CLAWBACK_ENABLED = -3;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SUCCESS(): XdrClawbackClaimableBalanceResultCode {
        return new XdrClawbackClaimableBalanceResultCode(XdrClawbackClaimableBalanceResultCode::SUCCESS);
    }

    public static function DOES_NOT_EXIST(): XdrClawbackClaimableBalanceResultCode {
        return new XdrClawbackClaimableBalanceResultCode(XdrClawbackClaimableBalanceResultCode::DOES_NOT_EXIST);
    }

    public static function NOT_ISSUER(): XdrClawbackClaimableBalanceResultCode {
        return new XdrClawbackClaimableBalanceResultCode(XdrClawbackClaimableBalanceResultCode::NOT_ISSUER);
    }

    public static function NOT_CLAWBACK_ENABLED(): XdrClawbackClaimableBalanceResultCode {
        return new XdrClawbackClaimableBalanceResultCode(XdrClawbackClaimableBalanceResultCode::NOT_CLAWBACK_ENABLED);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrClawbackClaimableBalanceResultCode {
        $value = $xdr->readInteger32();
        return new XdrClawbackClaimableBalanceResultCode($value);
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
