<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrContractDataEntry {

    public XdrExtensionPoint $ext;
    public XdrSCAddress $contract;
    public XdrSCVal $key;
    public XdrContractDataDurability $durability;
    public XdrSCVal $val;

    public function __construct(XdrExtensionPoint $ext, XdrSCAddress $contract, XdrSCVal $key, XdrContractDataDurability $durability, XdrSCVal $val) {
        $this->ext = $ext;
        $this->contract = $contract;
        $this->key = $key;
        $this->durability = $durability;
        $this->val = $val;
    }

    public function encode(): string {
        $bytes = $this->ext->encode();
        $bytes .= $this->contract->encode();
        $bytes .= $this->key->encode();
        $bytes .= $this->durability->encode();
        $bytes .= $this->val->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrContractDataEntry {
        $ext = XdrExtensionPoint::decode($xdr);
        $contract = XdrSCAddress::decode($xdr);
        $key = XdrSCVal::decode($xdr);
        $durability = XdrContractDataDurability::decode($xdr);
        $val = XdrSCVal::decode($xdr);
        return new XdrContractDataEntry($ext, $contract, $key, $durability, $val);
    }

    public function getExt(): XdrExtensionPoint { return $this->ext; }
    public function setExt(XdrExtensionPoint $ext): void { $this->ext = $ext; }
    public function getContract(): XdrSCAddress { return $this->contract; }
    public function setContract(XdrSCAddress $contract): void { $this->contract = $contract; }
    public function getKey(): XdrSCVal { return $this->key; }
    public function setKey(XdrSCVal $key): void { $this->key = $key; }
    public function getDurability(): XdrContractDataDurability { return $this->durability; }
    public function setDurability(XdrContractDataDurability $durability): void { $this->durability = $durability; }
    public function getVal(): XdrSCVal { return $this->val; }
    public function setVal(XdrSCVal $val): void { $this->val = $val; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
