<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrCryptoKeyType {
    public int $value;

    const KEY_TYPE_ED25519 = 0;
    const KEY_TYPE_PRE_AUTH_TX = 1;
    const KEY_TYPE_HASH_X = 2;
    const KEY_TYPE_ED25519_SIGNED_PAYLOAD = 3;
    const KEY_TYPE_MUXED_ED25519 = 256;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function KEY_TYPE_ED25519(): XdrCryptoKeyType {
        return new XdrCryptoKeyType(XdrCryptoKeyType::KEY_TYPE_ED25519);
    }

    public static function KEY_TYPE_PRE_AUTH_TX(): XdrCryptoKeyType {
        return new XdrCryptoKeyType(XdrCryptoKeyType::KEY_TYPE_PRE_AUTH_TX);
    }

    public static function KEY_TYPE_HASH_X(): XdrCryptoKeyType {
        return new XdrCryptoKeyType(XdrCryptoKeyType::KEY_TYPE_HASH_X);
    }

    public static function KEY_TYPE_ED25519_SIGNED_PAYLOAD(): XdrCryptoKeyType {
        return new XdrCryptoKeyType(XdrCryptoKeyType::KEY_TYPE_ED25519_SIGNED_PAYLOAD);
    }

    public static function KEY_TYPE_MUXED_ED25519(): XdrCryptoKeyType {
        return new XdrCryptoKeyType(XdrCryptoKeyType::KEY_TYPE_MUXED_ED25519);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrCryptoKeyType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 256:
                return new XdrCryptoKeyType($value);
            default:
                throw new InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::KEY_TYPE_ED25519 => 'ed25519',
            self::KEY_TYPE_PRE_AUTH_TX => 'pre_auth_tx',
            self::KEY_TYPE_HASH_X => 'hash_x',
            self::KEY_TYPE_ED25519_SIGNED_PAYLOAD => 'ed25519_signed_payload',
            self::KEY_TYPE_MUXED_ED25519 => 'muxed_ed25519',
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown XdrCryptoKeyType enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new InvalidArgumentException(
                'Expected string for XdrCryptoKeyType JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'ed25519' => new static(self::KEY_TYPE_ED25519),
            'pre_auth_tx' => new static(self::KEY_TYPE_PRE_AUTH_TX),
            'hash_x' => new static(self::KEY_TYPE_HASH_X),
            'ed25519_signed_payload' => new static(self::KEY_TYPE_ED25519_SIGNED_PAYLOAD),
            'muxed_ed25519' => new static(self::KEY_TYPE_MUXED_ED25519),
            default => throw new InvalidArgumentException(
                'Unknown XdrCryptoKeyType JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }

    public function enumName(): string {
        switch ($this->value) {
            case self::KEY_TYPE_ED25519:
                return 'KEY_TYPE_ED25519';
            case self::KEY_TYPE_PRE_AUTH_TX:
                return 'KEY_TYPE_PRE_AUTH_TX';
            case self::KEY_TYPE_HASH_X:
                return 'KEY_TYPE_HASH_X';
            case self::KEY_TYPE_ED25519_SIGNED_PAYLOAD:
                return 'KEY_TYPE_ED25519_SIGNED_PAYLOAD';
            case self::KEY_TYPE_MUXED_ED25519:
                return 'KEY_TYPE_MUXED_ED25519';
            default:
                return 'XdrCryptoKeyType#' . $this->value;
        }
    }

    public static function fromTxRepName(string $name): static {
        switch ($name) {
            case 'KEY_TYPE_ED25519':
                return new static(self::KEY_TYPE_ED25519);
            case 'KEY_TYPE_PRE_AUTH_TX':
                return new static(self::KEY_TYPE_PRE_AUTH_TX);
            case 'KEY_TYPE_HASH_X':
                return new static(self::KEY_TYPE_HASH_X);
            case 'KEY_TYPE_ED25519_SIGNED_PAYLOAD':
                return new static(self::KEY_TYPE_ED25519_SIGNED_PAYLOAD);
            case 'KEY_TYPE_MUXED_ED25519':
                return new static(self::KEY_TYPE_MUXED_ED25519);
            default:
                $prefix = 'XdrCryptoKeyType#';
                if (str_starts_with($name, $prefix)) {
                    $val = (int) substr($name, strlen($prefix));
                    return new static($val);
                }
                throw new InvalidArgumentException('Unknown enum value: ' . $name);
        }
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix] = $this->enumName();
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $raw = TxRepHelper::getValue($map, $prefix);
        if ($raw === null) {
            throw new InvalidArgumentException('Missing TxRep value for: ' . $prefix);
        }
        return self::fromTxRepName($raw);
    }
}
