<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrContractExecutableBase {

    public XdrContractExecutableType $type;
    public ?string $wasmIdHex = null;
    public ?XdrContractExecutableExternalRef $externalRef = null;

    public function __construct(?XdrContractExecutableType $type = null) {
        if ($type !== null) {
            $this->type = $type;
        }
    }

    public function encode(): string {
        $bytes = $this->type->encode();
        switch ($this->type->getValue()) {
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_WASM:
                $bytes .= XdrEncoder::opaqueFixed(pack('H*', $this->wasmIdHex), 32);
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_STELLAR_ASSET:
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_EXTERNAL_REF:
                $bytes .= $this->externalRef->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): static {
        $result = new static(XdrContractExecutableType::decode($xdr));
        switch ($result->type->getValue()) {
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_WASM:
                $result->wasmIdHex = bin2hex($xdr->readOpaqueFixed(32));
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_STELLAR_ASSET:
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_EXTERNAL_REF:
                $result->externalRef = XdrContractExecutableExternalRef::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getType(): XdrContractExecutableType { return $this->type; }
    public function setType(XdrContractExecutableType $type): void { $this->type = $type; }
    public function getWasmIdHex(): ?string { return $this->wasmIdHex; }
    public function setWasmIdHex(?string $wasmIdHex): void { $this->wasmIdHex = $wasmIdHex; }
    public function getExternalRef(): ?XdrContractExecutableExternalRef { return $this->externalRef; }
    public function setExternalRef(?XdrContractExecutableExternalRef $externalRef): void { $this->externalRef = $externalRef; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): mixed {
        return match ($this->type->getValue()) {
            XdrContractExecutableType::CONTRACT_EXECUTABLE_WASM => ['wasm' => (static function ($v) { if (!is_string($v) || strlen($v) !== 64 || !ctype_xdigit($v)) { throw new InvalidArgumentException('Expected 64-character hex wasm hash, got ' . (is_string($v) ? strlen($v) . '-character string' : get_debug_type($v))); } return strtolower($v); })($this->wasmIdHex)],
            XdrContractExecutableType::CONTRACT_EXECUTABLE_STELLAR_ASSET => 'stellar_asset',
            XdrContractExecutableType::CONTRACT_EXECUTABLE_EXTERNAL_REF => ['external_ref' => $this->externalRef->toJsonValue()],
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown discriminant for type on XdrContractExecutableType'
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (is_string($value)) {
            return match ($value) {
                'stellar_asset' => new static(new XdrContractExecutableType(XdrContractExecutableType::CONTRACT_EXECUTABLE_STELLAR_ASSET)),
                'wasm' => throw new InvalidArgumentException(
                    "Arm 'wasm' on XdrContractExecutableBase is non-void; supply a single-key object {\"wasm\": <payload>} instead of a bare string."
                ),
                'external_ref' => throw new InvalidArgumentException(
                    "Arm 'external_ref' on XdrContractExecutableBase is non-void; supply a single-key object {\"external_ref\": <payload>} instead of a bare string."
                ),
                default => throw new InvalidArgumentException(
                    'Unknown XdrContractExecutableBase void arm string: ' . XdrJsonHelper::safePreview($value)
                ),
            };
        }
        if (!is_array($value) || count($value) !== 1) {
            throw new InvalidArgumentException(
                'Expected single-key object or void-arm string for XdrContractExecutableBase, got ' . get_debug_type($value)
            );
        }
        $key = array_key_first($value);
        if (!is_string($key)) {
            throw new InvalidArgumentException(
                'Expected string arm key for XdrContractExecutableBase, got ' . get_debug_type($key)
            );
        }
        $arm = $value[$key];
        return match ($key) {
            'wasm' => (static function () use ($arm) { $r = new static(new XdrContractExecutableType(XdrContractExecutableType::CONTRACT_EXECUTABLE_WASM)); $r->wasmIdHex = (static function ($v) { if (!is_string($v)) { throw new InvalidArgumentException('Expected string JSON value for SEP-51 field, got ' . get_debug_type($v)); } if (strlen($v) !== 64 || !ctype_xdigit($v)) { throw new InvalidArgumentException('Expected 64-character hex wasm hash, got ' . strlen($v) . '-character string'); } return strtolower($v); })($arm); return $r; })(),
            'external_ref' => (static function () use ($arm) { $r = new static(new XdrContractExecutableType(XdrContractExecutableType::CONTRACT_EXECUTABLE_EXTERNAL_REF)); $r->externalRef = XdrContractExecutableExternalRef::fromJsonValue($arm); return $r; })(),
            default => throw new InvalidArgumentException(
                'Unknown arm key for XdrContractExecutableBase: ' . XdrJsonHelper::safePreview($key)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If an object in $json repeats a key, or if
     *         the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(XdrJsonHelper::decodeText($json));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $this->type->toTxRep($prefix . '.type', $lines);
        switch ($this->type->getValue()) {
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_WASM:
                $lines[$prefix . '.wasm_hash'] = $this->wasmIdHex;
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_STELLAR_ASSET:
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_EXTERNAL_REF:
                $this->externalRef->toTxRep($prefix . '.external_ref', $lines);
                break;
            default:
                break;
        }
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $disc = XdrContractExecutableType::fromTxRep($map, $prefix . '.type');
        $result = new static($disc);
        switch ($result->type->getValue()) {
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_WASM:
                $result->wasmIdHex = TxRepHelper::getValue($map, $prefix . '.wasm_hash') ?? '';
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_STELLAR_ASSET:
                break;
            case XdrContractExecutableType::CONTRACT_EXECUTABLE_EXTERNAL_REF:
                $result->externalRef = XdrContractExecutableExternalRef::fromTxRep($map, $prefix . '.external_ref');
                break;
            default:
                break;
        }
        return $result;
    }
}
