<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrCreateClaimableBalanceResultCode {
    public int $value;

    const SUCCESS = 0;
    const MALFORMED = -1;
    const LOW_RESERVE = -2;
    const NO_TRUST = -3;
    const NOT_AUTHORIZED = -4;
    const UNDERFUNDED = -5;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SUCCESS(): XdrCreateClaimableBalanceResultCode {
        return new XdrCreateClaimableBalanceResultCode(XdrCreateClaimableBalanceResultCode::SUCCESS);
    }

    public static function MALFORMED(): XdrCreateClaimableBalanceResultCode {
        return new XdrCreateClaimableBalanceResultCode(XdrCreateClaimableBalanceResultCode::MALFORMED);
    }

    public static function LOW_RESERVE(): XdrCreateClaimableBalanceResultCode {
        return new XdrCreateClaimableBalanceResultCode(XdrCreateClaimableBalanceResultCode::LOW_RESERVE);
    }

    public static function NO_TRUST(): XdrCreateClaimableBalanceResultCode {
        return new XdrCreateClaimableBalanceResultCode(XdrCreateClaimableBalanceResultCode::NO_TRUST);
    }

    public static function NOT_AUTHORIZED(): XdrCreateClaimableBalanceResultCode {
        return new XdrCreateClaimableBalanceResultCode(XdrCreateClaimableBalanceResultCode::NOT_AUTHORIZED);
    }

    public static function UNDERFUNDED(): XdrCreateClaimableBalanceResultCode {
        return new XdrCreateClaimableBalanceResultCode(XdrCreateClaimableBalanceResultCode::UNDERFUNDED);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrCreateClaimableBalanceResultCode {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case -1:
            case -2:
            case -3:
            case -4:
            case -5:
                return new XdrCreateClaimableBalanceResultCode($value);
            default:
                throw new InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::SUCCESS => 'success',
            self::MALFORMED => 'malformed',
            self::LOW_RESERVE => 'low_reserve',
            self::NO_TRUST => 'no_trust',
            self::NOT_AUTHORIZED => 'not_authorized',
            self::UNDERFUNDED => 'underfunded',
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown XdrCreateClaimableBalanceResultCode enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new InvalidArgumentException(
                'Expected string for XdrCreateClaimableBalanceResultCode JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'success' => new static(self::SUCCESS),
            'malformed' => new static(self::MALFORMED),
            'low_reserve' => new static(self::LOW_RESERVE),
            'no_trust' => new static(self::NO_TRUST),
            'not_authorized' => new static(self::NOT_AUTHORIZED),
            'underfunded' => new static(self::UNDERFUNDED),
            default => throw new InvalidArgumentException(
                'Unknown XdrCreateClaimableBalanceResultCode JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
