<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrConfigSettingContractBandwidthV0 {

    public int $ledgerMaxTxsSizeBytes;
    public int $txMaxSizeBytes;
    public int $feeTxSize1KB;

    public function __construct(int $ledgerMaxTxsSizeBytes, int $txMaxSizeBytes, int $feeTxSize1KB) {
        $this->ledgerMaxTxsSizeBytes = $ledgerMaxTxsSizeBytes;
        $this->txMaxSizeBytes = $txMaxSizeBytes;
        $this->feeTxSize1KB = $feeTxSize1KB;
    }

    public function encode(): string {
        $bytes = XdrEncoder::unsignedInteger32($this->ledgerMaxTxsSizeBytes);
        $bytes .= XdrEncoder::unsignedInteger32($this->txMaxSizeBytes);
        $bytes .= XdrEncoder::integer64($this->feeTxSize1KB);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrConfigSettingContractBandwidthV0 {
        $ledgerMaxTxsSizeBytes = $xdr->readUnsignedInteger32();
        $txMaxSizeBytes = $xdr->readUnsignedInteger32();
        $feeTxSize1KB = $xdr->readInteger64();
        return new XdrConfigSettingContractBandwidthV0($ledgerMaxTxsSizeBytes, $txMaxSizeBytes, $feeTxSize1KB);
    }

    public function getLedgerMaxTxsSizeBytes(): int { return $this->ledgerMaxTxsSizeBytes; }
    public function setLedgerMaxTxsSizeBytes(int $ledgerMaxTxsSizeBytes): void { $this->ledgerMaxTxsSizeBytes = $ledgerMaxTxsSizeBytes; }
    public function getTxMaxSizeBytes(): int { return $this->txMaxSizeBytes; }
    public function setTxMaxSizeBytes(int $txMaxSizeBytes): void { $this->txMaxSizeBytes = $txMaxSizeBytes; }
    public function getFeeTxSize1KB(): int { return $this->feeTxSize1KB; }
    public function setFeeTxSize1KB(int $feeTxSize1KB): void { $this->feeTxSize1KB = $feeTxSize1KB; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'ledger_max_txs_size_bytes' => $this->ledgerMaxTxsSizeBytes,
            'tx_max_size_bytes' => $this->txMaxSizeBytes,
            'fee_tx_size1_kb' => XdrJsonHelper::int64ToString($this->feeTxSize1KB),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrConfigSettingContractBandwidthV0 JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('ledger_max_txs_size_bytes', $value)) {
            throw new InvalidArgumentException(
                'Missing required field ledger_max_txs_size_bytes for XdrConfigSettingContractBandwidthV0'
            );
        }
        $ledgerMaxTxsSizeBytes = (static function ($v) { if (!is_int($v)) { throw new InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['ledger_max_txs_size_bytes']);
        if (!array_key_exists('tx_max_size_bytes', $value)) {
            throw new InvalidArgumentException(
                'Missing required field tx_max_size_bytes for XdrConfigSettingContractBandwidthV0'
            );
        }
        $txMaxSizeBytes = (static function ($v) { if (!is_int($v)) { throw new InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['tx_max_size_bytes']);
        if (!array_key_exists('fee_tx_size1_kb', $value)) {
            throw new InvalidArgumentException(
                'Missing required field fee_tx_size1_kb for XdrConfigSettingContractBandwidthV0'
            );
        }
        $feeTxSize1KB = (static function ($v) { if (!is_string($v) && !is_int($v)) { throw new InvalidArgumentException('Expected int64 JSON value (string or int), got ' . get_debug_type($v)); } return XdrJsonHelper::stringToInt64($v); })($value['fee_tx_size1_kb']);
        return new static($ledgerMaxTxsSizeBytes, $txMaxSizeBytes, $feeTxSize1KB);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
