<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrError {

    public XdrErrorCode $code;
    public string $msg;

    public function __construct(XdrErrorCode $code, string $msg) {
        $this->code = $code;
        $this->msg = $msg;
    }

    public function encode(): string {
        $bytes = $this->code->encode();
        $bytes .= XdrEncoder::string($this->msg);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrError {
        $code = XdrErrorCode::decode($xdr);
        $msg = $xdr->readString();
        return new XdrError($code, $msg);
    }

    public function getCode(): XdrErrorCode { return $this->code; }
    public function setCode(XdrErrorCode $code): void { $this->code = $code; }
    public function getMsg(): string { return $this->msg; }
    public function setMsg(string $msg): void { $this->msg = $msg; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
