<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrErrorCode {
    public int $value;

    const ERR_MISC = 0;
    const ERR_DATA = 1;
    const ERR_CONF = 2;
    const ERR_AUTH = 3;
    const ERR_LOAD = 4;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function ERR_MISC(): XdrErrorCode {
        return new XdrErrorCode(XdrErrorCode::ERR_MISC);
    }

    public static function ERR_DATA(): XdrErrorCode {
        return new XdrErrorCode(XdrErrorCode::ERR_DATA);
    }

    public static function ERR_CONF(): XdrErrorCode {
        return new XdrErrorCode(XdrErrorCode::ERR_CONF);
    }

    public static function ERR_AUTH(): XdrErrorCode {
        return new XdrErrorCode(XdrErrorCode::ERR_AUTH);
    }

    public static function ERR_LOAD(): XdrErrorCode {
        return new XdrErrorCode(XdrErrorCode::ERR_LOAD);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrErrorCode {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
                return new XdrErrorCode($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
