<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrEndSponsoringFutureReservesResultCode {
    public int $value;

    const SUCCESS = 0;
    const NOT_SPONSORED = -1;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SUCCESS(): XdrEndSponsoringFutureReservesResultCode {
        return new XdrEndSponsoringFutureReservesResultCode(XdrEndSponsoringFutureReservesResultCode::SUCCESS);
    }

    public static function NOT_SPONSORED(): XdrEndSponsoringFutureReservesResultCode {
        return new XdrEndSponsoringFutureReservesResultCode(XdrEndSponsoringFutureReservesResultCode::NOT_SPONSORED);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrEndSponsoringFutureReservesResultCode {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case -1:
                return new XdrEndSponsoringFutureReservesResultCode($value);
            default:
                throw new InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::SUCCESS => 'success',
            self::NOT_SPONSORED => 'not_sponsored',
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown XdrEndSponsoringFutureReservesResultCode enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new InvalidArgumentException(
                'Expected string for XdrEndSponsoringFutureReservesResultCode JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'success' => new static(self::SUCCESS),
            'not_sponsored' => new static(self::NOT_SPONSORED),
            default => throw new InvalidArgumentException(
                'Unknown XdrEndSponsoringFutureReservesResultCode JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
