<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrExtendFootprintTTLOp {

    public XdrExtensionPoint $ext;
    public int $extendTo;

    public function __construct(XdrExtensionPoint $ext, int $extendTo) {
        $this->ext = $ext;
        $this->extendTo = $extendTo;
    }

    public function encode(): string {
        $bytes = $this->ext->encode();
        $bytes .= XdrEncoder::unsignedInteger32($this->extendTo);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrExtendFootprintTTLOp {
        $ext = XdrExtensionPoint::decode($xdr);
        $extendTo = $xdr->readUnsignedInteger32();
        return new XdrExtendFootprintTTLOp($ext, $extendTo);
    }

    public function getExt(): XdrExtensionPoint { return $this->ext; }
    public function setExt(XdrExtensionPoint $ext): void { $this->ext = $ext; }
    public function getExtendTo(): int { return $this->extendTo; }
    public function setExtendTo(int $extendTo): void { $this->extendTo = $extendTo; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'ext' => $this->ext->toJsonValue(),
            'extend_to' => $this->extendTo,
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrExtendFootprintTTLOp JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('ext', $value)) {
            throw new InvalidArgumentException(
                'Missing required field ext for XdrExtendFootprintTTLOp'
            );
        }
        $ext = XdrExtensionPoint::fromJsonValue($value['ext']);
        if (!array_key_exists('extend_to', $value)) {
            throw new InvalidArgumentException(
                'Missing required field extend_to for XdrExtendFootprintTTLOp'
            );
        }
        $extendTo = (static function ($v) { if (!is_int($v)) { throw new InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['extend_to']);
        return new static($ext, $extendTo);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $this->ext->toTxRep($prefix . '.ext', $lines);
        $lines[$prefix . '.extendTo'] = (string)$this->extendTo;
    }

    public static function fromTxRep(array $map, string $prefix): XdrExtendFootprintTTLOp {
        $ext = XdrExtensionPoint::fromTxRep($map, $prefix . '.ext');
        $extendTo = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.extendTo') ?? '0');
        return new XdrExtendFootprintTTLOp($ext, $extendTo);
    }
}
