<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrFloodAdvert {

    public XdrTxAdvertVector $txHashes;

    public function __construct(XdrTxAdvertVector $txHashes) {
        $this->txHashes = $txHashes;
    }

    public function encode(): string {
        $bytes = $this->txHashes->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrFloodAdvert {
        $txHashes = XdrTxAdvertVector::decode($xdr);
        return new XdrFloodAdvert($txHashes);
    }

    public function getTxHashes(): XdrTxAdvertVector { return $this->txHashes; }
    public function setTxHashes(XdrTxAdvertVector $txHashes): void { $this->txHashes = $txHashes; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
