<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrHashIDPreimageContractID {

    public string $networkID;
    public XdrContractIDPreimage $contractIDPreimage;

    public function __construct(string $networkID, XdrContractIDPreimage $contractIDPreimage) {
        $this->networkID = $networkID;
        $this->contractIDPreimage = $contractIDPreimage;
    }

    public function encode(): string {
        $bytes = XdrEncoder::opaqueFixed($this->networkID, 32);
        $bytes .= $this->contractIDPreimage->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrHashIDPreimageContractID {
        $networkID = $xdr->readOpaqueFixed(32);
        $contractIDPreimage = XdrContractIDPreimage::decode($xdr);
        return new XdrHashIDPreimageContractID($networkID, $contractIDPreimage);
    }

    public function getNetworkID(): string { return $this->networkID; }
    public function setNetworkID(string $networkID): void { $this->networkID = $networkID; }
    public function getContractIDPreimage(): XdrContractIDPreimage { return $this->contractIDPreimage; }
    public function setContractIDPreimage(XdrContractIDPreimage $contractIDPreimage): void { $this->contractIDPreimage = $contractIDPreimage; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
