<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrHello {

    public int $ledgerVersion;
    public int $overlayVersion;
    public int $overlayMinVersion;
    public string $networkID;
    public string $versionStr;
    public int $listeningPort;
    public XdrNodeID $peerID;
    public XdrAuthCert $cert;
    public string $nonce;

    public function __construct(int $ledgerVersion, int $overlayVersion, int $overlayMinVersion, string $networkID, string $versionStr, int $listeningPort, XdrNodeID $peerID, XdrAuthCert $cert, string $nonce) {
        $this->ledgerVersion = $ledgerVersion;
        $this->overlayVersion = $overlayVersion;
        $this->overlayMinVersion = $overlayMinVersion;
        $this->networkID = $networkID;
        $this->versionStr = $versionStr;
        $this->listeningPort = $listeningPort;
        $this->peerID = $peerID;
        $this->cert = $cert;
        $this->nonce = $nonce;
    }

    public function encode(): string {
        $bytes = XdrEncoder::unsignedInteger32($this->ledgerVersion);
        $bytes .= XdrEncoder::unsignedInteger32($this->overlayVersion);
        $bytes .= XdrEncoder::unsignedInteger32($this->overlayMinVersion);
        $bytes .= XdrEncoder::opaqueFixed($this->networkID, 32);
        $bytes .= XdrEncoder::string($this->versionStr);
        $bytes .= XdrEncoder::integer32($this->listeningPort);
        $bytes .= $this->peerID->encode();
        $bytes .= $this->cert->encode();
        $bytes .= XdrEncoder::opaqueFixed($this->nonce, 32);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrHello {
        $ledgerVersion = $xdr->readUnsignedInteger32();
        $overlayVersion = $xdr->readUnsignedInteger32();
        $overlayMinVersion = $xdr->readUnsignedInteger32();
        $networkID = $xdr->readOpaqueFixed(32);
        $versionStr = $xdr->readString();
        $listeningPort = $xdr->readInteger32();
        $peerID = XdrNodeID::decode($xdr);
        $cert = XdrAuthCert::decode($xdr);
        $nonce = $xdr->readOpaqueFixed(32);
        return new XdrHello($ledgerVersion, $overlayVersion, $overlayMinVersion, $networkID, $versionStr, $listeningPort, $peerID, $cert, $nonce);
    }

    public function getLedgerVersion(): int { return $this->ledgerVersion; }
    public function setLedgerVersion(int $ledgerVersion): void { $this->ledgerVersion = $ledgerVersion; }
    public function getOverlayVersion(): int { return $this->overlayVersion; }
    public function setOverlayVersion(int $overlayVersion): void { $this->overlayVersion = $overlayVersion; }
    public function getOverlayMinVersion(): int { return $this->overlayMinVersion; }
    public function setOverlayMinVersion(int $overlayMinVersion): void { $this->overlayMinVersion = $overlayMinVersion; }
    public function getNetworkID(): string { return $this->networkID; }
    public function setNetworkID(string $networkID): void { $this->networkID = $networkID; }
    public function getVersionStr(): string { return $this->versionStr; }
    public function setVersionStr(string $versionStr): void { $this->versionStr = $versionStr; }
    public function getListeningPort(): int { return $this->listeningPort; }
    public function setListeningPort(int $listeningPort): void { $this->listeningPort = $listeningPort; }
    public function getPeerID(): XdrNodeID { return $this->peerID; }
    public function setPeerID(XdrNodeID $peerID): void { $this->peerID = $peerID; }
    public function getCert(): XdrAuthCert { return $this->cert; }
    public function setCert(XdrAuthCert $cert): void { $this->cert = $cert; }
    public function getNonce(): string { return $this->nonce; }
    public function setNonce(string $nonce): void { $this->nonce = $nonce; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
