<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrHmacSha256Mac {

    public string $mac;

    public function __construct(string $mac) {
        $this->mac = $mac;
    }

    public function encode(): string {
        $bytes = XdrEncoder::opaqueFixed($this->mac, 32);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrHmacSha256Mac {
        $mac = $xdr->readOpaqueFixed(32);
        return new XdrHmacSha256Mac($mac);
    }

    public function getMac(): string { return $this->mac; }
    public function setMac(string $mac): void { $this->mac = $mac; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
