<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use phpseclib3\Math\BigInteger;

class XdrInflationPayout {

    public XdrAccountID $destination;
    public BigInteger $amount;

    public function __construct(XdrAccountID $destination, BigInteger $amount) {
        $this->destination = $destination;
        $this->amount = $amount;
    }

    public function encode(): string {
        $bytes = $this->destination->encode();
        $bytes .= XdrEncoder::bigInteger64($this->amount);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrInflationPayout {
        $destination = XdrAccountID::decode($xdr);
        $amount = $xdr->readBigInteger64();
        return new XdrInflationPayout($destination, $amount);
    }

    public function getDestination(): XdrAccountID { return $this->destination; }
    public function setDestination(XdrAccountID $destination): void { $this->destination = $destination; }
    public function getAmount(): BigInteger { return $this->amount; }
    public function setAmount(BigInteger $amount): void { $this->amount = $amount; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
