<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrInvokeHostFunctionResultCode {
    public int $value;

    const INVOKE_HOST_FUNCTION_SUCCESS = 0;
    const INVOKE_HOST_FUNCTION_MALFORMED = -1;
    const INVOKE_HOST_FUNCTION_TRAPPED = -2;
    const INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED = -3;
    const INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED = -4;
    const INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE = -5;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function INVOKE_HOST_FUNCTION_SUCCESS(): XdrInvokeHostFunctionResultCode {
        return new XdrInvokeHostFunctionResultCode(XdrInvokeHostFunctionResultCode::INVOKE_HOST_FUNCTION_SUCCESS);
    }

    public static function INVOKE_HOST_FUNCTION_MALFORMED(): XdrInvokeHostFunctionResultCode {
        return new XdrInvokeHostFunctionResultCode(XdrInvokeHostFunctionResultCode::INVOKE_HOST_FUNCTION_MALFORMED);
    }

    public static function INVOKE_HOST_FUNCTION_TRAPPED(): XdrInvokeHostFunctionResultCode {
        return new XdrInvokeHostFunctionResultCode(XdrInvokeHostFunctionResultCode::INVOKE_HOST_FUNCTION_TRAPPED);
    }

    public static function INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED(): XdrInvokeHostFunctionResultCode {
        return new XdrInvokeHostFunctionResultCode(XdrInvokeHostFunctionResultCode::INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED);
    }

    public static function INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED(): XdrInvokeHostFunctionResultCode {
        return new XdrInvokeHostFunctionResultCode(XdrInvokeHostFunctionResultCode::INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED);
    }

    public static function INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE(): XdrInvokeHostFunctionResultCode {
        return new XdrInvokeHostFunctionResultCode(XdrInvokeHostFunctionResultCode::INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrInvokeHostFunctionResultCode {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case -1:
            case -2:
            case -3:
            case -4:
            case -5:
                return new XdrInvokeHostFunctionResultCode($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
