<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use phpseclib3\Math\BigInteger;

class XdrInnerTransactionResult {

    public BigInteger $feeCharged;
    public XdrInnerTransactionResultResult $result;
    public XdrTransactionResultExt $ext;

    public function __construct(BigInteger $feeCharged, XdrInnerTransactionResultResult $result, XdrTransactionResultExt $ext) {
        $this->feeCharged = $feeCharged;
        $this->result = $result;
        $this->ext = $ext;
    }

    public function encode(): string {
        $bytes = XdrEncoder::bigInteger64($this->feeCharged);
        $bytes .= $this->result->encode();
        $bytes .= $this->ext->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrInnerTransactionResult {
        $feeCharged = $xdr->readBigInteger64();
        $result = XdrInnerTransactionResultResult::decode($xdr);
        $ext = XdrTransactionResultExt::decode($xdr);
        return new XdrInnerTransactionResult($feeCharged, $result, $ext);
    }

    public function getFeeCharged(): BigInteger { return $this->feeCharged; }
    public function setFeeCharged(BigInteger $feeCharged): void { $this->feeCharged = $feeCharged; }
    public function getResult(): XdrInnerTransactionResultResult { return $this->result; }
    public function setResult(XdrInnerTransactionResultResult $result): void { $this->result = $result; }
    public function getExt(): XdrTransactionResultExt { return $this->ext; }
    public function setExt(XdrTransactionResultExt $ext): void { $this->ext = $ext; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'fee_charged' => $this->feeCharged->toString(),
            'result' => $this->result->toJsonValue(),
            'ext' => $this->ext->toJsonValue(),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrInnerTransactionResult JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('fee_charged', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field fee_charged for XdrInnerTransactionResult'
            );
        }
        $feeCharged = new BigInteger(is_string($value['fee_charged']) ? $value['fee_charged'] : (string) (int) $value['fee_charged']);
        if (!array_key_exists('result', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field result for XdrInnerTransactionResult'
            );
        }
        $result = XdrInnerTransactionResultResult::fromJsonValue($value['result']);
        if (!array_key_exists('ext', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field ext for XdrInnerTransactionResult'
            );
        }
        $ext = XdrTransactionResultExt::fromJsonValue($value['ext']);
        return new static($feeCharged, $result, $ext);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
