<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrInvokeHostFunctionSuccessPreImage {

    public XdrSCVal $returnValue;
    public array $events;

    public function __construct(XdrSCVal $returnValue, array $events) {
        $this->returnValue = $returnValue;
        $this->events = $events;
    }

    public function encode(): string {
        $bytes = $this->returnValue->encode();
        $eventsCount = count($this->events);
        $bytes .= XdrEncoder::integer32($eventsCount);
        foreach ($this->events as $eventsItem) {
            $bytes .= $eventsItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrInvokeHostFunctionSuccessPreImage {
        $returnValue = XdrSCVal::decode($xdr);
        $events = [];
        $eventsSize = $xdr->readInteger32();
        for ($i = 0; $i < $eventsSize; $i++) {
            $events[] = XdrContractEvent::decode($xdr);
        }
        return new XdrInvokeHostFunctionSuccessPreImage($returnValue, $events);
    }

    public function getReturnValue(): XdrSCVal { return $this->returnValue; }
    public function setReturnValue(XdrSCVal $returnValue): void { $this->returnValue = $returnValue; }
    public function getEvents(): array { return $this->events; }
    public function setEvents(array $events): void { $this->events = $events; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'return_value' => $this->returnValue->toJsonValue(),
            'events' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->events),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrInvokeHostFunctionSuccessPreImage JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('return_value', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field return_value for XdrInvokeHostFunctionSuccessPreImage'
            );
        }
        $returnValue = XdrSCVal::fromJsonValue($value['return_value']);
        if (!array_key_exists('events', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field events for XdrInvokeHostFunctionSuccessPreImage'
            );
        }
        $events = (static function ($v) {
            if (!is_array($v)) {
                throw new \InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrContractEvent::fromJsonValue($item); }
            return $out;
        })($value['events']);
        return new static($returnValue, $events);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
