<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrLedgerBounds {

    public int $minLedger;
    public int $maxLedger;

    public function __construct(int $minLedger, int $maxLedger) {
        $this->minLedger = $minLedger;
        $this->maxLedger = $maxLedger;
    }

    public function encode(): string {
        $bytes = XdrEncoder::unsignedInteger32($this->minLedger);
        $bytes .= XdrEncoder::unsignedInteger32($this->maxLedger);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrLedgerBounds {
        $minLedger = $xdr->readUnsignedInteger32();
        $maxLedger = $xdr->readUnsignedInteger32();
        return new XdrLedgerBounds($minLedger, $maxLedger);
    }

    public function getMinLedger(): int { return $this->minLedger; }
    public function setMinLedger(int $minLedger): void { $this->minLedger = $minLedger; }
    public function getMaxLedger(): int { return $this->maxLedger; }
    public function setMaxLedger(int $maxLedger): void { $this->maxLedger = $maxLedger; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'min_ledger' => $this->minLedger,
            'max_ledger' => $this->maxLedger,
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrLedgerBounds JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('min_ledger', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field min_ledger for XdrLedgerBounds'
            );
        }
        $minLedger = (static function ($v) { if (!is_int($v)) { throw new \InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['min_ledger']);
        if (!array_key_exists('max_ledger', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field max_ledger for XdrLedgerBounds'
            );
        }
        $maxLedger = (static function ($v) { if (!is_int($v)) { throw new \InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['max_ledger']);
        return new static($minLedger, $maxLedger);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix . '.minLedger'] = (string)$this->minLedger;
        $lines[$prefix . '.maxLedger'] = (string)$this->maxLedger;
    }

    public static function fromTxRep(array $map, string $prefix): XdrLedgerBounds {
        $minLedger = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.minLedger') ?? '0');
        $maxLedger = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.maxLedger') ?? '0');
        return new XdrLedgerBounds($minLedger, $maxLedger);
    }
}
