<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrLedgerKeyBase {

    public XdrLedgerEntryType $type;
    public ?XdrLedgerKeyAccount $account = null;
    public ?XdrLedgerKeyTrustLine $trustLine = null;
    public ?XdrLedgerKeyOffer $offer = null;
    public ?XdrLedgerKeyData $data = null;
    public ?XdrClaimableBalanceID $balanceID = null;
    public ?XdrLedgerKeyLiquidityPool $liquidityPool = null;
    public ?XdrLedgerKeyContractData $contractData = null;
    public ?XdrLedgerKeyContractCode $contractCode = null;
    public ?XdrConfigSettingID $configSetting = null;
    public ?XdrLedgerKeyTTL $ttl = null;

    public function __construct(?XdrLedgerEntryType $type = null) {
        if ($type !== null) {
            $this->type = $type;
        }
    }

    public function encode(): string {
        $bytes = $this->type->encode();
        switch ($this->type->getValue()) {
            case XdrLedgerEntryType::ACCOUNT:
                $bytes .= $this->account->encode();
                break;
            case XdrLedgerEntryType::TRUSTLINE:
                $bytes .= $this->trustLine->encode();
                break;
            case XdrLedgerEntryType::OFFER:
                $bytes .= $this->offer->encode();
                break;
            case XdrLedgerEntryType::DATA:
                $bytes .= $this->data->encode();
                break;
            case XdrLedgerEntryType::CLAIMABLE_BALANCE:
                $bytes .= $this->balanceID->encode();
                break;
            case XdrLedgerEntryType::LIQUIDITY_POOL:
                $bytes .= $this->liquidityPool->encode();
                break;
            case XdrLedgerEntryType::CONTRACT_DATA:
                $bytes .= $this->contractData->encode();
                break;
            case XdrLedgerEntryType::CONTRACT_CODE:
                $bytes .= $this->contractCode->encode();
                break;
            case XdrLedgerEntryType::CONFIG_SETTING:
                $bytes .= $this->configSetting->encode();
                break;
            case XdrLedgerEntryType::TTL:
                $bytes .= $this->ttl->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): static {
        $result = new static(XdrLedgerEntryType::decode($xdr));
        switch ($result->type->getValue()) {
            case XdrLedgerEntryType::ACCOUNT:
                $result->account = XdrLedgerKeyAccount::decode($xdr);
                break;
            case XdrLedgerEntryType::TRUSTLINE:
                $result->trustLine = XdrLedgerKeyTrustLine::decode($xdr);
                break;
            case XdrLedgerEntryType::OFFER:
                $result->offer = XdrLedgerKeyOffer::decode($xdr);
                break;
            case XdrLedgerEntryType::DATA:
                $result->data = XdrLedgerKeyData::decode($xdr);
                break;
            case XdrLedgerEntryType::CLAIMABLE_BALANCE:
                $result->balanceID = XdrClaimableBalanceID::decode($xdr);
                break;
            case XdrLedgerEntryType::LIQUIDITY_POOL:
                $result->liquidityPool = XdrLedgerKeyLiquidityPool::decode($xdr);
                break;
            case XdrLedgerEntryType::CONTRACT_DATA:
                $result->contractData = XdrLedgerKeyContractData::decode($xdr);
                break;
            case XdrLedgerEntryType::CONTRACT_CODE:
                $result->contractCode = XdrLedgerKeyContractCode::decode($xdr);
                break;
            case XdrLedgerEntryType::CONFIG_SETTING:
                $result->configSetting = XdrConfigSettingID::decode($xdr);
                break;
            case XdrLedgerEntryType::TTL:
                $result->ttl = XdrLedgerKeyTTL::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getType(): XdrLedgerEntryType { return $this->type; }
    public function setType(XdrLedgerEntryType $type): void { $this->type = $type; }
    public function getAccount(): ?XdrLedgerKeyAccount { return $this->account; }
    public function setAccount(?XdrLedgerKeyAccount $account): void { $this->account = $account; }
    public function getTrustLine(): ?XdrLedgerKeyTrustLine { return $this->trustLine; }
    public function setTrustLine(?XdrLedgerKeyTrustLine $trustLine): void { $this->trustLine = $trustLine; }
    public function getOffer(): ?XdrLedgerKeyOffer { return $this->offer; }
    public function setOffer(?XdrLedgerKeyOffer $offer): void { $this->offer = $offer; }
    public function getData(): ?XdrLedgerKeyData { return $this->data; }
    public function setData(?XdrLedgerKeyData $data): void { $this->data = $data; }
    public function getBalanceID(): ?XdrClaimableBalanceID { return $this->balanceID; }
    public function setBalanceID(?XdrClaimableBalanceID $balanceID): void { $this->balanceID = $balanceID; }
    public function getLiquidityPool(): ?XdrLedgerKeyLiquidityPool { return $this->liquidityPool; }
    public function setLiquidityPool(?XdrLedgerKeyLiquidityPool $liquidityPool): void { $this->liquidityPool = $liquidityPool; }
    public function getContractData(): ?XdrLedgerKeyContractData { return $this->contractData; }
    public function setContractData(?XdrLedgerKeyContractData $contractData): void { $this->contractData = $contractData; }
    public function getContractCode(): ?XdrLedgerKeyContractCode { return $this->contractCode; }
    public function setContractCode(?XdrLedgerKeyContractCode $contractCode): void { $this->contractCode = $contractCode; }
    public function getConfigSetting(): ?XdrConfigSettingID { return $this->configSetting; }
    public function setConfigSetting(?XdrConfigSettingID $configSetting): void { $this->configSetting = $configSetting; }
    public function getTtl(): ?XdrLedgerKeyTTL { return $this->ttl; }
    public function setTtl(?XdrLedgerKeyTTL $ttl): void { $this->ttl = $ttl; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
