<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrLedgerEntryChange {

    public XdrLedgerEntryChangeType $type;
    public ?XdrLedgerEntry $created = null;
    public ?XdrLedgerEntry $updated = null;
    public ?XdrLedgerKey $removed = null;
    public ?XdrLedgerEntry $state = null;
    public ?XdrLedgerEntry $restored = null;

    public function __construct(?XdrLedgerEntryChangeType $type = null) {
        if ($type !== null) {
            $this->type = $type;
        }
    }

    public function encode(): string {
        $bytes = $this->type->encode();
        switch ($this->type->getValue()) {
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_CREATED:
                $bytes .= $this->created->encode();
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_UPDATED:
                $bytes .= $this->updated->encode();
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_REMOVED:
                $bytes .= $this->removed->encode();
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_STATE:
                $bytes .= $this->state->encode();
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_RESTORED:
                $bytes .= $this->restored->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrLedgerEntryChange {
        $result = new XdrLedgerEntryChange(XdrLedgerEntryChangeType::decode($xdr));
        switch ($result->type->getValue()) {
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_CREATED:
                $result->created = XdrLedgerEntry::decode($xdr);
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_UPDATED:
                $result->updated = XdrLedgerEntry::decode($xdr);
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_REMOVED:
                $result->removed = XdrLedgerKey::decode($xdr);
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_STATE:
                $result->state = XdrLedgerEntry::decode($xdr);
                break;
            case XdrLedgerEntryChangeType::LEDGER_ENTRY_RESTORED:
                $result->restored = XdrLedgerEntry::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getType(): XdrLedgerEntryChangeType { return $this->type; }
    public function setType(XdrLedgerEntryChangeType $type): void { $this->type = $type; }
    public function getCreated(): ?XdrLedgerEntry { return $this->created; }
    public function setCreated(?XdrLedgerEntry $created): void { $this->created = $created; }
    public function getUpdated(): ?XdrLedgerEntry { return $this->updated; }
    public function setUpdated(?XdrLedgerEntry $updated): void { $this->updated = $updated; }
    public function getRemoved(): ?XdrLedgerKey { return $this->removed; }
    public function setRemoved(?XdrLedgerKey $removed): void { $this->removed = $removed; }
    public function getState(): ?XdrLedgerEntry { return $this->state; }
    public function setState(?XdrLedgerEntry $state): void { $this->state = $state; }
    public function getRestored(): ?XdrLedgerEntry { return $this->restored; }
    public function setRestored(?XdrLedgerEntry $restored): void { $this->restored = $restored; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
