<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrLiquidityPoolConstantProductParameters {

    public XdrAsset $assetA;
    public XdrAsset $assetB;
    public int $fee;

    public function __construct(XdrAsset $assetA, XdrAsset $assetB, int $fee) {
        $this->assetA = $assetA;
        $this->assetB = $assetB;
        $this->fee = $fee;
    }

    public function encode(): string {
        $bytes = $this->assetA->encode();
        $bytes .= $this->assetB->encode();
        $bytes .= XdrEncoder::integer32($this->fee);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrLiquidityPoolConstantProductParameters {
        $assetA = XdrAsset::decode($xdr);
        $assetB = XdrAsset::decode($xdr);
        $fee = $xdr->readInteger32();
        return new XdrLiquidityPoolConstantProductParameters($assetA, $assetB, $fee);
    }

    public function getAssetA(): XdrAsset { return $this->assetA; }
    public function setAssetA(XdrAsset $assetA): void { $this->assetA = $assetA; }
    public function getAssetB(): XdrAsset { return $this->assetB; }
    public function setAssetB(XdrAsset $assetB): void { $this->assetB = $assetB; }
    public function getFee(): int { return $this->fee; }
    public function setFee(int $fee): void { $this->fee = $fee; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
