<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrManageDataOperationBase {

    public string $dataName;
    public ?string $dataValue = null;

    public function __construct(string $dataName, ?string $dataValue = null) {
        $this->dataName = $dataName;
        $this->dataValue = $dataValue;
    }

    public function encode(): string {
        $bytes = XdrEncoder::string($this->dataName);
        if ($this->dataValue !== null) {
            $bytes .= XdrEncoder::integer32(1);
            $bytes .= XdrEncoder::opaqueVariable($this->dataValue);
        } else {
            $bytes .= XdrEncoder::integer32(0);
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): static {
        $dataName = $xdr->readString();
        $dataValue = null;
        if ($xdr->readInteger32() !== 0) {
            $dataValue = $xdr->readOpaqueVariable();
        }
        return new static($dataName, $dataValue);
    }

    public function getDataName(): string { return $this->dataName; }
    public function setDataName(string $dataName): void { $this->dataName = $dataName; }
    public function getDataValue(): ?string { return $this->dataValue; }
    public function setDataValue(?string $dataValue): void { $this->dataValue = $dataValue; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'data_name' => XdrJsonHelper::escapeString($this->dataName),
            'data_value' => ($this->dataValue !== null ? XdrJsonHelper::bytesToHex($this->dataValue) : null),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrManageDataOperation JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('data_name', $value)) {
            throw new InvalidArgumentException(
                'Missing required field data_name for XdrManageDataOperation'
            );
        }
        if (!array_key_exists('data_value', $value)) {
            throw new InvalidArgumentException(
                'Missing required field data_value for XdrManageDataOperation'
            );
        }
        if (!is_string($value['data_name'])) {
            throw new InvalidArgumentException(
                'Expected string for data_name, got ' . get_debug_type($value['data_name'])
            );
        }
        $dataName = XdrJsonHelper::unescapeString($value['data_name']);
        $rawBytes = null;
        if ($value['data_value'] !== null) {
            if (!is_string($value['data_value'])) {
                throw new InvalidArgumentException(
                    'Expected hex string or null for data_value, got ' . get_debug_type($value['data_value'])
                );
            }
            $rawBytes = XdrJsonHelper::hexToBytes($value['data_value']);
        }
        // Wrapper signature: (string $key, XdrDataValue $value).
        return new static($dataName, new XdrDataValue($rawBytes));
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix . '.dataName'] = TxRepHelper::escapeString($this->dataName);
        if ($this->dataValue !== null) {
            $lines[$prefix . '.dataValue._present'] = 'true';
            $lines[$prefix . '.dataValue'] = TxRepHelper::bytesToHex($this->dataValue);
        } else {
            $lines[$prefix . '.dataValue._present'] = 'false';
        }
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $dataName = TxRepHelper::unescapeString(TxRepHelper::getValue($map, $prefix . '.dataName') ?? '');
        $dataValue = null;
        $dataValuePresent = TxRepHelper::getValue($map, $prefix . '.dataValue._present');
        if ($dataValuePresent !== null && $dataValuePresent === 'true') {
            $dataValue = TxRepHelper::hexToBytes(TxRepHelper::getValue($map, $prefix . '.dataValue') ?? '');
        }
        return new static($dataName, $dataValue);
    }
}
