<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrManageDataResult {

    public XdrManageDataResultCode $code;

    public function __construct(?XdrManageDataResultCode $code = null) {
        if ($code !== null) {
            $this->code = $code;
        }
    }

    public function encode(): string {
        $bytes = $this->code->encode();
        switch ($this->code->getValue()) {
            case XdrManageDataResultCode::SUCCESS:
                break;
            case XdrManageDataResultCode::NOT_SUPPORTED_YET:
            case XdrManageDataResultCode::NAME_NOT_FOUND:
            case XdrManageDataResultCode::LOW_RESERVE:
            case XdrManageDataResultCode::INVALID_NAME:
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrManageDataResult {
        $result = new XdrManageDataResult(XdrManageDataResultCode::decode($xdr));
        switch ($result->code->getValue()) {
            case XdrManageDataResultCode::SUCCESS:
                break;
            case XdrManageDataResultCode::NOT_SUPPORTED_YET:
            case XdrManageDataResultCode::NAME_NOT_FOUND:
            case XdrManageDataResultCode::LOW_RESERVE:
            case XdrManageDataResultCode::INVALID_NAME:
                break;
            default:
                break;
        }
        return $result;
    }

    public function getCode(): XdrManageDataResultCode { return $this->code; }
    public function setCode(XdrManageDataResultCode $code): void { $this->code = $code; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): mixed {
        return match ($this->code->getValue()) {
            XdrManageDataResultCode::SUCCESS => 'success',
            XdrManageDataResultCode::NOT_SUPPORTED_YET => 'not_supported_yet',
            XdrManageDataResultCode::NAME_NOT_FOUND => 'name_not_found',
            XdrManageDataResultCode::LOW_RESERVE => 'low_reserve',
            XdrManageDataResultCode::INVALID_NAME => 'invalid_name',
            // @codeCoverageIgnoreStart
            default => throw new \InvalidArgumentException(
                'Unknown discriminant for code on XdrManageDataResultCode'
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (is_string($value)) {
            return match ($value) {
                'success' => new static(new XdrManageDataResultCode(XdrManageDataResultCode::SUCCESS)),
                'not_supported_yet' => new static(new XdrManageDataResultCode(XdrManageDataResultCode::NOT_SUPPORTED_YET)),
                'name_not_found' => new static(new XdrManageDataResultCode(XdrManageDataResultCode::NAME_NOT_FOUND)),
                'low_reserve' => new static(new XdrManageDataResultCode(XdrManageDataResultCode::LOW_RESERVE)),
                'invalid_name' => new static(new XdrManageDataResultCode(XdrManageDataResultCode::INVALID_NAME)),
                default => throw new \InvalidArgumentException(
                    'Unknown XdrManageDataResult void arm string: ' . XdrJsonHelper::safePreview($value)
                ),
            };
        }
        throw new \InvalidArgumentException(
            'Expected void-arm string for XdrManageDataResult, got ' . get_debug_type($value)
        );
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
