<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrOperationMeta {

    public array $ledgerEntryChanges;

    public function __construct(array $ledgerEntryChanges) {
        $this->ledgerEntryChanges = $ledgerEntryChanges;
    }

    public function encode(): string {
        $ledgerEntryChangesCount = count($this->ledgerEntryChanges);
        $bytes = XdrEncoder::integer32($ledgerEntryChangesCount);
        foreach ($this->ledgerEntryChanges as $ledgerEntryChangesItem) {
            $bytes .= $ledgerEntryChangesItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrOperationMeta {
        $ledgerEntryChanges = [];
        $ledgerEntryChangesSize = $xdr->readInteger32();
        for ($i = 0; $i < $ledgerEntryChangesSize; $i++) {
            $ledgerEntryChanges[] = XdrLedgerEntryChange::decode($xdr);
        }
        return new XdrOperationMeta($ledgerEntryChanges);
    }

    public function getLedgerEntryChanges(): array { return $this->ledgerEntryChanges; }
    public function setLedgerEntryChanges(array $ledgerEntryChanges): void { $this->ledgerEntryChanges = $ledgerEntryChanges; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
