<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use phpseclib3\Math\BigInteger;

class XdrPathPaymentStrictReceiveOperation {

    public XdrAsset $sendAsset;
    public BigInteger $sendMax;
    public XdrMuxedAccount $destination;
    public XdrAsset $destAsset;
    public BigInteger $destAmount;
    public array $path;

    public function __construct(XdrAsset $sendAsset, BigInteger $sendMax, XdrMuxedAccount $destination, XdrAsset $destAsset, BigInteger $destAmount, array $path) {
        $this->sendAsset = $sendAsset;
        $this->sendMax = $sendMax;
        $this->destination = $destination;
        $this->destAsset = $destAsset;
        $this->destAmount = $destAmount;
        $this->path = $path;
    }

    public function encode(): string {
        $bytes = $this->sendAsset->encode();
        $bytes .= XdrEncoder::bigInteger64($this->sendMax);
        $bytes .= $this->destination->encode();
        $bytes .= $this->destAsset->encode();
        $bytes .= XdrEncoder::bigInteger64($this->destAmount);
        $pathCount = count($this->path);
        $bytes .= XdrEncoder::integer32($pathCount);
        foreach ($this->path as $pathItem) {
            $bytes .= $pathItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrPathPaymentStrictReceiveOperation {
        $sendAsset = XdrAsset::decode($xdr);
        $sendMax = $xdr->readBigInteger64();
        $destination = XdrMuxedAccount::decode($xdr);
        $destAsset = XdrAsset::decode($xdr);
        $destAmount = $xdr->readBigInteger64();
        $path = [];
        $pathSize = $xdr->readInteger32();
        for ($i = 0; $i < $pathSize; $i++) {
            $path[] = XdrAsset::decode($xdr);
        }
        return new XdrPathPaymentStrictReceiveOperation($sendAsset, $sendMax, $destination, $destAsset, $destAmount, $path);
    }

    public function getSendAsset(): XdrAsset { return $this->sendAsset; }
    public function setSendAsset(XdrAsset $sendAsset): void { $this->sendAsset = $sendAsset; }
    public function getSendMax(): BigInteger { return $this->sendMax; }
    public function setSendMax(BigInteger $sendMax): void { $this->sendMax = $sendMax; }
    public function getDestination(): XdrMuxedAccount { return $this->destination; }
    public function setDestination(XdrMuxedAccount $destination): void { $this->destination = $destination; }
    public function getDestAsset(): XdrAsset { return $this->destAsset; }
    public function setDestAsset(XdrAsset $destAsset): void { $this->destAsset = $destAsset; }
    public function getDestAmount(): BigInteger { return $this->destAmount; }
    public function setDestAmount(BigInteger $destAmount): void { $this->destAmount = $destAmount; }
    public function getPath(): array { return $this->path; }
    public function setPath(array $path): void { $this->path = $path; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
