<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrPreconditionsV2Base {

    public ?XdrTimeBounds $timeBounds = null;
    public ?XdrLedgerBounds $ledgerBounds = null;
    public ?XdrSequenceNumber $minSeqNum = null;
    public int $minSeqAge;
    public int $minSeqLedgerGap;
    public array $extraSigners;

    public function __construct(int $minSeqAge, int $minSeqLedgerGap, array $extraSigners, ?XdrTimeBounds $timeBounds = null, ?XdrLedgerBounds $ledgerBounds = null, ?XdrSequenceNumber $minSeqNum = null) {
        $this->minSeqAge = $minSeqAge;
        $this->minSeqLedgerGap = $minSeqLedgerGap;
        $this->extraSigners = $extraSigners;
        $this->timeBounds = $timeBounds;
        $this->ledgerBounds = $ledgerBounds;
        $this->minSeqNum = $minSeqNum;
    }

    public function encode(): string {
        if ($this->timeBounds !== null) {
            $bytes = XdrEncoder::integer32(1);
            $bytes .= $this->timeBounds->encode();
        } else {
            $bytes = XdrEncoder::integer32(0);
        }
        if ($this->ledgerBounds !== null) {
            $bytes .= XdrEncoder::integer32(1);
            $bytes .= $this->ledgerBounds->encode();
        } else {
            $bytes .= XdrEncoder::integer32(0);
        }
        if ($this->minSeqNum !== null) {
            $bytes .= XdrEncoder::integer32(1);
            $bytes .= $this->minSeqNum->encode();
        } else {
            $bytes .= XdrEncoder::integer32(0);
        }
        $bytes .= XdrEncoder::unsignedInteger64($this->minSeqAge);
        $bytes .= XdrEncoder::unsignedInteger32($this->minSeqLedgerGap);
        $extraSignersCount = count($this->extraSigners);
        $bytes .= XdrEncoder::integer32($extraSignersCount);
        foreach ($this->extraSigners as $extraSignersItem) {
            $bytes .= $extraSignersItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): static {
        $timeBounds = null;
        if ($xdr->readInteger32() !== 0) {
            $timeBounds = XdrTimeBounds::decode($xdr);
        }
        $ledgerBounds = null;
        if ($xdr->readInteger32() !== 0) {
            $ledgerBounds = XdrLedgerBounds::decode($xdr);
        }
        $minSeqNum = null;
        if ($xdr->readInteger32() !== 0) {
            $minSeqNum = XdrSequenceNumber::decode($xdr);
        }
        $minSeqAge = $xdr->readUnsignedInteger64();
        $minSeqLedgerGap = $xdr->readUnsignedInteger32();
        $extraSigners = [];
        $extraSignersSize = $xdr->readInteger32();
        for ($i = 0; $i < $extraSignersSize; $i++) {
            $extraSigners[] = XdrSignerKey::decode($xdr);
        }
        return new static($minSeqAge, $minSeqLedgerGap, $extraSigners, $timeBounds, $ledgerBounds, $minSeqNum);
    }

    public function getTimeBounds(): ?XdrTimeBounds { return $this->timeBounds; }
    public function setTimeBounds(?XdrTimeBounds $timeBounds): void { $this->timeBounds = $timeBounds; }
    public function getLedgerBounds(): ?XdrLedgerBounds { return $this->ledgerBounds; }
    public function setLedgerBounds(?XdrLedgerBounds $ledgerBounds): void { $this->ledgerBounds = $ledgerBounds; }
    public function getMinSeqNum(): ?XdrSequenceNumber { return $this->minSeqNum; }
    public function setMinSeqNum(?XdrSequenceNumber $minSeqNum): void { $this->minSeqNum = $minSeqNum; }
    public function getMinSeqAge(): int { return $this->minSeqAge; }
    public function setMinSeqAge(int $minSeqAge): void { $this->minSeqAge = $minSeqAge; }
    public function getMinSeqLedgerGap(): int { return $this->minSeqLedgerGap; }
    public function setMinSeqLedgerGap(int $minSeqLedgerGap): void { $this->minSeqLedgerGap = $minSeqLedgerGap; }
    public function getExtraSigners(): array { return $this->extraSigners; }
    public function setExtraSigners(array $extraSigners): void { $this->extraSigners = $extraSigners; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
