<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrParallelTxsComponent {

    public ?int $baseFee = null;
    public array $executionStages;

    public function __construct(array $executionStages, ?int $baseFee = null) {
        $this->executionStages = $executionStages;
        $this->baseFee = $baseFee;
    }

    public function encode(): string {
        if ($this->baseFee !== null) {
            $bytes = XdrEncoder::integer32(1);
            $bytes .= XdrEncoder::integer64($this->baseFee);
        } else {
            $bytes = XdrEncoder::integer32(0);
        }
        $executionStagesCount = count($this->executionStages);
        $bytes .= XdrEncoder::integer32($executionStagesCount);
        foreach ($this->executionStages as $executionStagesItem) {
            $bytes .= $executionStagesItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrParallelTxsComponent {
        $baseFee = null;
        if ($xdr->readInteger32() !== 0) {
            $baseFee = $xdr->readInteger64();
        }
        $executionStages = [];
        $executionStagesSize = $xdr->readInteger32();
        for ($i = 0; $i < $executionStagesSize; $i++) {
            $executionStages[] = XdrParallelTxExecutionStage::decode($xdr);
        }
        return new XdrParallelTxsComponent($executionStages, $baseFee);
    }

    public function getBaseFee(): ?int { return $this->baseFee; }
    public function setBaseFee(?int $baseFee): void { $this->baseFee = $baseFee; }
    public function getExecutionStages(): array { return $this->executionStages; }
    public function setExecutionStages(array $executionStages): void { $this->executionStages = $executionStages; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'base_fee' => ($this->baseFee !== null ? XdrJsonHelper::int64ToString($this->baseFee) : null),
            'execution_stages' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->executionStages),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrParallelTxsComponent JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('base_fee', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field base_fee for XdrParallelTxsComponent'
            );
        }
        $baseFee = null;
        if ($value['base_fee'] !== null) {
            $baseFee = (static function ($v) { if (!is_string($v) && !is_int($v)) { throw new \InvalidArgumentException('Expected int64 JSON value (string or int), got ' . get_debug_type($v)); } return XdrJsonHelper::stringToInt64($v); })($value['base_fee']);
        }
        if (!array_key_exists('execution_stages', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field execution_stages for XdrParallelTxsComponent'
            );
        }
        $executionStages = (static function ($v) {
            if (!is_array($v)) {
                throw new \InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrParallelTxExecutionStage::fromJsonValue($item); }
            return $out;
        })($value['execution_stages']);
        return new static($executionStages, $baseFee);
    }

    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
