<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrPathPaymentStrictReceiveResult {

    public XdrPathPaymentStrictReceiveResultCode $code;
    public ?XdrPathPaymentResultSuccess $success = null;
    public ?XdrAsset $noIssuer = null;

    public function __construct(?XdrPathPaymentStrictReceiveResultCode $code = null) {
        if ($code !== null) {
            $this->code = $code;
        }
    }

    public function encode(): string {
        $bytes = $this->code->encode();
        switch ($this->code->getValue()) {
            case XdrPathPaymentStrictReceiveResultCode::SUCCESS:
                $bytes .= $this->success->encode();
                break;
            case XdrPathPaymentStrictReceiveResultCode::MALFORMED:
            case XdrPathPaymentStrictReceiveResultCode::UNDERFUNDED:
            case XdrPathPaymentStrictReceiveResultCode::SRC_NO_TRUST:
            case XdrPathPaymentStrictReceiveResultCode::SRC_NOT_AUTHORIZED:
            case XdrPathPaymentStrictReceiveResultCode::NO_DESTINATION:
            case XdrPathPaymentStrictReceiveResultCode::NO_TRUST:
            case XdrPathPaymentStrictReceiveResultCode::NOT_AUTHORIZED:
            case XdrPathPaymentStrictReceiveResultCode::LINE_FULL:
                break;
            case XdrPathPaymentStrictReceiveResultCode::NO_ISSUER:
                $bytes .= $this->noIssuer->encode();
                break;
            case XdrPathPaymentStrictReceiveResultCode::TOO_FEW_OFFERS:
            case XdrPathPaymentStrictReceiveResultCode::OFFER_CROSS_SELF:
            case XdrPathPaymentStrictReceiveResultCode::OVER_SENDMAX:
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrPathPaymentStrictReceiveResult {
        $result = new XdrPathPaymentStrictReceiveResult(XdrPathPaymentStrictReceiveResultCode::decode($xdr));
        switch ($result->code->getValue()) {
            case XdrPathPaymentStrictReceiveResultCode::SUCCESS:
                $result->success = XdrPathPaymentResultSuccess::decode($xdr);
                break;
            case XdrPathPaymentStrictReceiveResultCode::MALFORMED:
            case XdrPathPaymentStrictReceiveResultCode::UNDERFUNDED:
            case XdrPathPaymentStrictReceiveResultCode::SRC_NO_TRUST:
            case XdrPathPaymentStrictReceiveResultCode::SRC_NOT_AUTHORIZED:
            case XdrPathPaymentStrictReceiveResultCode::NO_DESTINATION:
            case XdrPathPaymentStrictReceiveResultCode::NO_TRUST:
            case XdrPathPaymentStrictReceiveResultCode::NOT_AUTHORIZED:
            case XdrPathPaymentStrictReceiveResultCode::LINE_FULL:
                break;
            case XdrPathPaymentStrictReceiveResultCode::NO_ISSUER:
                $result->noIssuer = XdrAsset::decode($xdr);
                break;
            case XdrPathPaymentStrictReceiveResultCode::TOO_FEW_OFFERS:
            case XdrPathPaymentStrictReceiveResultCode::OFFER_CROSS_SELF:
            case XdrPathPaymentStrictReceiveResultCode::OVER_SENDMAX:
                break;
            default:
                break;
        }
        return $result;
    }

    public function getCode(): XdrPathPaymentStrictReceiveResultCode { return $this->code; }
    public function setCode(XdrPathPaymentStrictReceiveResultCode $code): void { $this->code = $code; }
    public function getSuccess(): ?XdrPathPaymentResultSuccess { return $this->success; }
    public function setSuccess(?XdrPathPaymentResultSuccess $success): void { $this->success = $success; }
    public function getNoIssuer(): ?XdrAsset { return $this->noIssuer; }
    public function setNoIssuer(?XdrAsset $noIssuer): void { $this->noIssuer = $noIssuer; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): mixed {
        return match ($this->code->getValue()) {
            XdrPathPaymentStrictReceiveResultCode::SUCCESS => ['success' => $this->success->toJsonValue()],
            XdrPathPaymentStrictReceiveResultCode::MALFORMED => 'malformed',
            XdrPathPaymentStrictReceiveResultCode::UNDERFUNDED => 'underfunded',
            XdrPathPaymentStrictReceiveResultCode::SRC_NO_TRUST => 'src_no_trust',
            XdrPathPaymentStrictReceiveResultCode::SRC_NOT_AUTHORIZED => 'src_not_authorized',
            XdrPathPaymentStrictReceiveResultCode::NO_DESTINATION => 'no_destination',
            XdrPathPaymentStrictReceiveResultCode::NO_TRUST => 'no_trust',
            XdrPathPaymentStrictReceiveResultCode::NOT_AUTHORIZED => 'not_authorized',
            XdrPathPaymentStrictReceiveResultCode::LINE_FULL => 'line_full',
            XdrPathPaymentStrictReceiveResultCode::NO_ISSUER => ['no_issuer' => $this->noIssuer->toJsonValue()],
            XdrPathPaymentStrictReceiveResultCode::TOO_FEW_OFFERS => 'too_few_offers',
            XdrPathPaymentStrictReceiveResultCode::OFFER_CROSS_SELF => 'offer_cross_self',
            XdrPathPaymentStrictReceiveResultCode::OVER_SENDMAX => 'over_sendmax',
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown discriminant for code on XdrPathPaymentStrictReceiveResultCode'
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (is_string($value)) {
            return match ($value) {
                'malformed' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::MALFORMED)),
                'underfunded' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::UNDERFUNDED)),
                'src_no_trust' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::SRC_NO_TRUST)),
                'src_not_authorized' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::SRC_NOT_AUTHORIZED)),
                'no_destination' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::NO_DESTINATION)),
                'no_trust' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::NO_TRUST)),
                'not_authorized' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::NOT_AUTHORIZED)),
                'line_full' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::LINE_FULL)),
                'too_few_offers' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::TOO_FEW_OFFERS)),
                'offer_cross_self' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::OFFER_CROSS_SELF)),
                'over_sendmax' => new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::OVER_SENDMAX)),
                'success' => throw new InvalidArgumentException(
                    "Arm 'success' on XdrPathPaymentStrictReceiveResult is non-void; supply a single-key object {\"success\": <payload>} instead of a bare string."
                ),
                'no_issuer' => throw new InvalidArgumentException(
                    "Arm 'no_issuer' on XdrPathPaymentStrictReceiveResult is non-void; supply a single-key object {\"no_issuer\": <payload>} instead of a bare string."
                ),
                default => throw new InvalidArgumentException(
                    'Unknown XdrPathPaymentStrictReceiveResult void arm string: ' . XdrJsonHelper::safePreview($value)
                ),
            };
        }
        if (!is_array($value) || count($value) !== 1) {
            throw new InvalidArgumentException(
                'Expected single-key object or void-arm string for XdrPathPaymentStrictReceiveResult, got ' . get_debug_type($value)
            );
        }
        $key = array_key_first($value);
        if (!is_string($key)) {
            throw new InvalidArgumentException(
                'Expected string arm key for XdrPathPaymentStrictReceiveResult, got ' . get_debug_type($key)
            );
        }
        $arm = $value[$key];
        return match ($key) {
            'success' => (static function () use ($arm) { $r = new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::SUCCESS)); $r->success = XdrPathPaymentResultSuccess::fromJsonValue($arm); return $r; })(),
            'no_issuer' => (static function () use ($arm) { $r = new static(new XdrPathPaymentStrictReceiveResultCode(XdrPathPaymentStrictReceiveResultCode::NO_ISSUER)); $r->noIssuer = XdrAsset::fromJsonValue($arm); return $r; })(),
            default => throw new InvalidArgumentException(
                'Unknown arm key for XdrPathPaymentStrictReceiveResult: ' . XdrJsonHelper::safePreview($key)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
