<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use phpseclib3\Math\BigInteger;

class XdrPathPaymentStrictSendOperation {

    public XdrAsset $sendAsset;
    public BigInteger $sendAmount;
    public XdrMuxedAccount $destination;
    public XdrAsset $destAsset;
    public BigInteger $destMin;
    public array $path;

    public function __construct(XdrAsset $sendAsset, BigInteger $sendAmount, XdrMuxedAccount $destination, XdrAsset $destAsset, BigInteger $destMin, array $path) {
        $this->sendAsset = $sendAsset;
        $this->sendAmount = $sendAmount;
        $this->destination = $destination;
        $this->destAsset = $destAsset;
        $this->destMin = $destMin;
        $this->path = $path;
    }

    public function encode(): string {
        $bytes = $this->sendAsset->encode();
        $bytes .= XdrEncoder::bigInteger64($this->sendAmount);
        $bytes .= $this->destination->encode();
        $bytes .= $this->destAsset->encode();
        $bytes .= XdrEncoder::bigInteger64($this->destMin);
        $pathCount = count($this->path);
        $bytes .= XdrEncoder::integer32($pathCount);
        foreach ($this->path as $pathItem) {
            $bytes .= $pathItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrPathPaymentStrictSendOperation {
        $sendAsset = XdrAsset::decode($xdr);
        $sendAmount = $xdr->readBigInteger64();
        $destination = XdrMuxedAccount::decode($xdr);
        $destAsset = XdrAsset::decode($xdr);
        $destMin = $xdr->readBigInteger64();
        $path = [];
        $pathSize = $xdr->readInteger32();
        for ($i = 0; $i < $pathSize; $i++) {
            $path[] = XdrAsset::decode($xdr);
        }
        return new XdrPathPaymentStrictSendOperation($sendAsset, $sendAmount, $destination, $destAsset, $destMin, $path);
    }

    public function getSendAsset(): XdrAsset { return $this->sendAsset; }
    public function setSendAsset(XdrAsset $sendAsset): void { $this->sendAsset = $sendAsset; }
    public function getSendAmount(): BigInteger { return $this->sendAmount; }
    public function setSendAmount(BigInteger $sendAmount): void { $this->sendAmount = $sendAmount; }
    public function getDestination(): XdrMuxedAccount { return $this->destination; }
    public function setDestination(XdrMuxedAccount $destination): void { $this->destination = $destination; }
    public function getDestAsset(): XdrAsset { return $this->destAsset; }
    public function setDestAsset(XdrAsset $destAsset): void { $this->destAsset = $destAsset; }
    public function getDestMin(): BigInteger { return $this->destMin; }
    public function setDestMin(BigInteger $destMin): void { $this->destMin = $destMin; }
    public function getPath(): array { return $this->path; }
    public function setPath(array $path): void { $this->path = $path; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix . '.sendAsset'] = TxRepHelper::formatAsset($this->sendAsset);
        $lines[$prefix . '.sendAmount'] = $this->sendAmount->toString();
        $lines[$prefix . '.destination'] = TxRepHelper::formatMuxedAccount($this->destination);
        $lines[$prefix . '.destAsset'] = TxRepHelper::formatAsset($this->destAsset);
        $lines[$prefix . '.destMin'] = $this->destMin->toString();
        $lines[$prefix . '.path.len'] = (string)count($this->path);
        for ($i = 0; $i < count($this->path); $i++) {
            $lines[$prefix . '.path[' . $i . ']'] = TxRepHelper::formatAsset($this->path[$i]);
        }
    }

    public static function fromTxRep(array $map, string $prefix): XdrPathPaymentStrictSendOperation {
        $sendAsset = TxRepHelper::parseAsset(TxRepHelper::getValue($map, $prefix . '.sendAsset') ?? '');
        $sendAmount = TxRepHelper::parseBigInt(TxRepHelper::getValue($map, $prefix . '.sendAmount') ?? '0');
        $destination = TxRepHelper::parseMuxedAccount(TxRepHelper::getValue($map, $prefix . '.destination') ?? '');
        $destAsset = TxRepHelper::parseAsset(TxRepHelper::getValue($map, $prefix . '.destAsset') ?? '');
        $destMin = TxRepHelper::parseBigInt(TxRepHelper::getValue($map, $prefix . '.destMin') ?? '0');
        $pathLen = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.path.len') ?? '0');
        $path = [];
        for ($i = 0; $i < $pathLen; $i++) {
            $path[] = TxRepHelper::parseAsset(TxRepHelper::getValue($map, $prefix . '.path[' . $i . ']') ?? '');
        }
        return new XdrPathPaymentStrictSendOperation($sendAsset, $sendAmount, $destination, $destAsset, $destMin, $path);
    }
}
