<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrRevokeSponsorshipSigner {

    public XdrAccountID $accountId;
    public XdrSignerKey $signerKey;

    public function __construct(XdrAccountID $accountId, XdrSignerKey $signerKey) {
        $this->accountId = $accountId;
        $this->signerKey = $signerKey;
    }

    public function encode(): string {
        $bytes = $this->accountId->encode();
        $bytes .= $this->signerKey->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrRevokeSponsorshipSigner {
        $accountId = XdrAccountID::decode($xdr);
        $signerKey = XdrSignerKey::decode($xdr);
        return new XdrRevokeSponsorshipSigner($accountId, $signerKey);
    }

    public function getAccountId(): XdrAccountID { return $this->accountId; }
    public function setAccountId(XdrAccountID $accountId): void { $this->accountId = $accountId; }
    public function getSignerKey(): XdrSignerKey { return $this->signerKey; }
    public function setSignerKey(XdrSignerKey $signerKey): void { $this->signerKey = $signerKey; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'account_id' => $this->accountId->toJsonValue(),
            'signer_key' => $this->signerKey->toJsonValue(),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrRevokeSponsorshipSigner JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('account_id', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field account_id for XdrRevokeSponsorshipSigner'
            );
        }
        $accountId = XdrAccountID::fromJsonValue($value['account_id']);
        if (!array_key_exists('signer_key', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field signer_key for XdrRevokeSponsorshipSigner'
            );
        }
        $signerKey = XdrSignerKey::fromJsonValue($value['signer_key']);
        return new static($accountId, $signerKey);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix . '.accountID'] = TxRepHelper::formatAccountId($this->accountId);
        $lines[$prefix . '.signerKey'] = TxRepHelper::formatSignerKey($this->signerKey);
    }

    public static function fromTxRep(array $map, string $prefix): XdrRevokeSponsorshipSigner {
        $accountId = TxRepHelper::parseAccountId(TxRepHelper::getValue($map, $prefix . '.accountID') ?? '');
        $signerKey = TxRepHelper::parseSignerKey(TxRepHelper::getValue($map, $prefix . '.signerKey') ?? '');
        return new XdrRevokeSponsorshipSigner($accountId, $signerKey);
    }
}
