<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrRestoreFootprintOp {

    public XdrExtensionPoint $ext;

    public function __construct(XdrExtensionPoint $ext) {
        $this->ext = $ext;
    }

    public function encode(): string {
        $bytes = $this->ext->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrRestoreFootprintOp {
        $ext = XdrExtensionPoint::decode($xdr);
        return new XdrRestoreFootprintOp($ext);
    }

    public function getExt(): XdrExtensionPoint { return $this->ext; }
    public function setExt(XdrExtensionPoint $ext): void { $this->ext = $ext; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
