<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrRevokeSponsorshipResultCode {
    public int $value;

    const SUCCESS = 0;
    const DOES_NOT_EXIST = -1;
    const NOT_SPONSOR = -2;
    const LOW_RESERVE = -3;
    const ONLY_TRANSFERABLE = -4;
    const MALFORMED = -5;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SUCCESS(): XdrRevokeSponsorshipResultCode {
        return new XdrRevokeSponsorshipResultCode(XdrRevokeSponsorshipResultCode::SUCCESS);
    }

    public static function DOES_NOT_EXIST(): XdrRevokeSponsorshipResultCode {
        return new XdrRevokeSponsorshipResultCode(XdrRevokeSponsorshipResultCode::DOES_NOT_EXIST);
    }

    public static function NOT_SPONSOR(): XdrRevokeSponsorshipResultCode {
        return new XdrRevokeSponsorshipResultCode(XdrRevokeSponsorshipResultCode::NOT_SPONSOR);
    }

    public static function LOW_RESERVE(): XdrRevokeSponsorshipResultCode {
        return new XdrRevokeSponsorshipResultCode(XdrRevokeSponsorshipResultCode::LOW_RESERVE);
    }

    public static function ONLY_TRANSFERABLE(): XdrRevokeSponsorshipResultCode {
        return new XdrRevokeSponsorshipResultCode(XdrRevokeSponsorshipResultCode::ONLY_TRANSFERABLE);
    }

    public static function MALFORMED(): XdrRevokeSponsorshipResultCode {
        return new XdrRevokeSponsorshipResultCode(XdrRevokeSponsorshipResultCode::MALFORMED);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrRevokeSponsorshipResultCode {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case -1:
            case -2:
            case -3:
            case -4:
            case -5:
                return new XdrRevokeSponsorshipResultCode($value);
            default:
                throw new InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::SUCCESS => 'success',
            self::DOES_NOT_EXIST => 'does_not_exist',
            self::NOT_SPONSOR => 'not_sponsor',
            self::LOW_RESERVE => 'low_reserve',
            self::ONLY_TRANSFERABLE => 'only_transferable',
            self::MALFORMED => 'malformed',
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown XdrRevokeSponsorshipResultCode enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new InvalidArgumentException(
                'Expected string for XdrRevokeSponsorshipResultCode JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'success' => new static(self::SUCCESS),
            'does_not_exist' => new static(self::DOES_NOT_EXIST),
            'not_sponsor' => new static(self::NOT_SPONSOR),
            'low_reserve' => new static(self::LOW_RESERVE),
            'only_transferable' => new static(self::ONLY_TRANSFERABLE),
            'malformed' => new static(self::MALFORMED),
            default => throw new InvalidArgumentException(
                'Unknown XdrRevokeSponsorshipResultCode JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
