<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSerializedBinaryFuseFilter {

    public XdrBinaryFuseFilterType $type;
    public XdrShortHashSeed $inputHashSeed;
    public XdrShortHashSeed $filterSeed;
    public int $segmentLength;
    public int $segementLengthMask;
    public int $segmentCount;
    public int $segmentCountLength;
    public int $fingerprintLength;
    public string $fingerprints;

    public function __construct(XdrBinaryFuseFilterType $type, XdrShortHashSeed $inputHashSeed, XdrShortHashSeed $filterSeed, int $segmentLength, int $segementLengthMask, int $segmentCount, int $segmentCountLength, int $fingerprintLength, string $fingerprints) {
        $this->type = $type;
        $this->inputHashSeed = $inputHashSeed;
        $this->filterSeed = $filterSeed;
        $this->segmentLength = $segmentLength;
        $this->segementLengthMask = $segementLengthMask;
        $this->segmentCount = $segmentCount;
        $this->segmentCountLength = $segmentCountLength;
        $this->fingerprintLength = $fingerprintLength;
        $this->fingerprints = $fingerprints;
    }

    public function encode(): string {
        $bytes = $this->type->encode();
        $bytes .= $this->inputHashSeed->encode();
        $bytes .= $this->filterSeed->encode();
        $bytes .= XdrEncoder::unsignedInteger32($this->segmentLength);
        $bytes .= XdrEncoder::unsignedInteger32($this->segementLengthMask);
        $bytes .= XdrEncoder::unsignedInteger32($this->segmentCount);
        $bytes .= XdrEncoder::unsignedInteger32($this->segmentCountLength);
        $bytes .= XdrEncoder::unsignedInteger32($this->fingerprintLength);
        $bytes .= XdrEncoder::opaqueVariable($this->fingerprints);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSerializedBinaryFuseFilter {
        $type = XdrBinaryFuseFilterType::decode($xdr);
        $inputHashSeed = XdrShortHashSeed::decode($xdr);
        $filterSeed = XdrShortHashSeed::decode($xdr);
        $segmentLength = $xdr->readUnsignedInteger32();
        $segementLengthMask = $xdr->readUnsignedInteger32();
        $segmentCount = $xdr->readUnsignedInteger32();
        $segmentCountLength = $xdr->readUnsignedInteger32();
        $fingerprintLength = $xdr->readUnsignedInteger32();
        $fingerprints = $xdr->readOpaqueVariable();
        return new XdrSerializedBinaryFuseFilter($type, $inputHashSeed, $filterSeed, $segmentLength, $segementLengthMask, $segmentCount, $segmentCountLength, $fingerprintLength, $fingerprints);
    }

    public function getType(): XdrBinaryFuseFilterType { return $this->type; }
    public function setType(XdrBinaryFuseFilterType $type): void { $this->type = $type; }
    public function getInputHashSeed(): XdrShortHashSeed { return $this->inputHashSeed; }
    public function setInputHashSeed(XdrShortHashSeed $inputHashSeed): void { $this->inputHashSeed = $inputHashSeed; }
    public function getFilterSeed(): XdrShortHashSeed { return $this->filterSeed; }
    public function setFilterSeed(XdrShortHashSeed $filterSeed): void { $this->filterSeed = $filterSeed; }
    public function getSegmentLength(): int { return $this->segmentLength; }
    public function setSegmentLength(int $segmentLength): void { $this->segmentLength = $segmentLength; }
    public function getSegementLengthMask(): int { return $this->segementLengthMask; }
    public function setSegementLengthMask(int $segementLengthMask): void { $this->segementLengthMask = $segementLengthMask; }
    public function getSegmentCount(): int { return $this->segmentCount; }
    public function setSegmentCount(int $segmentCount): void { $this->segmentCount = $segmentCount; }
    public function getSegmentCountLength(): int { return $this->segmentCountLength; }
    public function setSegmentCountLength(int $segmentCountLength): void { $this->segmentCountLength = $segmentCountLength; }
    public function getFingerprintLength(): int { return $this->fingerprintLength; }
    public function setFingerprintLength(int $fingerprintLength): void { $this->fingerprintLength = $fingerprintLength; }
    public function getFingerprints(): string { return $this->fingerprints; }
    public function setFingerprints(string $fingerprints): void { $this->fingerprints = $fingerprints; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
