<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCPNomination {

    public string $quorumSetHash;
    public array $votes;
    public array $accepted;

    public function __construct(string $quorumSetHash, array $votes, array $accepted) {
        $this->quorumSetHash = $quorumSetHash;
        $this->votes = $votes;
        $this->accepted = $accepted;
    }

    public function encode(): string {
        $bytes = XdrEncoder::opaqueFixed($this->quorumSetHash, 32);
        $votesCount = count($this->votes);
        $bytes .= XdrEncoder::integer32($votesCount);
        foreach ($this->votes as $votesItem) {
            $bytes .= $votesItem->encode();
        }
        $acceptedCount = count($this->accepted);
        $bytes .= XdrEncoder::integer32($acceptedCount);
        foreach ($this->accepted as $acceptedItem) {
            $bytes .= $acceptedItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCPNomination {
        $quorumSetHash = $xdr->readOpaqueFixed(32);
        $votes = [];
        $votesSize = $xdr->readInteger32();
        for ($i = 0; $i < $votesSize; $i++) {
            $votes[] = XdrValue::decode($xdr);
        }
        $accepted = [];
        $acceptedSize = $xdr->readInteger32();
        for ($i = 0; $i < $acceptedSize; $i++) {
            $accepted[] = XdrValue::decode($xdr);
        }
        return new XdrSCPNomination($quorumSetHash, $votes, $accepted);
    }

    public function getQuorumSetHash(): string { return $this->quorumSetHash; }
    public function setQuorumSetHash(string $quorumSetHash): void { $this->quorumSetHash = $quorumSetHash; }
    public function getVotes(): array { return $this->votes; }
    public function setVotes(array $votes): void { $this->votes = $votes; }
    public function getAccepted(): array { return $this->accepted; }
    public function setAccepted(array $accepted): void { $this->accepted = $accepted; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
