<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSurveyMessageResponseType {
    public int $value;

    const SURVEY_TOPOLOGY_RESPONSE_V2 = 2;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SURVEY_TOPOLOGY_RESPONSE_V2(): XdrSurveyMessageResponseType {
        return new XdrSurveyMessageResponseType(XdrSurveyMessageResponseType::SURVEY_TOPOLOGY_RESPONSE_V2);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSurveyMessageResponseType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 2:
                return new XdrSurveyMessageResponseType($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::SURVEY_TOPOLOGY_RESPONSE_V2 => 'survey_topology_response_v2',
            // @codeCoverageIgnoreStart
            default => throw new \InvalidArgumentException(
                'Unknown XdrSurveyMessageResponseType enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new \InvalidArgumentException(
                'Expected string for XdrSurveyMessageResponseType JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'survey_topology_response_v2' => new static(self::SURVEY_TOPOLOGY_RESPONSE_V2),
            default => throw new \InvalidArgumentException(
                'Unknown XdrSurveyMessageResponseType JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
