<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrSCEnvMetaEntryInterfaceVersion {

    public int $protocol;
    public int $preRelease;

    public function __construct(int $protocol, int $preRelease) {
        $this->protocol = $protocol;
        $this->preRelease = $preRelease;
    }

    public function encode(): string {
        $bytes = XdrEncoder::unsignedInteger32($this->protocol);
        $bytes .= XdrEncoder::unsignedInteger32($this->preRelease);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCEnvMetaEntryInterfaceVersion {
        $protocol = $xdr->readUnsignedInteger32();
        $preRelease = $xdr->readUnsignedInteger32();
        return new XdrSCEnvMetaEntryInterfaceVersion($protocol, $preRelease);
    }

    public function getProtocol(): int { return $this->protocol; }
    public function setProtocol(int $protocol): void { $this->protocol = $protocol; }
    public function getPreRelease(): int { return $this->preRelease; }
    public function setPreRelease(int $preRelease): void { $this->preRelease = $preRelease; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'protocol' => $this->protocol,
            'pre_release' => $this->preRelease,
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrSCEnvMetaEntryInterfaceVersion JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('protocol', $value)) {
            throw new InvalidArgumentException(
                'Missing required field protocol for XdrSCEnvMetaEntryInterfaceVersion'
            );
        }
        $protocol = (static function ($v) { if (!is_int($v)) { throw new InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['protocol']);
        if (!array_key_exists('pre_release', $value)) {
            throw new InvalidArgumentException(
                'Missing required field pre_release for XdrSCEnvMetaEntryInterfaceVersion'
            );
        }
        $preRelease = (static function ($v) { if (!is_int($v)) { throw new InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['pre_release']);
        return new static($protocol, $preRelease);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
