<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCSpecTypeUDT {

    public string $name;

    public function __construct(string $name) {
        $this->name = $name;
    }

    public function encode(): string {
        $bytes = XdrEncoder::string($this->name);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCSpecTypeUDT {
        $name = $xdr->readString();
        return new XdrSCSpecTypeUDT($name);
    }

    public function getName(): string { return $this->name; }
    public function setName(string $name): void { $this->name = $name; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
