<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCPStatementConfirm {

    public XdrSCPBallot $ballot;
    public int $nPrepared;
    public int $nCommit;
    public int $nH;
    public string $quorumSetHash;

    public function __construct(XdrSCPBallot $ballot, int $nPrepared, int $nCommit, int $nH, string $quorumSetHash) {
        $this->ballot = $ballot;
        $this->nPrepared = $nPrepared;
        $this->nCommit = $nCommit;
        $this->nH = $nH;
        $this->quorumSetHash = $quorumSetHash;
    }

    public function encode(): string {
        $bytes = $this->ballot->encode();
        $bytes .= XdrEncoder::unsignedInteger32($this->nPrepared);
        $bytes .= XdrEncoder::unsignedInteger32($this->nCommit);
        $bytes .= XdrEncoder::unsignedInteger32($this->nH);
        $bytes .= XdrEncoder::opaqueFixed($this->quorumSetHash, 32);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCPStatementConfirm {
        $ballot = XdrSCPBallot::decode($xdr);
        $nPrepared = $xdr->readUnsignedInteger32();
        $nCommit = $xdr->readUnsignedInteger32();
        $nH = $xdr->readUnsignedInteger32();
        $quorumSetHash = $xdr->readOpaqueFixed(32);
        return new XdrSCPStatementConfirm($ballot, $nPrepared, $nCommit, $nH, $quorumSetHash);
    }

    public function getBallot(): XdrSCPBallot { return $this->ballot; }
    public function setBallot(XdrSCPBallot $ballot): void { $this->ballot = $ballot; }
    public function getNPrepared(): int { return $this->nPrepared; }
    public function setNPrepared(int $nPrepared): void { $this->nPrepared = $nPrepared; }
    public function getNCommit(): int { return $this->nCommit; }
    public function setNCommit(int $nCommit): void { $this->nCommit = $nCommit; }
    public function getNH(): int { return $this->nH; }
    public function setNH(int $nH): void { $this->nH = $nH; }
    public function getQuorumSetHash(): string { return $this->quorumSetHash; }
    public function setQuorumSetHash(string $quorumSetHash): void { $this->quorumSetHash = $quorumSetHash; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'ballot' => $this->ballot->toJsonValue(),
            'n_prepared' => $this->nPrepared,
            'n_commit' => $this->nCommit,
            'n_h' => $this->nH,
            'quorum_set_hash' => XdrJsonHelper::bytesToHex($this->quorumSetHash),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrSCPStatementConfirm JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('ballot', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field ballot for XdrSCPStatementConfirm'
            );
        }
        $ballot = XdrSCPBallot::fromJsonValue($value['ballot']);
        if (!array_key_exists('n_prepared', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field n_prepared for XdrSCPStatementConfirm'
            );
        }
        $nPrepared = (static function ($v) { if (!is_int($v)) { throw new \InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['n_prepared']);
        if (!array_key_exists('n_commit', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field n_commit for XdrSCPStatementConfirm'
            );
        }
        $nCommit = (static function ($v) { if (!is_int($v)) { throw new \InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['n_commit']);
        if (!array_key_exists('n_h', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field n_h for XdrSCPStatementConfirm'
            );
        }
        $nH = (static function ($v) { if (!is_int($v)) { throw new \InvalidArgumentException('Expected int JSON value, got ' . get_debug_type($v)); } return $v; })($value['n_h']);
        if (!array_key_exists('quorum_set_hash', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field quorum_set_hash for XdrSCPStatementConfirm'
            );
        }
        $quorumSetHash = (static function ($v) { if (!is_string($v)) { throw new \InvalidArgumentException('Expected hex string JSON value, got ' . get_debug_type($v)); } return XdrJsonHelper::hexToBytes($v); })($value['quorum_set_hash']);
        return new static($ballot, $nPrepared, $nCommit, $nH, $quorumSetHash);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
