<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrSorobanTransactionData {

    public XdrSorobanTransactionDataExt $ext;
    public XdrSorobanResources $resources;
    public int $resourceFee;

    public function __construct(XdrSorobanTransactionDataExt $ext, XdrSorobanResources $resources, int $resourceFee) {
        $this->ext = $ext;
        $this->resources = $resources;
        $this->resourceFee = $resourceFee;
    }

    public function encode(): string {
        $bytes = $this->ext->encode();
        $bytes .= $this->resources->encode();
        $bytes .= XdrEncoder::integer64($this->resourceFee);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSorobanTransactionData {
        $ext = XdrSorobanTransactionDataExt::decode($xdr);
        $resources = XdrSorobanResources::decode($xdr);
        $resourceFee = $xdr->readInteger64();
        return new XdrSorobanTransactionData($ext, $resources, $resourceFee);
    }

    public function getExt(): XdrSorobanTransactionDataExt { return $this->ext; }
    public function setExt(XdrSorobanTransactionDataExt $ext): void { $this->ext = $ext; }
    public function getResources(): XdrSorobanResources { return $this->resources; }
    public function setResources(XdrSorobanResources $resources): void { $this->resources = $resources; }
    public function getResourceFee(): int { return $this->resourceFee; }
    public function setResourceFee(int $resourceFee): void { $this->resourceFee = $resourceFee; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'ext' => $this->ext->toJsonValue(),
            'resources' => $this->resources->toJsonValue(),
            'resource_fee' => XdrJsonHelper::int64ToString($this->resourceFee),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrSorobanTransactionData JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('ext', $value)) {
            throw new InvalidArgumentException(
                'Missing required field ext for XdrSorobanTransactionData'
            );
        }
        $ext = XdrSorobanTransactionDataExt::fromJsonValue($value['ext']);
        if (!array_key_exists('resources', $value)) {
            throw new InvalidArgumentException(
                'Missing required field resources for XdrSorobanTransactionData'
            );
        }
        $resources = XdrSorobanResources::fromJsonValue($value['resources']);
        if (!array_key_exists('resource_fee', $value)) {
            throw new InvalidArgumentException(
                'Missing required field resource_fee for XdrSorobanTransactionData'
            );
        }
        $resourceFee = (static function ($v) { if (!is_string($v) && !is_int($v)) { throw new InvalidArgumentException('Expected int64 JSON value (string or int), got ' . get_debug_type($v)); } return XdrJsonHelper::stringToInt64($v); })($value['resource_fee']);
        return new static($ext, $resources, $resourceFee);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $this->ext->toTxRep($prefix . '.ext', $lines);
        $this->resources->toTxRep($prefix . '.resources', $lines);
        $lines[$prefix . '.resourceFee'] = (string)$this->resourceFee;
    }

    public static function fromTxRep(array $map, string $prefix): XdrSorobanTransactionData {
        $ext = XdrSorobanTransactionDataExt::fromTxRep($map, $prefix . '.ext');
        $resources = XdrSorobanResources::fromTxRep($map, $prefix . '.resources');
        $resourceFee = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.resourceFee') ?? '0');
        return new XdrSorobanTransactionData($ext, $resources, $resourceFee);
    }
}
