<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSetTrustLineFlagsResultCode {
    public int $value;

    const SUCCESS = 0;
    const MALFORMED = -1;
    const NO_TRUST_LINE = -2;
    const CANT_REVOKE = -3;
    const INVALID_STATE = -4;
    const LOW_RESERVE = -5;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SUCCESS(): XdrSetTrustLineFlagsResultCode {
        return new XdrSetTrustLineFlagsResultCode(XdrSetTrustLineFlagsResultCode::SUCCESS);
    }

    public static function MALFORMED(): XdrSetTrustLineFlagsResultCode {
        return new XdrSetTrustLineFlagsResultCode(XdrSetTrustLineFlagsResultCode::MALFORMED);
    }

    public static function NO_TRUST_LINE(): XdrSetTrustLineFlagsResultCode {
        return new XdrSetTrustLineFlagsResultCode(XdrSetTrustLineFlagsResultCode::NO_TRUST_LINE);
    }

    public static function CANT_REVOKE(): XdrSetTrustLineFlagsResultCode {
        return new XdrSetTrustLineFlagsResultCode(XdrSetTrustLineFlagsResultCode::CANT_REVOKE);
    }

    public static function INVALID_STATE(): XdrSetTrustLineFlagsResultCode {
        return new XdrSetTrustLineFlagsResultCode(XdrSetTrustLineFlagsResultCode::INVALID_STATE);
    }

    public static function LOW_RESERVE(): XdrSetTrustLineFlagsResultCode {
        return new XdrSetTrustLineFlagsResultCode(XdrSetTrustLineFlagsResultCode::LOW_RESERVE);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSetTrustLineFlagsResultCode {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case -1:
            case -2:
            case -3:
            case -4:
            case -5:
                return new XdrSetTrustLineFlagsResultCode($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::SUCCESS => 'success',
            self::MALFORMED => 'malformed',
            self::NO_TRUST_LINE => 'no_trust_line',
            self::CANT_REVOKE => 'cant_revoke',
            self::INVALID_STATE => 'invalid_state',
            self::LOW_RESERVE => 'low_reserve',
            // @codeCoverageIgnoreStart
            default => throw new \InvalidArgumentException(
                'Unknown XdrSetTrustLineFlagsResultCode enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new \InvalidArgumentException(
                'Expected string for XdrSetTrustLineFlagsResultCode JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'success' => new static(self::SUCCESS),
            'malformed' => new static(self::MALFORMED),
            'no_trust_line' => new static(self::NO_TRUST_LINE),
            'cant_revoke' => new static(self::CANT_REVOKE),
            'invalid_state' => new static(self::INVALID_STATE),
            'low_reserve' => new static(self::LOW_RESERVE),
            default => throw new \InvalidArgumentException(
                'Unknown XdrSetTrustLineFlagsResultCode JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
