<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSorobanAuthorizedFunctionType {
    public int $value;

    const SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN = 0;
    const SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN = 1;
    const SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN = 2;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN(): XdrSorobanAuthorizedFunctionType {
        return new XdrSorobanAuthorizedFunctionType(XdrSorobanAuthorizedFunctionType::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN);
    }

    public static function SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN(): XdrSorobanAuthorizedFunctionType {
        return new XdrSorobanAuthorizedFunctionType(XdrSorobanAuthorizedFunctionType::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN);
    }

    public static function SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN(): XdrSorobanAuthorizedFunctionType {
        return new XdrSorobanAuthorizedFunctionType(XdrSorobanAuthorizedFunctionType::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSorobanAuthorizedFunctionType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
                return new XdrSorobanAuthorizedFunctionType($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function enumName(): string {
        switch ($this->value) {
            case self::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
                return 'SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN';
            case self::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
                return 'SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN';
            case self::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN:
                return 'SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN';
            default:
                return 'XdrSorobanAuthorizedFunctionType#' . $this->value;
        }
    }

    public static function fromTxRepName(string $name): static {
        switch ($name) {
            case 'SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN':
                return new static(self::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN);
            case 'SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN':
                return new static(self::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN);
            case 'SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN':
                return new static(self::SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN);
            default:
                $prefix = 'XdrSorobanAuthorizedFunctionType#';
                if (str_starts_with($name, $prefix)) {
                    $val = (int) substr($name, strlen($prefix));
                    return new static($val);
                }
                throw new \InvalidArgumentException('Unknown enum value: ' . $name);
        }
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix] = $this->enumName();
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $raw = TxRepHelper::getValue($map, $prefix);
        if ($raw === null) {
            throw new \InvalidArgumentException('Missing TxRep value for: ' . $prefix);
        }
        return self::fromTxRepName($raw);
    }
}
