<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCSpecEventParamLocationV0 {
    public int $value;

    const SC_SPEC_EVENT_PARAM_LOCATION_DATA = 0;
    const SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST = 1;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SC_SPEC_EVENT_PARAM_LOCATION_DATA(): XdrSCSpecEventParamLocationV0 {
        return new XdrSCSpecEventParamLocationV0(XdrSCSpecEventParamLocationV0::SC_SPEC_EVENT_PARAM_LOCATION_DATA);
    }

    public static function SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST(): XdrSCSpecEventParamLocationV0 {
        return new XdrSCSpecEventParamLocationV0(XdrSCSpecEventParamLocationV0::SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSCSpecEventParamLocationV0 {
        $value = $xdr->readInteger32();
        return new XdrSCSpecEventParamLocationV0($value);
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
