<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCPStatementType {
    public int $value;

    const SCP_ST_PREPARE = 0;
    const SCP_ST_CONFIRM = 1;
    const SCP_ST_EXTERNALIZE = 2;
    const SCP_ST_NOMINATE = 3;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SCP_ST_PREPARE(): XdrSCPStatementType {
        return new XdrSCPStatementType(XdrSCPStatementType::SCP_ST_PREPARE);
    }

    public static function SCP_ST_CONFIRM(): XdrSCPStatementType {
        return new XdrSCPStatementType(XdrSCPStatementType::SCP_ST_CONFIRM);
    }

    public static function SCP_ST_EXTERNALIZE(): XdrSCPStatementType {
        return new XdrSCPStatementType(XdrSCPStatementType::SCP_ST_EXTERNALIZE);
    }

    public static function SCP_ST_NOMINATE(): XdrSCPStatementType {
        return new XdrSCPStatementType(XdrSCPStatementType::SCP_ST_NOMINATE);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSCPStatementType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
                return new XdrSCPStatementType($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
