<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCSpecTypeTuple {

    public array $valueTypes;

    public function __construct(array $valueTypes) {
        $this->valueTypes = $valueTypes;
    }

    public function encode(): string {
        $valueTypesCount = count($this->valueTypes);
        $bytes = XdrEncoder::integer32($valueTypesCount);
        foreach ($this->valueTypes as $valueTypesItem) {
            $bytes .= $valueTypesItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCSpecTypeTuple {
        $valueTypes = [];
        $valueTypesSize = $xdr->readInteger32();
        for ($i = 0; $i < $valueTypesSize; $i++) {
            $valueTypes[] = XdrSCSpecTypeDef::decode($xdr);
        }
        return new XdrSCSpecTypeTuple($valueTypes);
    }

    public function getValueTypes(): array { return $this->valueTypes; }
    public function setValueTypes(array $valueTypes): void { $this->valueTypes = $valueTypes; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'value_types' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->valueTypes),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrSCSpecTypeTuple JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('value_types', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field value_types for XdrSCSpecTypeTuple'
            );
        }
        $valueTypes = (static function ($v) {
            if (!is_array($v)) {
                throw new \InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrSCSpecTypeDef::fromJsonValue($item); }
            return $out;
        })($value['value_types']);
        return new static($valueTypes);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
