<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSignerKeyTypeBase {
    public int $value;

    const SIGNER_KEY_TYPE_ED25519 = 0;
    const SIGNER_KEY_TYPE_PRE_AUTH_TX = 1;
    const SIGNER_KEY_TYPE_HASH_X = 2;
    const SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD = 3;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SIGNER_KEY_TYPE_ED25519(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_ED25519);
    }

    public static function SIGNER_KEY_TYPE_PRE_AUTH_TX(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_PRE_AUTH_TX);
    }

    public static function SIGNER_KEY_TYPE_HASH_X(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_HASH_X);
    }

    public static function SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): static {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 256:
                return new static($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::SIGNER_KEY_TYPE_ED25519 => 'ed25519',
            self::SIGNER_KEY_TYPE_PRE_AUTH_TX => 'pre_auth_tx',
            self::SIGNER_KEY_TYPE_HASH_X => 'hash_x',
            self::SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD => 'ed25519_signed_payload',
            XdrSignerKeyType::MUXED_ED25519 => 'muxed_ed25519',
            // @codeCoverageIgnoreStart
            default => throw new \InvalidArgumentException(
                'Unknown XdrSignerKeyType enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new \InvalidArgumentException(
                'Expected string for XdrSignerKeyType JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'ed25519' => new static(self::SIGNER_KEY_TYPE_ED25519),
            'pre_auth_tx' => new static(self::SIGNER_KEY_TYPE_PRE_AUTH_TX),
            'hash_x' => new static(self::SIGNER_KEY_TYPE_HASH_X),
            'ed25519_signed_payload' => new static(self::SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD),
            'muxed_ed25519' => new static(XdrSignerKeyType::MUXED_ED25519),
            default => throw new \InvalidArgumentException(
                'Unknown XdrSignerKeyType JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }

    public function enumName(): string {
        switch ($this->value) {
            case self::SIGNER_KEY_TYPE_ED25519:
                return 'SIGNER_KEY_TYPE_ED25519';
            case self::SIGNER_KEY_TYPE_PRE_AUTH_TX:
                return 'SIGNER_KEY_TYPE_PRE_AUTH_TX';
            case self::SIGNER_KEY_TYPE_HASH_X:
                return 'SIGNER_KEY_TYPE_HASH_X';
            case self::SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD:
                return 'SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD';
            default:
                return 'XdrSignerKeyTypeBase#' . $this->value;
        }
    }

    public static function fromTxRepName(string $name): static {
        switch ($name) {
            case 'SIGNER_KEY_TYPE_ED25519':
                return new static(self::SIGNER_KEY_TYPE_ED25519);
            case 'SIGNER_KEY_TYPE_PRE_AUTH_TX':
                return new static(self::SIGNER_KEY_TYPE_PRE_AUTH_TX);
            case 'SIGNER_KEY_TYPE_HASH_X':
                return new static(self::SIGNER_KEY_TYPE_HASH_X);
            case 'SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD':
                return new static(self::SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD);
            default:
                $prefix = 'XdrSignerKeyTypeBase#';
                if (str_starts_with($name, $prefix)) {
                    $val = (int) substr($name, strlen($prefix));
                    return new static($val);
                }
                throw new \InvalidArgumentException('Unknown enum value: ' . $name);
        }
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix] = $this->enumName();
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $raw = TxRepHelper::getValue($map, $prefix);
        if ($raw === null) {
            throw new \InvalidArgumentException('Missing TxRep value for: ' . $prefix);
        }
        return self::fromTxRepName($raw);
    }
}
