<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrSCSpecType {
    public int $value;

    const SC_SPEC_TYPE_VAL = 0;
    const SC_SPEC_TYPE_BOOL = 1;
    const SC_SPEC_TYPE_VOID = 2;
    const SC_SPEC_TYPE_ERROR = 3;
    const SC_SPEC_TYPE_U32 = 4;
    const SC_SPEC_TYPE_I32 = 5;
    const SC_SPEC_TYPE_U64 = 6;
    const SC_SPEC_TYPE_I64 = 7;
    const SC_SPEC_TYPE_TIMEPOINT = 8;
    const SC_SPEC_TYPE_DURATION = 9;
    const SC_SPEC_TYPE_U128 = 10;
    const SC_SPEC_TYPE_I128 = 11;
    const SC_SPEC_TYPE_U256 = 12;
    const SC_SPEC_TYPE_I256 = 13;
    const SC_SPEC_TYPE_BYTES = 14;
    const SC_SPEC_TYPE_STRING = 16;
    const SC_SPEC_TYPE_SYMBOL = 17;
    const SC_SPEC_TYPE_ADDRESS = 19;
    const SC_SPEC_TYPE_MUXED_ADDRESS = 20;
    const SC_SPEC_TYPE_OPTION = 1000;
    const SC_SPEC_TYPE_RESULT = 1001;
    const SC_SPEC_TYPE_VEC = 1002;
    const SC_SPEC_TYPE_MAP = 1004;
    const SC_SPEC_TYPE_TUPLE = 1005;
    const SC_SPEC_TYPE_BYTES_N = 1006;
    const SC_SPEC_TYPE_UDT = 2000;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function VAL(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_VAL);
    }

    public static function BOOL(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_BOOL);
    }

    public static function VOID(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_VOID);
    }

    public static function ERROR(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_ERROR);
    }

    public static function U32(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_U32);
    }

    public static function I32(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_I32);
    }

    public static function U64(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_U64);
    }

    public static function I64(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_I64);
    }

    public static function TIMEPOINT(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_TIMEPOINT);
    }

    public static function DURATION(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_DURATION);
    }

    public static function U128(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_U128);
    }

    public static function I128(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_I128);
    }

    public static function U256(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_U256);
    }

    public static function I256(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_I256);
    }

    public static function BYTES(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_BYTES);
    }

    public static function STRING(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_STRING);
    }

    public static function SYMBOL(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_SYMBOL);
    }

    public static function ADDRESS(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_ADDRESS);
    }

    public static function MUXED_ADDRESS(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_MUXED_ADDRESS);
    }

    public static function OPTION(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_OPTION);
    }

    public static function RESULT(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_RESULT);
    }

    public static function VEC(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_VEC);
    }

    public static function MAP(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_MAP);
    }

    public static function TUPLE(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_TUPLE);
    }

    public static function BYTES_N(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_BYTES_N);
    }

    public static function UDT(): XdrSCSpecType {
        return new XdrSCSpecType(XdrSCSpecType::SC_SPEC_TYPE_UDT);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSCSpecType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
            case 9:
            case 10:
            case 11:
            case 12:
            case 13:
            case 14:
            case 16:
            case 17:
            case 19:
            case 20:
            case 1000:
            case 1001:
            case 1002:
            case 1004:
            case 1005:
            case 1006:
            case 2000:
                return new XdrSCSpecType($value);
            default:
                throw new InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::SC_SPEC_TYPE_VAL => 'val',
            self::SC_SPEC_TYPE_BOOL => 'bool',
            self::SC_SPEC_TYPE_VOID => 'void',
            self::SC_SPEC_TYPE_ERROR => 'error',
            self::SC_SPEC_TYPE_U32 => 'u32',
            self::SC_SPEC_TYPE_I32 => 'i32',
            self::SC_SPEC_TYPE_U64 => 'u64',
            self::SC_SPEC_TYPE_I64 => 'i64',
            self::SC_SPEC_TYPE_TIMEPOINT => 'timepoint',
            self::SC_SPEC_TYPE_DURATION => 'duration',
            self::SC_SPEC_TYPE_U128 => 'u128',
            self::SC_SPEC_TYPE_I128 => 'i128',
            self::SC_SPEC_TYPE_U256 => 'u256',
            self::SC_SPEC_TYPE_I256 => 'i256',
            self::SC_SPEC_TYPE_BYTES => 'bytes',
            self::SC_SPEC_TYPE_STRING => 'string',
            self::SC_SPEC_TYPE_SYMBOL => 'symbol',
            self::SC_SPEC_TYPE_ADDRESS => 'address',
            self::SC_SPEC_TYPE_MUXED_ADDRESS => 'muxed_address',
            self::SC_SPEC_TYPE_OPTION => 'option',
            self::SC_SPEC_TYPE_RESULT => 'result',
            self::SC_SPEC_TYPE_VEC => 'vec',
            self::SC_SPEC_TYPE_MAP => 'map',
            self::SC_SPEC_TYPE_TUPLE => 'tuple',
            self::SC_SPEC_TYPE_BYTES_N => 'bytes_n',
            self::SC_SPEC_TYPE_UDT => 'udt',
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown XdrSCSpecType enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new InvalidArgumentException(
                'Expected string for XdrSCSpecType JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'val' => new static(self::SC_SPEC_TYPE_VAL),
            'bool' => new static(self::SC_SPEC_TYPE_BOOL),
            'void' => new static(self::SC_SPEC_TYPE_VOID),
            'error' => new static(self::SC_SPEC_TYPE_ERROR),
            'u32' => new static(self::SC_SPEC_TYPE_U32),
            'i32' => new static(self::SC_SPEC_TYPE_I32),
            'u64' => new static(self::SC_SPEC_TYPE_U64),
            'i64' => new static(self::SC_SPEC_TYPE_I64),
            'timepoint' => new static(self::SC_SPEC_TYPE_TIMEPOINT),
            'duration' => new static(self::SC_SPEC_TYPE_DURATION),
            'u128' => new static(self::SC_SPEC_TYPE_U128),
            'i128' => new static(self::SC_SPEC_TYPE_I128),
            'u256' => new static(self::SC_SPEC_TYPE_U256),
            'i256' => new static(self::SC_SPEC_TYPE_I256),
            'bytes' => new static(self::SC_SPEC_TYPE_BYTES),
            'string' => new static(self::SC_SPEC_TYPE_STRING),
            'symbol' => new static(self::SC_SPEC_TYPE_SYMBOL),
            'address' => new static(self::SC_SPEC_TYPE_ADDRESS),
            'muxed_address' => new static(self::SC_SPEC_TYPE_MUXED_ADDRESS),
            'option' => new static(self::SC_SPEC_TYPE_OPTION),
            'result' => new static(self::SC_SPEC_TYPE_RESULT),
            'vec' => new static(self::SC_SPEC_TYPE_VEC),
            'map' => new static(self::SC_SPEC_TYPE_MAP),
            'tuple' => new static(self::SC_SPEC_TYPE_TUPLE),
            'bytes_n' => new static(self::SC_SPEC_TYPE_BYTES_N),
            'udt' => new static(self::SC_SPEC_TYPE_UDT),
            default => throw new InvalidArgumentException(
                'Unknown XdrSCSpecType JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
