<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCContractInstance {

    public XdrContractExecutable $executable;
    public ?array $storage = null;

    public function __construct(XdrContractExecutable $executable, ?array $storage = null) {
        $this->executable = $executable;
        $this->storage = $storage;
    }

    public function encode(): string {
        $bytes = $this->executable->encode();
        if ($this->storage !== null) {
            $bytes .= XdrEncoder::integer32(1);
            $storageCount = count($this->storage);
            $bytes .= XdrEncoder::integer32($storageCount);
            foreach ($this->storage as $storageItem) {
                $bytes .= $storageItem->encode();
            }
        } else {
            $bytes .= XdrEncoder::integer32(0);
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCContractInstance {
        $executable = XdrContractExecutable::decode($xdr);
        $storage = null;
        if ($xdr->readInteger32() !== 0) {
            $storage = [];
            $storageSize = $xdr->readInteger32();
            for ($i = 0; $i < $storageSize; $i++) {
                $storage[] = XdrSCMapEntry::decode($xdr);
            }
        }
        return new XdrSCContractInstance($executable, $storage);
    }

    public function getExecutable(): XdrContractExecutable { return $this->executable; }
    public function setExecutable(XdrContractExecutable $executable): void { $this->executable = $executable; }
    public function getStorage(): ?array { return $this->storage; }
    public function setStorage(?array $storage): void { $this->storage = $storage; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
