<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSorobanCredentialsType {
    public int $value;

    const SOROBAN_CREDENTIALS_SOURCE_ACCOUNT = 0;
    const SOROBAN_CREDENTIALS_ADDRESS = 1;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SOROBAN_CREDENTIALS_SOURCE_ACCOUNT(): XdrSorobanCredentialsType {
        return new XdrSorobanCredentialsType(XdrSorobanCredentialsType::SOROBAN_CREDENTIALS_SOURCE_ACCOUNT);
    }

    public static function SOROBAN_CREDENTIALS_ADDRESS(): XdrSorobanCredentialsType {
        return new XdrSorobanCredentialsType(XdrSorobanCredentialsType::SOROBAN_CREDENTIALS_ADDRESS);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSorobanCredentialsType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
                return new XdrSorobanCredentialsType($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function enumName(): string {
        switch ($this->value) {
            case self::SOROBAN_CREDENTIALS_SOURCE_ACCOUNT:
                return 'SOROBAN_CREDENTIALS_SOURCE_ACCOUNT';
            case self::SOROBAN_CREDENTIALS_ADDRESS:
                return 'SOROBAN_CREDENTIALS_ADDRESS';
            default:
                return 'XdrSorobanCredentialsType#' . $this->value;
        }
    }

    public static function fromTxRepName(string $name): static {
        switch ($name) {
            case 'SOROBAN_CREDENTIALS_SOURCE_ACCOUNT':
                return new static(self::SOROBAN_CREDENTIALS_SOURCE_ACCOUNT);
            case 'SOROBAN_CREDENTIALS_ADDRESS':
                return new static(self::SOROBAN_CREDENTIALS_ADDRESS);
            default:
                $prefix = 'XdrSorobanCredentialsType#';
                if (str_starts_with($name, $prefix)) {
                    $val = (int) substr($name, strlen($prefix));
                    return new static($val);
                }
                throw new \InvalidArgumentException('Unknown enum value: ' . $name);
        }
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix] = $this->enumName();
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $raw = TxRepHelper::getValue($map, $prefix);
        if ($raw === null) {
            throw new \InvalidArgumentException('Missing TxRep value for: ' . $prefix);
        }
        return self::fromTxRepName($raw);
    }
}
