<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSignedTimeSlicedSurveyRequestMessage {

    public string $requestSignature;
    public XdrTimeSlicedSurveyRequestMessage $request;

    public function __construct(string $requestSignature, XdrTimeSlicedSurveyRequestMessage $request) {
        $this->requestSignature = $requestSignature;
        $this->request = $request;
    }

    public function encode(): string {
        $bytes = XdrEncoder::opaqueVariable($this->requestSignature);
        $bytes .= $this->request->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSignedTimeSlicedSurveyRequestMessage {
        $requestSignature = $xdr->readOpaqueVariable();
        $request = XdrTimeSlicedSurveyRequestMessage::decode($xdr);
        return new XdrSignedTimeSlicedSurveyRequestMessage($requestSignature, $request);
    }

    public function getRequestSignature(): string { return $this->requestSignature; }
    public function setRequestSignature(string $requestSignature): void { $this->requestSignature = $requestSignature; }
    public function getRequest(): XdrTimeSlicedSurveyRequestMessage { return $this->request; }
    public function setRequest(XdrTimeSlicedSurveyRequestMessage $request): void { $this->request = $request; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'request_signature' => XdrJsonHelper::bytesToHex($this->requestSignature),
            'request' => $this->request->toJsonValue(),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrSignedTimeSlicedSurveyRequestMessage JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('request_signature', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field request_signature for XdrSignedTimeSlicedSurveyRequestMessage'
            );
        }
        $requestSignature = (static function ($v) { if (!is_string($v)) { throw new \InvalidArgumentException('Expected hex string JSON value, got ' . get_debug_type($v)); } return XdrJsonHelper::hexToBytes($v); })($value['request_signature']);
        if (!array_key_exists('request', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field request for XdrSignedTimeSlicedSurveyRequestMessage'
            );
        }
        $request = XdrTimeSlicedSurveyRequestMessage::fromJsonValue($value['request']);
        return new static($requestSignature, $request);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
