<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrStellarValueSignedMsValue {

    public int $closeTimeMs;
    public XdrLedgerCloseValueSignature $lcValueSignature;

    public function __construct(int $closeTimeMs, XdrLedgerCloseValueSignature $lcValueSignature) {
        $this->closeTimeMs = $closeTimeMs;
        $this->lcValueSignature = $lcValueSignature;
    }

    public function encode(): string {
        $bytes = XdrEncoder::unsignedInteger64($this->closeTimeMs);
        $bytes .= $this->lcValueSignature->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrStellarValueSignedMsValue {
        $closeTimeMs = $xdr->readUnsignedInteger64();
        $lcValueSignature = XdrLedgerCloseValueSignature::decode($xdr);
        return new XdrStellarValueSignedMsValue($closeTimeMs, $lcValueSignature);
    }

    public function getCloseTimeMs(): int { return $this->closeTimeMs; }
    public function setCloseTimeMs(int $closeTimeMs): void { $this->closeTimeMs = $closeTimeMs; }
    public function getLcValueSignature(): XdrLedgerCloseValueSignature { return $this->lcValueSignature; }
    public function setLcValueSignature(XdrLedgerCloseValueSignature $lcValueSignature): void { $this->lcValueSignature = $lcValueSignature; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'close_time_ms' => XdrJsonHelper::uint64ToString($this->closeTimeMs),
            'lc_value_signature' => $this->lcValueSignature->toJsonValue(),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrStellarValueSignedMsValue JSON value, got ' . get_debug_type($value)
            );
        }
        XdrJsonHelper::rejectUnknownFields($value, ['close_time_ms', 'lc_value_signature'], 'XdrStellarValueSignedMsValue');
        if (!array_key_exists('close_time_ms', $value)) {
            throw new InvalidArgumentException(
                'Missing required field close_time_ms for XdrStellarValueSignedMsValue'
            );
        }
        $closeTimeMs = (static function ($v) { if (!is_string($v) && !is_int($v)) { throw new InvalidArgumentException('Expected uint64 JSON value (string or int), got ' . get_debug_type($v)); } return XdrJsonHelper::stringToUint64($v); })($value['close_time_ms']);
        if (!array_key_exists('lc_value_signature', $value)) {
            throw new InvalidArgumentException(
                'Missing required field lc_value_signature for XdrStellarValueSignedMsValue'
            );
        }
        $lcValueSignature = XdrLedgerCloseValueSignature::fromJsonValue($value['lc_value_signature']);
        return new static($closeTimeMs, $lcValueSignature);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If an object in $json repeats a key, or if
     *         the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(XdrJsonHelper::decodeText($json));
    }
}
