<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSignerKeyTypeBase {
    public int $value;

    const SIGNER_KEY_TYPE_ED25519 = 0;
    const SIGNER_KEY_TYPE_PRE_AUTH_TX = 1;
    const SIGNER_KEY_TYPE_HASH_X = 2;
    const SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD = 3;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SIGNER_KEY_TYPE_ED25519(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_ED25519);
    }

    public static function SIGNER_KEY_TYPE_PRE_AUTH_TX(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_PRE_AUTH_TX);
    }

    public static function SIGNER_KEY_TYPE_HASH_X(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_HASH_X);
    }

    public static function SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD(): static {
        return new static(XdrSignerKeyTypeBase::SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): static {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
                return new static($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
