<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCNonceKey {

    public int $nonce;

    public function __construct(int $nonce) {
        $this->nonce = $nonce;
    }

    public function encode(): string {
        $bytes = XdrEncoder::integer64($this->nonce);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCNonceKey {
        $nonce = $xdr->readInteger64();
        return new XdrSCNonceKey($nonce);
    }

    public function getNonce(): int { return $this->nonce; }
    public function setNonce(int $nonce): void { $this->nonce = $nonce; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix . '.nonce'] = (string)$this->nonce;
    }

    public static function fromTxRep(array $map, string $prefix): XdrSCNonceKey {
        $nonce = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.nonce') ?? '0');
        return new XdrSCNonceKey($nonce);
    }
}
