<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrSCSpecTypeVec {

    public XdrSCSpecTypeDef $elementType;

    public function __construct(XdrSCSpecTypeDef $elementType) {
        $this->elementType = $elementType;
    }

    public function encode(): string {
        $bytes = $this->elementType->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSCSpecTypeVec {
        $elementType = XdrSCSpecTypeDef::decode($xdr);
        return new XdrSCSpecTypeVec($elementType);
    }

    public function getElementType(): XdrSCSpecTypeDef { return $this->elementType; }
    public function setElementType(XdrSCSpecTypeDef $elementType): void { $this->elementType = $elementType; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'element_type' => $this->elementType->toJsonValue(),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrSCSpecTypeVec JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('element_type', $value)) {
            throw new InvalidArgumentException(
                'Missing required field element_type for XdrSCSpecTypeVec'
            );
        }
        $elementType = XdrSCSpecTypeDef::fromJsonValue($value['element_type']);
        return new static($elementType);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
