<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSigner {

    public XdrSignerKey $key;
    public int $weight;

    public function __construct(XdrSignerKey $key, int $weight) {
        $this->key = $key;
        $this->weight = $weight;
    }

    public function encode(): string {
        $bytes = $this->key->encode();
        $bytes .= XdrEncoder::unsignedInteger32($this->weight);
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrSigner {
        $key = XdrSignerKey::decode($xdr);
        $weight = $xdr->readUnsignedInteger32();
        return new XdrSigner($key, $weight);
    }

    public function getKey(): XdrSignerKey { return $this->key; }
    public function setKey(XdrSignerKey $key): void { $this->key = $key; }
    public function getWeight(): int { return $this->weight; }
    public function setWeight(int $weight): void { $this->weight = $weight; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
