<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrSCAddressType {
    public int $value;

    const SC_ADDRESS_TYPE_ACCOUNT = 0;
    const SC_ADDRESS_TYPE_CONTRACT = 1;
    const SC_ADDRESS_TYPE_MUXED_ACCOUNT = 2;
    const SC_ADDRESS_TYPE_CLAIMABLE_BALANCE = 3;
    const SC_ADDRESS_TYPE_LIQUIDITY_POOL = 4;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function SC_ADDRESS_TYPE_ACCOUNT(): XdrSCAddressType {
        return new XdrSCAddressType(XdrSCAddressType::SC_ADDRESS_TYPE_ACCOUNT);
    }

    public static function SC_ADDRESS_TYPE_CONTRACT(): XdrSCAddressType {
        return new XdrSCAddressType(XdrSCAddressType::SC_ADDRESS_TYPE_CONTRACT);
    }

    public static function SC_ADDRESS_TYPE_MUXED_ACCOUNT(): XdrSCAddressType {
        return new XdrSCAddressType(XdrSCAddressType::SC_ADDRESS_TYPE_MUXED_ACCOUNT);
    }

    public static function SC_ADDRESS_TYPE_CLAIMABLE_BALANCE(): XdrSCAddressType {
        return new XdrSCAddressType(XdrSCAddressType::SC_ADDRESS_TYPE_CLAIMABLE_BALANCE);
    }

    public static function SC_ADDRESS_TYPE_LIQUIDITY_POOL(): XdrSCAddressType {
        return new XdrSCAddressType(XdrSCAddressType::SC_ADDRESS_TYPE_LIQUIDITY_POOL);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrSCAddressType {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
                return new XdrSCAddressType($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function enumName(): string {
        switch ($this->value) {
            case self::SC_ADDRESS_TYPE_ACCOUNT:
                return 'SC_ADDRESS_TYPE_ACCOUNT';
            case self::SC_ADDRESS_TYPE_CONTRACT:
                return 'SC_ADDRESS_TYPE_CONTRACT';
            case self::SC_ADDRESS_TYPE_MUXED_ACCOUNT:
                return 'SC_ADDRESS_TYPE_MUXED_ACCOUNT';
            case self::SC_ADDRESS_TYPE_CLAIMABLE_BALANCE:
                return 'SC_ADDRESS_TYPE_CLAIMABLE_BALANCE';
            case self::SC_ADDRESS_TYPE_LIQUIDITY_POOL:
                return 'SC_ADDRESS_TYPE_LIQUIDITY_POOL';
            default:
                return 'XdrSCAddressType#' . $this->value;
        }
    }

    public static function fromTxRepName(string $name): static {
        switch ($name) {
            case 'SC_ADDRESS_TYPE_ACCOUNT':
                return new static(self::SC_ADDRESS_TYPE_ACCOUNT);
            case 'SC_ADDRESS_TYPE_CONTRACT':
                return new static(self::SC_ADDRESS_TYPE_CONTRACT);
            case 'SC_ADDRESS_TYPE_MUXED_ACCOUNT':
                return new static(self::SC_ADDRESS_TYPE_MUXED_ACCOUNT);
            case 'SC_ADDRESS_TYPE_CLAIMABLE_BALANCE':
                return new static(self::SC_ADDRESS_TYPE_CLAIMABLE_BALANCE);
            case 'SC_ADDRESS_TYPE_LIQUIDITY_POOL':
                return new static(self::SC_ADDRESS_TYPE_LIQUIDITY_POOL);
            default:
                $prefix = 'XdrSCAddressType#';
                if (str_starts_with($name, $prefix)) {
                    $val = (int) substr($name, strlen($prefix));
                    return new static($val);
                }
                throw new \InvalidArgumentException('Unknown enum value: ' . $name);
        }
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix] = $this->enumName();
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $raw = TxRepHelper::getValue($map, $prefix);
        if ($raw === null) {
            throw new \InvalidArgumentException('Missing TxRep value for: ' . $prefix);
        }
        return self::fromTxRepName($raw);
    }
}
