<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTxSetComponentTxsMaybeDiscountedFee {

    public ?int $baseFee = null;
    public array $txs;

    public function __construct(array $txs, ?int $baseFee = null) {
        $this->txs = $txs;
        $this->baseFee = $baseFee;
    }

    public function encode(): string {
        if ($this->baseFee !== null) {
            $bytes = XdrEncoder::integer32(1);
            $bytes .= XdrEncoder::integer64($this->baseFee);
        } else {
            $bytes = XdrEncoder::integer32(0);
        }
        $txsCount = count($this->txs);
        $bytes .= XdrEncoder::integer32($txsCount);
        foreach ($this->txs as $txsItem) {
            $bytes .= $txsItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTxSetComponentTxsMaybeDiscountedFee {
        $baseFee = null;
        if ($xdr->readInteger32() !== 0) {
            $baseFee = $xdr->readInteger64();
        }
        $txs = [];
        $txsSize = $xdr->readInteger32();
        for ($i = 0; $i < $txsSize; $i++) {
            $txs[] = XdrTransactionEnvelope::decode($xdr);
        }
        return new XdrTxSetComponentTxsMaybeDiscountedFee($txs, $baseFee);
    }

    public function getBaseFee(): ?int { return $this->baseFee; }
    public function setBaseFee(?int $baseFee): void { $this->baseFee = $baseFee; }
    public function getTxs(): array { return $this->txs; }
    public function setTxs(array $txs): void { $this->txs = $txs; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
