<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionEvent {

    public XdrTransactionEventStage $stage;
    public XdrContractEvent $event;

    public function __construct(XdrTransactionEventStage $stage, XdrContractEvent $event) {
        $this->stage = $stage;
        $this->event = $event;
    }

    public function encode(): string {
        $bytes = $this->stage->encode();
        $bytes .= $this->event->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionEvent {
        $stage = XdrTransactionEventStage::decode($xdr);
        $event = XdrContractEvent::decode($xdr);
        return new XdrTransactionEvent($stage, $event);
    }

    public function getStage(): XdrTransactionEventStage { return $this->stage; }
    public function setStage(XdrTransactionEventStage $stage): void { $this->stage = $stage; }
    public function getEvent(): XdrContractEvent { return $this->event; }
    public function setEvent(XdrContractEvent $event): void { $this->event = $event; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
