<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionEventStage {
    public int $value;

    const TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS = 0;
    const TRANSACTION_EVENT_STAGE_AFTER_TX = 1;
    const TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS = 2;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS(): XdrTransactionEventStage {
        return new XdrTransactionEventStage(XdrTransactionEventStage::TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS);
    }

    public static function TRANSACTION_EVENT_STAGE_AFTER_TX(): XdrTransactionEventStage {
        return new XdrTransactionEventStage(XdrTransactionEventStage::TRANSACTION_EVENT_STAGE_AFTER_TX);
    }

    public static function TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS(): XdrTransactionEventStage {
        return new XdrTransactionEventStage(XdrTransactionEventStage::TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionEventStage {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
                return new XdrTransactionEventStage($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS => 'before_all_txs',
            self::TRANSACTION_EVENT_STAGE_AFTER_TX => 'after_tx',
            self::TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS => 'after_all_txs',
            // @codeCoverageIgnoreStart
            default => throw new \InvalidArgumentException(
                'Unknown XdrTransactionEventStage enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new \InvalidArgumentException(
                'Expected string for XdrTransactionEventStage JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'before_all_txs' => new static(self::TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS),
            'after_tx' => new static(self::TRANSACTION_EVENT_STAGE_AFTER_TX),
            'after_all_txs' => new static(self::TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS),
            default => throw new \InvalidArgumentException(
                'Unknown XdrTransactionEventStage JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
