<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionMetaV2 {

    public array $txChangesBefore;
    public array $operations;
    public array $txChangesAfter;

    public function __construct(array $txChangesBefore, array $operations, array $txChangesAfter) {
        $this->txChangesBefore = $txChangesBefore;
        $this->operations = $operations;
        $this->txChangesAfter = $txChangesAfter;
    }

    public function encode(): string {
        $txChangesBeforeCount = count($this->txChangesBefore);
        $bytes = XdrEncoder::integer32($txChangesBeforeCount);
        foreach ($this->txChangesBefore as $txChangesBeforeItem) {
            $bytes .= $txChangesBeforeItem->encode();
        }
        $operationsCount = count($this->operations);
        $bytes .= XdrEncoder::integer32($operationsCount);
        foreach ($this->operations as $operationsItem) {
            $bytes .= $operationsItem->encode();
        }
        $txChangesAfterCount = count($this->txChangesAfter);
        $bytes .= XdrEncoder::integer32($txChangesAfterCount);
        foreach ($this->txChangesAfter as $txChangesAfterItem) {
            $bytes .= $txChangesAfterItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionMetaV2 {
        $txChangesBefore = [];
        $txChangesBeforeSize = $xdr->readInteger32();
        for ($i = 0; $i < $txChangesBeforeSize; $i++) {
            $txChangesBefore[] = XdrLedgerEntryChange::decode($xdr);
        }
        $operations = [];
        $operationsSize = $xdr->readInteger32();
        for ($i = 0; $i < $operationsSize; $i++) {
            $operations[] = XdrOperationMeta::decode($xdr);
        }
        $txChangesAfter = [];
        $txChangesAfterSize = $xdr->readInteger32();
        for ($i = 0; $i < $txChangesAfterSize; $i++) {
            $txChangesAfter[] = XdrLedgerEntryChange::decode($xdr);
        }
        return new XdrTransactionMetaV2($txChangesBefore, $operations, $txChangesAfter);
    }

    public function getTxChangesBefore(): array { return $this->txChangesBefore; }
    public function setTxChangesBefore(array $txChangesBefore): void { $this->txChangesBefore = $txChangesBefore; }
    public function getOperations(): array { return $this->operations; }
    public function setOperations(array $operations): void { $this->operations = $operations; }
    public function getTxChangesAfter(): array { return $this->txChangesAfter; }
    public function setTxChangesAfter(array $txChangesAfter): void { $this->txChangesAfter = $txChangesAfter; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'tx_changes_before' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->txChangesBefore),
            'operations' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->operations),
            'tx_changes_after' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->txChangesAfter),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrTransactionMetaV2 JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('tx_changes_before', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field tx_changes_before for XdrTransactionMetaV2'
            );
        }
        $txChangesBefore = (static function ($v) {
            if (!is_array($v)) {
                throw new \InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrLedgerEntryChange::fromJsonValue($item); }
            return $out;
        })($value['tx_changes_before']);
        if (!array_key_exists('operations', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field operations for XdrTransactionMetaV2'
            );
        }
        $operations = (static function ($v) {
            if (!is_array($v)) {
                throw new \InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrOperationMeta::fromJsonValue($item); }
            return $out;
        })($value['operations']);
        if (!array_key_exists('tx_changes_after', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field tx_changes_after for XdrTransactionMetaV2'
            );
        }
        $txChangesAfter = (static function ($v) {
            if (!is_array($v)) {
                throw new \InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrLedgerEntryChange::fromJsonValue($item); }
            return $out;
        })($value['tx_changes_after']);
        return new static($txChangesBefore, $operations, $txChangesAfter);
    }

    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
