<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrTransactionPhase {

    public int $v;
    public ?array $v0Components = null;
    public ?XdrParallelTxsComponent $parallelTxsComponent = null;

    public function __construct(?int $v = null) {
        if ($v !== null) {
            $this->v = $v;
        }
    }

    public function encode(): string {
        $bytes = XdrEncoder::integer32($this->v);
        switch ($this->v) {
            case 0:
                $v0ComponentsCount = count($this->v0Components);
                $bytes .= XdrEncoder::integer32($v0ComponentsCount);
                foreach ($this->v0Components as $v0ComponentsItem) {
                    $bytes .= $v0ComponentsItem->encode();
                }
                break;
            case 1:
                $bytes .= $this->parallelTxsComponent->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionPhase {
        $v = $xdr->readInteger32();
        $result = new XdrTransactionPhase($v);
        switch ($result->v) {
            case 0:
                $result->v0Components = [];
                $v0ComponentsSize = $xdr->readInteger32();
                for ($i = 0; $i < $v0ComponentsSize; $i++) {
                    $result->v0Components[] = XdrTxSetComponent::decode($xdr);
                }
                break;
            case 1:
                $result->parallelTxsComponent = XdrParallelTxsComponent::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getV(): int { return $this->v; }
    public function setV(int $v): void { $this->v = $v; }
    public function getV0Components(): ?array { return $this->v0Components; }
    public function setV0Components(?array $v0Components): void { $this->v0Components = $v0Components; }
    public function getParallelTxsComponent(): ?XdrParallelTxsComponent { return $this->parallelTxsComponent; }
    public function setParallelTxsComponent(?XdrParallelTxsComponent $parallelTxsComponent): void { $this->parallelTxsComponent = $parallelTxsComponent; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): mixed {
        return match ($this->v) {
            0 => ['v0' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->v0Components)],
            1 => ['v1' => $this->parallelTxsComponent->toJsonValue()],
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown discriminant for v on XdrTransactionPhase'
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value) || count($value) !== 1) {
            throw new InvalidArgumentException(
                'Expected single-key object for XdrTransactionPhase, got ' . get_debug_type($value)
            );
        }
        $key = array_key_first($value);
        if (!is_string($key)) {
            throw new InvalidArgumentException(
                'Expected string arm key for XdrTransactionPhase, got ' . get_debug_type($key)
            );
        }
        $arm = $value[$key];
        return match ($key) {
            'v0' => (static function () use ($arm) { $r = new static(0); $r->v0Components = (static function ($v) { if (!is_array($v)) { throw new InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v)); } $out = []; foreach ($v as $item) { $out[] = XdrTxSetComponent::fromJsonValue($item); } return $out; })($arm); return $r; })(),
            'v1' => (static function () use ($arm) { $r = new static(1); $r->parallelTxsComponent = XdrParallelTxsComponent::fromJsonValue($arm); return $r; })(),
            default => throw new InvalidArgumentException(
                'Unknown arm key for XdrTransactionPhase: ' . XdrJsonHelper::safePreview($key)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
