<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrTransactionMeta {

    public int $v;
    public ?array $operations = null;
    public ?XdrTransactionMetaV1 $v1 = null;
    public ?XdrTransactionMetaV2 $v2 = null;
    public ?XdrTransactionMetaV3 $v3 = null;
    public ?XdrTransactionMetaV4 $v4 = null;

    public function __construct(?int $v = null) {
        if ($v !== null) {
            $this->v = $v;
        }
    }

    public function encode(): string {
        $bytes = XdrEncoder::integer32($this->v);
        switch ($this->v) {
            case 0:
                $operationsCount = count($this->operations);
                $bytes .= XdrEncoder::integer32($operationsCount);
                foreach ($this->operations as $operationsItem) {
                    $bytes .= $operationsItem->encode();
                }
                break;
            case 1:
                $bytes .= $this->v1->encode();
                break;
            case 2:
                $bytes .= $this->v2->encode();
                break;
            case 3:
                $bytes .= $this->v3->encode();
                break;
            case 4:
                $bytes .= $this->v4->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionMeta {
        $v = $xdr->readInteger32();
        $result = new XdrTransactionMeta($v);
        switch ($result->v) {
            case 0:
                $result->operations = [];
                $operationsSize = $xdr->readInteger32();
                for ($i = 0; $i < $operationsSize; $i++) {
                    $result->operations[] = XdrOperationMeta::decode($xdr);
                }
                break;
            case 1:
                $result->v1 = XdrTransactionMetaV1::decode($xdr);
                break;
            case 2:
                $result->v2 = XdrTransactionMetaV2::decode($xdr);
                break;
            case 3:
                $result->v3 = XdrTransactionMetaV3::decode($xdr);
                break;
            case 4:
                $result->v4 = XdrTransactionMetaV4::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getV(): int { return $this->v; }
    public function setV(int $v): void { $this->v = $v; }
    public function getOperations(): ?array { return $this->operations; }
    public function setOperations(?array $operations): void { $this->operations = $operations; }
    public function getV1(): ?XdrTransactionMetaV1 { return $this->v1; }
    public function setV1(?XdrTransactionMetaV1 $v1): void { $this->v1 = $v1; }
    public function getV2(): ?XdrTransactionMetaV2 { return $this->v2; }
    public function setV2(?XdrTransactionMetaV2 $v2): void { $this->v2 = $v2; }
    public function getV3(): ?XdrTransactionMetaV3 { return $this->v3; }
    public function setV3(?XdrTransactionMetaV3 $v3): void { $this->v3 = $v3; }
    public function getV4(): ?XdrTransactionMetaV4 { return $this->v4; }
    public function setV4(?XdrTransactionMetaV4 $v4): void { $this->v4 = $v4; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): mixed {
        return match ($this->v) {
            0 => ['v0' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->operations)],
            1 => ['v1' => $this->v1->toJsonValue()],
            2 => ['v2' => $this->v2->toJsonValue()],
            3 => ['v3' => $this->v3->toJsonValue()],
            4 => ['v4' => $this->v4->toJsonValue()],
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown discriminant for v on XdrTransactionMeta'
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value) || count($value) !== 1) {
            throw new InvalidArgumentException(
                'Expected single-key object for XdrTransactionMeta, got ' . get_debug_type($value)
            );
        }
        $key = array_key_first($value);
        if (!is_string($key)) {
            throw new InvalidArgumentException(
                'Expected string arm key for XdrTransactionMeta, got ' . get_debug_type($key)
            );
        }
        $arm = $value[$key];
        return match ($key) {
            'v0' => (static function () use ($arm) { $r = new static(0); $r->operations = (static function ($v) { if (!is_array($v)) { throw new InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v)); } $out = []; foreach ($v as $item) { $out[] = XdrOperationMeta::fromJsonValue($item); } return $out; })($arm); return $r; })(),
            'v1' => (static function () use ($arm) { $r = new static(1); $r->v1 = XdrTransactionMetaV1::fromJsonValue($arm); return $r; })(),
            'v2' => (static function () use ($arm) { $r = new static(2); $r->v2 = XdrTransactionMetaV2::fromJsonValue($arm); return $r; })(),
            'v3' => (static function () use ($arm) { $r = new static(3); $r->v3 = XdrTransactionMetaV3::fromJsonValue($arm); return $r; })(),
            'v4' => (static function () use ($arm) { $r = new static(4); $r->v4 = XdrTransactionMetaV4::fromJsonValue($arm); return $r; })(),
            default => throw new InvalidArgumentException(
                'Unknown arm key for XdrTransactionMeta: ' . XdrJsonHelper::safePreview($key)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
