<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTxAdvertVector {

    /** @var string[] */
    public array $txAdvertVector;

    public function __construct(array $txAdvertVector) {
        $this->txAdvertVector = $txAdvertVector;
    }

    public function encode(): string {
        $count = count($this->txAdvertVector);
        $bytes = XdrEncoder::integer32($count);
        foreach ($this->txAdvertVector as $item) {
            $bytes .= XdrEncoder::string($item);
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTxAdvertVector {
        $txAdvertVector = [];
        $size = $xdr->readInteger32();
        for ($i = 0; $i < $size; $i++) {
            $txAdvertVector[] = $xdr->readString();
        }
        return new XdrTxAdvertVector($txAdvertVector);
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return array_map(static function ($item) { return XdrJsonHelper::bytesToHex($item); }, $this->txAdvertVector);
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected JSON array for XdrTxAdvertVector, got ' . get_debug_type($value)
            );
        }
        $out = [];
        foreach ($value as $item) { $out[] = (static function ($v) { if (!is_string($v)) { throw new \InvalidArgumentException('Expected hex string JSON value, got ' . get_debug_type($v)); } return XdrJsonHelper::hexToBytes($v); })($item); }
        return new static($out);
    }

    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
