<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionBase {

    public XdrMuxedAccount $sourceAccount;
    public int $fee;
    public XdrSequenceNumber $sequenceNumber;
    public XdrPreconditions $preconditions;
    public XdrMemo $memo;
    public array $operations;
    public XdrTransactionExt $ext;

    public function __construct(XdrMuxedAccount $sourceAccount, int $fee, XdrSequenceNumber $sequenceNumber, XdrPreconditions $preconditions, XdrMemo $memo, array $operations, XdrTransactionExt $ext) {
        $this->sourceAccount = $sourceAccount;
        $this->fee = $fee;
        $this->sequenceNumber = $sequenceNumber;
        $this->preconditions = $preconditions;
        $this->memo = $memo;
        $this->operations = $operations;
        $this->ext = $ext;
    }

    public function encode(): string {
        $bytes = $this->sourceAccount->encode();
        $bytes .= XdrEncoder::unsignedInteger32($this->fee);
        $bytes .= $this->sequenceNumber->encode();
        $bytes .= $this->preconditions->encode();
        $bytes .= $this->memo->encode();
        $operationsCount = count($this->operations);
        $bytes .= XdrEncoder::integer32($operationsCount);
        foreach ($this->operations as $operationsItem) {
            $bytes .= $operationsItem->encode();
        }
        $bytes .= $this->ext->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): static {
        $sourceAccount = XdrMuxedAccount::decode($xdr);
        $fee = $xdr->readUnsignedInteger32();
        $sequenceNumber = XdrSequenceNumber::decode($xdr);
        $preconditions = XdrPreconditions::decode($xdr);
        $memo = XdrMemo::decode($xdr);
        $operations = [];
        $operationsSize = $xdr->readInteger32();
        for ($i = 0; $i < $operationsSize; $i++) {
            $operations[] = XdrOperation::decode($xdr);
        }
        $ext = XdrTransactionExt::decode($xdr);
        return new static($sourceAccount, $fee, $sequenceNumber, $preconditions, $memo, $operations, $ext);
    }

    public function getSourceAccount(): XdrMuxedAccount { return $this->sourceAccount; }
    public function setSourceAccount(XdrMuxedAccount $sourceAccount): void { $this->sourceAccount = $sourceAccount; }
    public function getFee(): int { return $this->fee; }
    public function setFee(int $fee): void { $this->fee = $fee; }
    public function getSequenceNumber(): XdrSequenceNumber { return $this->sequenceNumber; }
    public function setSequenceNumber(XdrSequenceNumber $sequenceNumber): void { $this->sequenceNumber = $sequenceNumber; }
    public function getPreconditions(): XdrPreconditions { return $this->preconditions; }
    public function setPreconditions(XdrPreconditions $preconditions): void { $this->preconditions = $preconditions; }
    public function getMemo(): XdrMemo { return $this->memo; }
    public function setMemo(XdrMemo $memo): void { $this->memo = $memo; }
    public function getOperations(): array { return $this->operations; }
    public function setOperations(array $operations): void { $this->operations = $operations; }
    public function getExt(): XdrTransactionExt { return $this->ext; }
    public function setExt(XdrTransactionExt $ext): void { $this->ext = $ext; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toTxRep(string $prefix, array &$lines): void {
        $lines[$prefix . '.sourceAccount'] = TxRepHelper::formatMuxedAccount($this->sourceAccount);
        $lines[$prefix . '.fee'] = (string)$this->fee;
        $this->sequenceNumber->toTxRep($prefix . '.seqNum', $lines);
        $this->preconditions->toTxRep($prefix . '.cond', $lines);
        $this->memo->toTxRep($prefix . '.memo', $lines);
        $lines[$prefix . '.operations.len'] = (string)count($this->operations);
        for ($i = 0; $i < count($this->operations); $i++) {
            $this->operations[$i]->toTxRep($prefix . '.operations[' . $i . ']', $lines);
        }
        $this->ext->toTxRep($prefix . '.ext', $lines);
    }

    public static function fromTxRep(array $map, string $prefix): static {
        $sourceAccount = TxRepHelper::parseMuxedAccount(TxRepHelper::getValue($map, $prefix . '.sourceAccount') ?? '');
        $fee = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.fee') ?? '0');
        $sequenceNumber = XdrSequenceNumber::fromTxRep($map, $prefix . '.seqNum');
        $preconditions = XdrPreconditions::fromTxRep($map, $prefix . '.cond');
        $memo = XdrMemo::fromTxRep($map, $prefix . '.memo');
        $operationsLen = TxRepHelper::parseInt(TxRepHelper::getValue($map, $prefix . '.operations.len') ?? '0');
        $operations = [];
        for ($i = 0; $i < $operationsLen; $i++) {
            $operations[] = XdrOperation::fromTxRep($map, $prefix . '.operations[' . $i . ']');
        }
        $ext = XdrTransactionExt::fromTxRep($map, $prefix . '.ext');
        return new static($sourceAccount, $fee, $sequenceNumber, $preconditions, $memo, $operations, $ext);
    }
}
