<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionResultCode {
    public int $value;

    const FEE_BUMP_INNER_SUCCESS = 1;
    const SUCCESS = 0;
    const FAILED = -1;
    const TOO_EARLY = -2;
    const TOO_LATE = -3;
    const MISSING_OPERATION = -4;
    const BAD_SEQ = -5;
    const BAD_AUTH = -6;
    const INSUFFICIENT_BALANCE = -7;
    const NO_ACCOUNT = -8;
    const INSUFFICIENT_FEE = -9;
    const BAD_AUTH_EXTRA = -10;
    const INTERNAL_ERROR = -11;
    const NOT_SUPPORTED = -12;
    const FEE_BUMP_INNER_FAILED = -13;
    const BAD_SPONSORSHIP = -14;
    const BAD_MIN_SEQ_AGE_OR_GAP = -15;
    const MALFORMED = -16;
    const SOROBAN_INVALID = -17;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function FEE_BUMP_INNER_SUCCESS(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::FEE_BUMP_INNER_SUCCESS);
    }

    public static function SUCCESS(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::SUCCESS);
    }

    public static function FAILED(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::FAILED);
    }

    public static function TOO_EARLY(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::TOO_EARLY);
    }

    public static function TOO_LATE(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::TOO_LATE);
    }

    public static function MISSING_OPERATION(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::MISSING_OPERATION);
    }

    public static function BAD_SEQ(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::BAD_SEQ);
    }

    public static function BAD_AUTH(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::BAD_AUTH);
    }

    public static function INSUFFICIENT_BALANCE(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::INSUFFICIENT_BALANCE);
    }

    public static function NO_ACCOUNT(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::NO_ACCOUNT);
    }

    public static function INSUFFICIENT_FEE(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::INSUFFICIENT_FEE);
    }

    public static function BAD_AUTH_EXTRA(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::BAD_AUTH_EXTRA);
    }

    public static function INTERNAL_ERROR(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::INTERNAL_ERROR);
    }

    public static function NOT_SUPPORTED(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::NOT_SUPPORTED);
    }

    public static function FEE_BUMP_INNER_FAILED(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::FEE_BUMP_INNER_FAILED);
    }

    public static function BAD_SPONSORSHIP(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::BAD_SPONSORSHIP);
    }

    public static function BAD_MIN_SEQ_AGE_OR_GAP(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::BAD_MIN_SEQ_AGE_OR_GAP);
    }

    public static function MALFORMED(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::MALFORMED);
    }

    public static function SOROBAN_INVALID(): XdrTransactionResultCode {
        return new XdrTransactionResultCode(XdrTransactionResultCode::SOROBAN_INVALID);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionResultCode {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 1:
            case 0:
            case -1:
            case -2:
            case -3:
            case -4:
            case -5:
            case -6:
            case -7:
            case -8:
            case -9:
            case -10:
            case -11:
            case -12:
            case -13:
            case -14:
            case -15:
            case -16:
            case -17:
                return new XdrTransactionResultCode($value);
            default:
                throw new \InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
