<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionResultSet {

    public array $results;

    public function __construct(array $results) {
        $this->results = $results;
    }

    public function encode(): string {
        $resultsCount = count($this->results);
        $bytes = XdrEncoder::integer32($resultsCount);
        foreach ($this->results as $resultsItem) {
            $bytes .= $resultsItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionResultSet {
        $results = [];
        $resultsSize = $xdr->readInteger32();
        for ($i = 0; $i < $resultsSize; $i++) {
            $results[] = XdrTransactionResultPair::decode($xdr);
        }
        return new XdrTransactionResultSet($results);
    }

    public function getResults(): array { return $this->results; }
    public function setResults(array $results): void { $this->results = $results; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
