<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionSet {

    public string $previousLedgerHash;
    public array $txs;

    public function __construct(string $previousLedgerHash, array $txs) {
        $this->previousLedgerHash = $previousLedgerHash;
        $this->txs = $txs;
    }

    public function encode(): string {
        $bytes = XdrEncoder::opaqueFixed($this->previousLedgerHash, 32);
        $txsCount = count($this->txs);
        $bytes .= XdrEncoder::integer32($txsCount);
        foreach ($this->txs as $txsItem) {
            $bytes .= $txsItem->encode();
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionSet {
        $previousLedgerHash = $xdr->readOpaqueFixed(32);
        $txs = [];
        $txsSize = $xdr->readInteger32();
        for ($i = 0; $i < $txsSize; $i++) {
            $txs[] = XdrTransactionEnvelope::decode($xdr);
        }
        return new XdrTransactionSet($previousLedgerHash, $txs);
    }

    public function getPreviousLedgerHash(): string { return $this->previousLedgerHash; }
    public function setPreviousLedgerHash(string $previousLedgerHash): void { $this->previousLedgerHash = $previousLedgerHash; }
    public function getTxs(): array { return $this->txs; }
    public function setTxs(array $txs): void { $this->txs = $txs; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'previous_ledger_hash' => XdrJsonHelper::bytesToHex($this->previousLedgerHash),
            'txs' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->txs),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new \InvalidArgumentException(
                'Expected object for XdrTransactionSet JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('previous_ledger_hash', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field previous_ledger_hash for XdrTransactionSet'
            );
        }
        $previousLedgerHash = (static function ($v) { if (!is_string($v)) { throw new \InvalidArgumentException('Expected hex string JSON value, got ' . get_debug_type($v)); } return XdrJsonHelper::hexToBytes($v); })($value['previous_ledger_hash']);
        if (!array_key_exists('txs', $value)) {
            throw new \InvalidArgumentException(
                'Missing required field txs for XdrTransactionSet'
            );
        }
        $txs = (static function ($v) {
            if (!is_array($v)) {
                throw new \InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrTransactionEnvelope::fromJsonValue($item); }
            return $out;
        })($value['txs']);
        return new static($previousLedgerHash, $txs);
    }

    /**
     * @throws \JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws \JsonException If $json is not syntactically valid JSON.
     * @throws \InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
