<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

class XdrTransactionExt {

    public int $discriminant;
    public ?XdrSorobanTransactionData $sorobanTransactionData = null;

    public function __construct(?int $discriminant = null) {
        if ($discriminant !== null) {
            $this->discriminant = $discriminant;
        }
    }

    public function encode(): string {
        $bytes = XdrEncoder::integer32($this->discriminant);
        switch ($this->discriminant) {
            case 0:
                break;
            case 1:
                $bytes .= $this->sorobanTransactionData->encode();
                break;
            default:
                break;
        }
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionExt {
        $discriminant = $xdr->readInteger32();
        $result = new XdrTransactionExt($discriminant);
        switch ($result->discriminant) {
            case 0:
                break;
            case 1:
                $result->sorobanTransactionData = XdrSorobanTransactionData::decode($xdr);
                break;
            default:
                break;
        }
        return $result;
    }

    public function getDiscriminant(): int { return $this->discriminant; }
    public function setDiscriminant(int $discriminant): void { $this->discriminant = $discriminant; }
    public function getSorobanTransactionData(): ?XdrSorobanTransactionData { return $this->sorobanTransactionData; }
    public function setSorobanTransactionData(?XdrSorobanTransactionData $sorobanTransactionData): void { $this->sorobanTransactionData = $sorobanTransactionData; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new \InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }
}
