<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrTransactionResultMeta {

    public XdrTransactionResultPair $result;
    public array $feeProcessing;
    public XdrTransactionMeta $txApplyProcessing;

    public function __construct(XdrTransactionResultPair $result, array $feeProcessing, XdrTransactionMeta $txApplyProcessing) {
        $this->result = $result;
        $this->feeProcessing = $feeProcessing;
        $this->txApplyProcessing = $txApplyProcessing;
    }

    public function encode(): string {
        $bytes = $this->result->encode();
        $feeProcessingCount = count($this->feeProcessing);
        $bytes .= XdrEncoder::integer32($feeProcessingCount);
        foreach ($this->feeProcessing as $feeProcessingItem) {
            $bytes .= $feeProcessingItem->encode();
        }
        $bytes .= $this->txApplyProcessing->encode();
        return $bytes;
    }

    public static function decode(XdrBuffer $xdr): XdrTransactionResultMeta {
        $result = XdrTransactionResultPair::decode($xdr);
        $feeProcessing = [];
        $feeProcessingSize = $xdr->readInteger32();
        for ($i = 0; $i < $feeProcessingSize; $i++) {
            $feeProcessing[] = XdrLedgerEntryChange::decode($xdr);
        }
        $txApplyProcessing = XdrTransactionMeta::decode($xdr);
        return new XdrTransactionResultMeta($result, $feeProcessing, $txApplyProcessing);
    }

    public function getResult(): XdrTransactionResultPair { return $this->result; }
    public function setResult(XdrTransactionResultPair $result): void { $this->result = $result; }
    public function getFeeProcessing(): array { return $this->feeProcessing; }
    public function setFeeProcessing(array $feeProcessing): void { $this->feeProcessing = $feeProcessing; }
    public function getTxApplyProcessing(): XdrTransactionMeta { return $this->txApplyProcessing; }
    public function setTxApplyProcessing(XdrTransactionMeta $txApplyProcessing): void { $this->txApplyProcessing = $txApplyProcessing; }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): array {
        return [
            'result' => $this->result->toJsonValue(),
            'fee_processing' => array_map(static function ($item) { return $item->toJsonValue(); }, $this->feeProcessing),
            'tx_apply_processing' => $this->txApplyProcessing->toJsonValue(),
        ];
    }

    public static function fromJsonValue(mixed $value): static {
        if (is_array($value) && array_key_exists('$schema', $value)) {
            unset($value['$schema']);
        }
        if (!is_array($value)) {
            throw new InvalidArgumentException(
                'Expected object for XdrTransactionResultMeta JSON value, got ' . get_debug_type($value)
            );
        }
        if (!array_key_exists('result', $value)) {
            throw new InvalidArgumentException(
                'Missing required field result for XdrTransactionResultMeta'
            );
        }
        $result = XdrTransactionResultPair::fromJsonValue($value['result']);
        if (!array_key_exists('fee_processing', $value)) {
            throw new InvalidArgumentException(
                'Missing required field fee_processing for XdrTransactionResultMeta'
            );
        }
        $feeProcessing = (static function ($v) {
            if (!is_array($v)) {
                throw new InvalidArgumentException('Expected JSON array, got ' . get_debug_type($v));
            }
            $out = [];
            foreach ($v as $item) { $out[] = XdrLedgerEntryChange::fromJsonValue($item); }
            return $out;
        })($value['fee_processing']);
        if (!array_key_exists('tx_apply_processing', $value)) {
            throw new InvalidArgumentException(
                'Missing required field tx_apply_processing for XdrTransactionResultMeta'
            );
        }
        $txApplyProcessing = XdrTransactionMeta::fromJsonValue($value['tx_apply_processing']);
        return new static($result, $feeProcessing, $txApplyProcessing);
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
