<?php declare(strict_types=1);

// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

namespace Soneso\StellarSDK\Xdr;

use InvalidArgumentException;
use JsonException;

class XdrThresholdIndexes {
    public int $value;

    const THRESHOLD_MASTER_WEIGHT = 0;
    const THRESHOLD_LOW = 1;
    const THRESHOLD_MED = 2;
    const THRESHOLD_HIGH = 3;

    public function __construct(int $value) {
        $this->value = $value;
    }

    public function getValue(): int {
        return $this->value;
    }

    public static function THRESHOLD_MASTER_WEIGHT(): XdrThresholdIndexes {
        return new XdrThresholdIndexes(XdrThresholdIndexes::THRESHOLD_MASTER_WEIGHT);
    }

    public static function THRESHOLD_LOW(): XdrThresholdIndexes {
        return new XdrThresholdIndexes(XdrThresholdIndexes::THRESHOLD_LOW);
    }

    public static function THRESHOLD_MED(): XdrThresholdIndexes {
        return new XdrThresholdIndexes(XdrThresholdIndexes::THRESHOLD_MED);
    }

    public static function THRESHOLD_HIGH(): XdrThresholdIndexes {
        return new XdrThresholdIndexes(XdrThresholdIndexes::THRESHOLD_HIGH);
    }

    public function encode(): string {
        return XdrEncoder::integer32($this->value);
    }

    public static function decode(XdrBuffer $xdr): XdrThresholdIndexes {
        $value = $xdr->readInteger32();
        switch ($value) {
            case 0:
            case 1:
            case 2:
            case 3:
                return new XdrThresholdIndexes($value);
            default:
                throw new InvalidArgumentException("Unknown enum value: $value");
        }
    }

    public function toBase64Xdr(): string {
        return base64_encode($this->encode());
    }

    public static function fromBase64Xdr(string $xdr): static {
        $decoded = base64_decode($xdr, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid base64-encoded XDR');
        }
        return static::decode(new XdrBuffer($decoded));
    }

    public function toJsonValue(): string {
        return match ($this->value) {
            self::THRESHOLD_MASTER_WEIGHT => 'master_weight',
            self::THRESHOLD_LOW => 'low',
            self::THRESHOLD_MED => 'med',
            self::THRESHOLD_HIGH => 'high',
            // @codeCoverageIgnoreStart
            default => throw new InvalidArgumentException(
                'Unknown XdrThresholdIndexes enum value: ' . $this->value
            ),
            // @codeCoverageIgnoreEnd
        };
    }

    public static function fromJsonValue(mixed $value): static {
        if (!is_string($value)) {
            throw new InvalidArgumentException(
                'Expected string for XdrThresholdIndexes JSON value, got ' . get_debug_type($value)
            );
        }
        return match ($value) {
            'master_weight' => new static(self::THRESHOLD_MASTER_WEIGHT),
            'low' => new static(self::THRESHOLD_LOW),
            'med' => new static(self::THRESHOLD_MED),
            'high' => new static(self::THRESHOLD_HIGH),
            default => throw new InvalidArgumentException(
                'Unknown XdrThresholdIndexes JSON value: ' . XdrJsonHelper::safePreview($value)
            ),
        };
    }

    /**
     * @throws JsonException If the value contains structures that cannot be encoded as JSON.
     */
    public function toJson(): string {
        return json_encode(
            $this->toJsonValue(),
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @throws JsonException If $json is not syntactically valid JSON.
     * @throws InvalidArgumentException If the JSON shape does not match this type.
     */
    public static function fromJson(string $json): static {
        return static::fromJsonValue(json_decode($json, true, 512, JSON_THROW_ON_ERROR));
    }
}
