version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    groups:
      composer:
        patterns:
          - "*"
    ignore:
      - dependency-name: "guzzlehttp/guzzle"
        update-types: ["version-update:semver-major"]
      - dependency-name: "christian-riesen/base32"
        update-types: ["version-update:semver-major"]
      - dependency-name: "phpseclib/phpseclib"
        update-types: ["version-update:semver-major"]
      - dependency-name: "psr/log"
        update-types: ["version-update:semver-major"]
      - dependency-name: "yosymfony/toml"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: bundler
    directory: /tools/xdr-generator
    schedule:
      interval: monthly
    groups:
      bundler:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
