<?php declare(strict_types=1);

// This file was automatically generated by the SEP-51 round-trip
// emitter (tools/xdr-generator/generator/round_trip_emitter.rb).
// DO NOT EDIT or your changes may be overwritten.
//
// Regenerate via:
//   cd tools/xdr-generator && bundle exec ruby generate.rb
//
// The emitter walks every Soneso\StellarSDK\Xdr class with toJson
// and emits per-arm / per-permutation round-trip tests, partitioned
// across five files by emit-pass category (one of which holds
// bare-string rejection tests for non-void union arms).

namespace Soneso\StellarSDKTests\Unit\Xdr\Sep51;

use PHPUnit\Framework\TestCase;

class UnionArmRejectionTest extends TestCase
{
public function testRejectsBareStringFor_XdrAccountMergeResult_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrAccountMergeResult::fromJson('"success"');
        $this->fail('Expected InvalidArgumentException for bare string "success" on XdrAccountMergeResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrBucketMetadataExt_v1(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrBucketMetadataExt::fromJson('"v1"');
        $this->fail('Expected InvalidArgumentException for bare string "v1" on XdrBucketMetadataExt');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('v1', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrChangeTrustAsset_credit_alphanum12(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrChangeTrustAsset::fromJson('"credit_alphanum12"');
        $this->fail('Expected InvalidArgumentException for bare string "credit_alphanum12" on XdrChangeTrustAsset');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('credit_alphanum12', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrChangeTrustAsset_credit_alphanum4(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrChangeTrustAsset::fromJson('"credit_alphanum4"');
        $this->fail('Expected InvalidArgumentException for bare string "credit_alphanum4" on XdrChangeTrustAsset');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('credit_alphanum4', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrChangeTrustAsset_pool_share(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrChangeTrustAsset::fromJson('"pool_share"');
        $this->fail('Expected InvalidArgumentException for bare string "pool_share" on XdrChangeTrustAsset');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('pool_share', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrClaimPredicate_and(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrClaimPredicate::fromJson('"and"');
        $this->fail('Expected InvalidArgumentException for bare string "and" on XdrClaimPredicate');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('and', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrClaimPredicate_before_absolute_time(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrClaimPredicate::fromJson('"before_absolute_time"');
        $this->fail('Expected InvalidArgumentException for bare string "before_absolute_time" on XdrClaimPredicate');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('before_absolute_time', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrClaimPredicate_before_relative_time(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrClaimPredicate::fromJson('"before_relative_time"');
        $this->fail('Expected InvalidArgumentException for bare string "before_relative_time" on XdrClaimPredicate');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('before_relative_time', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrClaimPredicate_not(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrClaimPredicate::fromJson('"not"');
        $this->fail('Expected InvalidArgumentException for bare string "not" on XdrClaimPredicate');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('not', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrClaimPredicate_or(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrClaimPredicate::fromJson('"or"');
        $this->fail('Expected InvalidArgumentException for bare string "or" on XdrClaimPredicate');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('or', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrContractExecutable_wasm(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrContractExecutable::fromJson('"wasm"');
        $this->fail('Expected InvalidArgumentException for bare string "wasm" on XdrContractExecutable');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('wasm', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrCreateClaimableBalanceResult_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrCreateClaimableBalanceResult::fromJson('"success"');
        $this->fail('Expected InvalidArgumentException for bare string "success" on XdrCreateClaimableBalanceResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrInflationResult_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrInflationResult::fromJson('"success"');
        $this->fail('Expected InvalidArgumentException for bare string "success" on XdrInflationResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrInnerTransactionResultResult_txfailed(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrInnerTransactionResultResult::fromJson('"txfailed"');
        $this->fail('Expected InvalidArgumentException for bare string "txfailed" on XdrInnerTransactionResultResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('txfailed', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrInnerTransactionResultResult_txsuccess(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrInnerTransactionResultResult::fromJson('"txsuccess"');
        $this->fail('Expected InvalidArgumentException for bare string "txsuccess" on XdrInnerTransactionResultResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('txsuccess', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrInvokeHostFunctionResult_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrInvokeHostFunctionResult::fromJson('"success"');
        $this->fail('Expected InvalidArgumentException for bare string "success" on XdrInvokeHostFunctionResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrManageOfferResult_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrManageOfferResult::fromJson('"success"');
        $this->fail('Expected InvalidArgumentException for bare string "success" on XdrManageOfferResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrManageOfferSuccessResultOffer_created(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrManageOfferSuccessResultOffer::fromJson('"created"');
        $this->fail('Expected InvalidArgumentException for bare string "created" on XdrManageOfferSuccessResultOffer');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('created', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrManageOfferSuccessResultOffer_updated(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrManageOfferSuccessResultOffer::fromJson('"updated"');
        $this->fail('Expected InvalidArgumentException for bare string "updated" on XdrManageOfferSuccessResultOffer');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('updated', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_account_merge(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"account_merge"');
        $this->fail('Expected InvalidArgumentException for bare string "account_merge" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('account_merge', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_allow_trust(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"allow_trust"');
        $this->fail('Expected InvalidArgumentException for bare string "allow_trust" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('allow_trust', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_begin_sponsoring_future_reserves(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"begin_sponsoring_future_reserves"');
        $this->fail('Expected InvalidArgumentException for bare string "begin_sponsoring_future_reserves" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('begin_sponsoring_future_reserves', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_bump_sequence(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"bump_sequence"');
        $this->fail('Expected InvalidArgumentException for bare string "bump_sequence" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('bump_sequence', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_change_trust(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"change_trust"');
        $this->fail('Expected InvalidArgumentException for bare string "change_trust" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('change_trust', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_claim_claimable_balance(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"claim_claimable_balance"');
        $this->fail('Expected InvalidArgumentException for bare string "claim_claimable_balance" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('claim_claimable_balance', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_clawback(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"clawback"');
        $this->fail('Expected InvalidArgumentException for bare string "clawback" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('clawback', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_clawback_claimable_balance(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"clawback_claimable_balance"');
        $this->fail('Expected InvalidArgumentException for bare string "clawback_claimable_balance" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('clawback_claimable_balance', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_create_account(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"create_account"');
        $this->fail('Expected InvalidArgumentException for bare string "create_account" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('create_account', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_create_claimable_balance(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"create_claimable_balance"');
        $this->fail('Expected InvalidArgumentException for bare string "create_claimable_balance" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('create_claimable_balance', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_create_passive_sell_offer(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"create_passive_sell_offer"');
        $this->fail('Expected InvalidArgumentException for bare string "create_passive_sell_offer" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('create_passive_sell_offer', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_extend_footprint_ttl(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"extend_footprint_ttl"');
        $this->fail('Expected InvalidArgumentException for bare string "extend_footprint_ttl" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('extend_footprint_ttl', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_invoke_host_function(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"invoke_host_function"');
        $this->fail('Expected InvalidArgumentException for bare string "invoke_host_function" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('invoke_host_function', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_liquidity_pool_deposit(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"liquidity_pool_deposit"');
        $this->fail('Expected InvalidArgumentException for bare string "liquidity_pool_deposit" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('liquidity_pool_deposit', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_liquidity_pool_withdraw(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"liquidity_pool_withdraw"');
        $this->fail('Expected InvalidArgumentException for bare string "liquidity_pool_withdraw" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('liquidity_pool_withdraw', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_manage_buy_offer(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"manage_buy_offer"');
        $this->fail('Expected InvalidArgumentException for bare string "manage_buy_offer" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('manage_buy_offer', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_manage_data(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"manage_data"');
        $this->fail('Expected InvalidArgumentException for bare string "manage_data" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('manage_data', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_manage_sell_offer(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"manage_sell_offer"');
        $this->fail('Expected InvalidArgumentException for bare string "manage_sell_offer" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('manage_sell_offer', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_path_payment_strict_receive(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"path_payment_strict_receive"');
        $this->fail('Expected InvalidArgumentException for bare string "path_payment_strict_receive" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('path_payment_strict_receive', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_path_payment_strict_send(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"path_payment_strict_send"');
        $this->fail('Expected InvalidArgumentException for bare string "path_payment_strict_send" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('path_payment_strict_send', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_payment(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"payment"');
        $this->fail('Expected InvalidArgumentException for bare string "payment" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('payment', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_restore_footprint(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"restore_footprint"');
        $this->fail('Expected InvalidArgumentException for bare string "restore_footprint" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('restore_footprint', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_revoke_sponsorship(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"revoke_sponsorship"');
        $this->fail('Expected InvalidArgumentException for bare string "revoke_sponsorship" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('revoke_sponsorship', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_set_options(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"set_options"');
        $this->fail('Expected InvalidArgumentException for bare string "set_options" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('set_options', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationBody_set_trust_line_flags(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationBody::fromJson('"set_trust_line_flags"');
        $this->fail('Expected InvalidArgumentException for bare string "set_trust_line_flags" on XdrOperationBody');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('set_trust_line_flags', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrOperationResult_opinner(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrOperationResult::fromJson('"opinner"');
        $this->fail('Expected InvalidArgumentException for bare string "opinner" on XdrOperationResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('opinner', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrPathPaymentStrictReceiveResult_no_issuer(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrPathPaymentStrictReceiveResult::fromJson('"no_issuer"');
        $this->fail('Expected InvalidArgumentException for bare string "no_issuer" on XdrPathPaymentStrictReceiveResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('no_issuer', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrPathPaymentStrictReceiveResult_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrPathPaymentStrictReceiveResult::fromJson('"success"');
        $this->fail('Expected InvalidArgumentException for bare string "success" on XdrPathPaymentStrictReceiveResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrPathPaymentStrictSendResult_no_issuer(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrPathPaymentStrictSendResult::fromJson('"no_issuer"');
        $this->fail('Expected InvalidArgumentException for bare string "no_issuer" on XdrPathPaymentStrictSendResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('no_issuer', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrPathPaymentStrictSendResult_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrPathPaymentStrictSendResult::fromJson('"success"');
        $this->fail('Expected InvalidArgumentException for bare string "success" on XdrPathPaymentStrictSendResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrPreconditions_time(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrPreconditions::fromJson('"time"');
        $this->fail('Expected InvalidArgumentException for bare string "time" on XdrPreconditions');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('time', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrPreconditions_v2(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrPreconditions::fromJson('"v2"');
        $this->fail('Expected InvalidArgumentException for bare string "v2" on XdrPreconditions');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('v2', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCSpecTypeDef_bytes_n(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCSpecTypeDef::fromJson('"bytes_n"');
        $this->fail('Expected InvalidArgumentException for bare string "bytes_n" on XdrSCSpecTypeDef');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('bytes_n', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCSpecTypeDef_map(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCSpecTypeDef::fromJson('"map"');
        $this->fail('Expected InvalidArgumentException for bare string "map" on XdrSCSpecTypeDef');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('map', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCSpecTypeDef_option(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCSpecTypeDef::fromJson('"option"');
        $this->fail('Expected InvalidArgumentException for bare string "option" on XdrSCSpecTypeDef');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('option', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCSpecTypeDef_result(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCSpecTypeDef::fromJson('"result"');
        $this->fail('Expected InvalidArgumentException for bare string "result" on XdrSCSpecTypeDef');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('result', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCSpecTypeDef_tuple(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCSpecTypeDef::fromJson('"tuple"');
        $this->fail('Expected InvalidArgumentException for bare string "tuple" on XdrSCSpecTypeDef');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('tuple', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCSpecTypeDef_udt(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCSpecTypeDef::fromJson('"udt"');
        $this->fail('Expected InvalidArgumentException for bare string "udt" on XdrSCSpecTypeDef');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('udt', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCSpecTypeDef_vec(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCSpecTypeDef::fromJson('"vec"');
        $this->fail('Expected InvalidArgumentException for bare string "vec" on XdrSCSpecTypeDef');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('vec', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_address(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"address"');
        $this->fail('Expected InvalidArgumentException for bare string "address" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('address', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_bool(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"bool"');
        $this->fail('Expected InvalidArgumentException for bare string "bool" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('bool', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_bytes(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"bytes"');
        $this->fail('Expected InvalidArgumentException for bare string "bytes" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('bytes', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_contract_instance(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"contract_instance"');
        $this->fail('Expected InvalidArgumentException for bare string "contract_instance" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('contract_instance', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_duration(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"duration"');
        $this->fail('Expected InvalidArgumentException for bare string "duration" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('duration', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_error(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"error"');
        $this->fail('Expected InvalidArgumentException for bare string "error" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('error', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_i128(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"i128"');
        $this->fail('Expected InvalidArgumentException for bare string "i128" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('i128', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_i256(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"i256"');
        $this->fail('Expected InvalidArgumentException for bare string "i256" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('i256', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_i32(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"i32"');
        $this->fail('Expected InvalidArgumentException for bare string "i32" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('i32', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_i64(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"i64"');
        $this->fail('Expected InvalidArgumentException for bare string "i64" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('i64', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_ledger_key_nonce(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"ledger_key_nonce"');
        $this->fail('Expected InvalidArgumentException for bare string "ledger_key_nonce" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('ledger_key_nonce', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_map(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"map"');
        $this->fail('Expected InvalidArgumentException for bare string "map" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('map', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_string(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"string"');
        $this->fail('Expected InvalidArgumentException for bare string "string" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('string', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_symbol(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"symbol"');
        $this->fail('Expected InvalidArgumentException for bare string "symbol" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('symbol', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_timepoint(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"timepoint"');
        $this->fail('Expected InvalidArgumentException for bare string "timepoint" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('timepoint', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_u128(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"u128"');
        $this->fail('Expected InvalidArgumentException for bare string "u128" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('u128', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_u256(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"u256"');
        $this->fail('Expected InvalidArgumentException for bare string "u256" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('u256', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_u32(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"u32"');
        $this->fail('Expected InvalidArgumentException for bare string "u32" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('u32', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_u64(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"u64"');
        $this->fail('Expected InvalidArgumentException for bare string "u64" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('u64', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSCVal_vec(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSCVal::fromJson('"vec"');
        $this->fail('Expected InvalidArgumentException for bare string "vec" on XdrSCVal');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('vec', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSorobanCredentials_address(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSorobanCredentials::fromJson('"address"');
        $this->fail('Expected InvalidArgumentException for bare string "address" on XdrSorobanCredentials');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('address', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSorobanCredentials_address_v2(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSorobanCredentials::fromJson('"address_v2"');
        $this->fail('Expected InvalidArgumentException for bare string "address_v2" on XdrSorobanCredentials');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('address_v2', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrSorobanCredentials_address_with_delegates(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrSorobanCredentials::fromJson('"address_with_delegates"');
        $this->fail('Expected InvalidArgumentException for bare string "address_with_delegates" on XdrSorobanCredentials');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('address_with_delegates', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrStellarValueExt_signed(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrStellarValueExt::fromJson('"signed"');
        $this->fail('Expected InvalidArgumentException for bare string "signed" on XdrStellarValueExt');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('signed', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrTransactionResultResult_txfailed(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrTransactionResultResult::fromJson('"txfailed"');
        $this->fail('Expected InvalidArgumentException for bare string "txfailed" on XdrTransactionResultResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('txfailed', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrTransactionResultResult_txfee_bump_inner_failed(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrTransactionResultResult::fromJson('"txfee_bump_inner_failed"');
        $this->fail('Expected InvalidArgumentException for bare string "txfee_bump_inner_failed" on XdrTransactionResultResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('txfee_bump_inner_failed', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrTransactionResultResult_txfee_bump_inner_success(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrTransactionResultResult::fromJson('"txfee_bump_inner_success"');
        $this->fail('Expected InvalidArgumentException for bare string "txfee_bump_inner_success" on XdrTransactionResultResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('txfee_bump_inner_success', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrTransactionResultResult_txsuccess(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrTransactionResultResult::fromJson('"txsuccess"');
        $this->fail('Expected InvalidArgumentException for bare string "txsuccess" on XdrTransactionResultResult');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('txsuccess', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrTrustlineAsset_credit_alphanum12(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrTrustlineAsset::fromJson('"credit_alphanum12"');
        $this->fail('Expected InvalidArgumentException for bare string "credit_alphanum12" on XdrTrustlineAsset');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('credit_alphanum12', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrTrustlineAsset_credit_alphanum4(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrTrustlineAsset::fromJson('"credit_alphanum4"');
        $this->fail('Expected InvalidArgumentException for bare string "credit_alphanum4" on XdrTrustlineAsset');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('credit_alphanum4', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}

public function testRejectsBareStringFor_XdrTrustlineAsset_pool_share(): void
{
    // Per-non-void-arm rejection: round-trip tests pass valid
    // payloads only, so the per-arm rejection throw inside
    // fromJsonValue stays uncovered. This test exercises that
    // branch directly by passing a bare string for an arm that
    // requires a single-key object payload, then asserts the
    // resulting message contains both the arm token and the
    // canonical "non-void" phrase to prove the per-arm branch
    // fired (not the catch-all default arm).
    try {
        \Soneso\StellarSDK\Xdr\XdrTrustlineAsset::fromJson('"pool_share"');
        $this->fail('Expected InvalidArgumentException for bare string "pool_share" on XdrTrustlineAsset');
    } catch (\InvalidArgumentException $e) {
        $this->assertStringContainsString('pool_share', $e->getMessage());
        $this->assertStringContainsString('non-void', $e->getMessage());
    }
}
}
