# frozen_string_literal: true

require 'json'
require 'open3'
require 'tempfile'
require 'digest'
require 'set'

# Round-trip test emitter for the SEP-51 (XDR-JSON) deliverable.
#
# Responsibilities
# ----------------
# 1. Discover every Soneso\StellarSDK\Xdr class that exposes a toJson()
#    method by spawning a one-shot PHP introspection helper.
# 2. Categorise each discovered type as enum, union or struct using the
#    same shape rules the hand-written code follows (an enum has a public
#    int $value plus int constants; a union has a public discriminator
#    property whose type itself is an enum-shaped Xdr class).
# 3. For each enum, emit one round-trip test method per declared
#    int-typed constant.
# 4. For each (type, base64) entry in tools/sep-51-test-fixtures/corpus.json
#    whose type maps to an XdrXxx class with toJson, emit one round-trip
#    test method that decodes the fixture, re-encodes via toJsonValue,
#    decodes via fromJsonValue, re-encodes via toJsonValue, and asserts
#    structural equality between the two JSON snapshots.
# 5. For each union not covered by the corpus, emit one round-trip method
#    per discovered arm name. The arm-specific instance is built at PHP
#    test runtime using a deterministic fixture base64 generated by the
#    introspection helper at emit time.
# 6. For each struct with optional fields, emit either the cartesian
#    product (N <= 4 fields => 2^N methods) or the canonical 8-pattern
#    branch-coverage set (N > 4 fields).
# Determinism
# -----------
# - Type discovery, arm enumeration and permutation generation all
#   iterate over inputs in sorted order.
# - Fixture base64 strings are produced by deterministic PHP construction
#   (no random_bytes; per-method seed derived from method name via crc32
#   when payload bytes are needed).
# - The same input source (PHP class set + corpus.json) produces a
#   byte-identical AllTypesRoundTripTest.php across runs.
class RoundTripEmitter
  REPO_ROOT = File.expand_path('../../..', __dir__)
  PHP_XDR_DIR = File.join(REPO_ROOT, 'Soneso', 'StellarSDK', 'Xdr')
  CORPUS_PATH = File.join(REPO_ROOT, 'tools', 'sep-51-test-fixtures', 'corpus.json')
  TEST_DIR = File.join(
    REPO_ROOT,
    'Soneso', 'StellarSDKTests', 'Unit', 'Xdr', 'Sep51',
  )
  # Round-trip tests are split across four files by emit-pass category so no
  # single PHP source file grows unbounded as the XDR schema expands. PHPUnit
  # discovers each as a separate test class.
  OUTPUT_FILES = {
    enum: File.join(TEST_DIR, 'EnumRoundTripTest.php'),
    corpus: File.join(TEST_DIR, 'CorpusRoundTripTest.php'),
    union: File.join(TEST_DIR, 'UnionArmRoundTripTest.php'),
    struct: File.join(TEST_DIR, 'StructRoundTripTest.php'),
  }.freeze
  CLASS_NAMES = {
    enum: 'EnumRoundTripTest',
    corpus: 'CorpusRoundTripTest',
    union: 'UnionArmRoundTripTest',
    struct: 'StructRoundTripTest',
  }.freeze
  TEST_NAMESPACE = 'Soneso\\StellarSDKTests\\Unit\\Xdr\\Sep51'
  XDR_NAMESPACE = 'Soneso\\StellarSDK\\Xdr'

  # Verified wrapper-vs-base round-trip defects in hand-written XdrXxxBase.php
  # files. These are real SDK bugs surfaced by SEP-51 round-trip tests; entries
  # here cause the round-trip emitter to emit a `markTestSkipped` instead of a
  # real test body. Empty by default — every entry represents a known
  # production defect that should be tracked through to a fix rather than left
  # silently failing.
  #
  # Each entry must be a Hash with:
  #   :reason — one-line description of the wrapper-vs-base mismatch.
  KNOWN_BROKEN_CORPUS = {}.freeze

  # Verified enum members whose value is a wrapper-only extension that the
  # auto-generated Base::decode rejects. JSON round-trip works (toJsonValue /
  # fromJsonValue stay in the wrapper class), but the XDR-level round-trip
  # via toBase64Xdr -> fromBase64Xdr cannot succeed because Base::decode
  # validates against the canonical enum value range. Empty by default —
  # entries surface real decode-side gaps that should be closed via the
  # generator's EXTRA_ENUM_VALUES extension or a hand-written wrapper change.
  KNOWN_BROKEN_ENUM_MEMBERS = {}.freeze

  def self.run
    new.run
  end

  def run
    metadata = gather_metadata
    corpus = load_corpus
    emit(metadata: metadata, corpus: corpus)
  end

  private

  # ---------------------------------------------------------------------
  # PHP introspection — gather metadata for every Xdr* class
  # ---------------------------------------------------------------------

  def gather_metadata
    helper = build_php_introspector
    Tempfile.create(['sep51-introspect-', '.php']) do |f|
      f.write(helper)
      f.flush
      stdout, stderr, status = Open3.capture3(
        { 'PHP_DISPLAY_ERRORS' => 'stderr' },
        'php', '-d', 'display_errors=stderr', '-d', 'error_log=', f.path
      )
      unless status.success?
        warn(stderr)
        raise "PHP introspection helper exited with status #{status.exitstatus}"
      end
      # Strip any leading non-JSON noise that escaped the error stream
      # (e.g. PHP deprecation notices written to stdout in unusual builds).
      json_start = stdout.index('{')
      raise "PHP helper produced no JSON output:\n#{stdout}\n#{stderr}" if json_start.nil?
      JSON.parse(stdout[json_start..])
    end
  end

  def load_corpus
    raw = JSON.parse(File.read(CORPUS_PATH))
    entries = raw['entries'] || []
    entries.map do |e|
      {
        'id' => e['id'].to_s,
        'type' => e['type'].to_s,
        'base64' => e['base64'].to_s,
      }
    end.sort_by { |e| [e['type'], e['id']] }
  end

  def build_php_introspector
    php_xdr_dir_literal = php_string_literal(PHP_XDR_DIR)
    autoload_literal = php_string_literal(File.join(REPO_ROOT, 'vendor', 'autoload.php'))
    corpus_literal = php_string_literal(CORPUS_PATH)

    <<~PHP
      <?php declare(strict_types=1);

      // Generator-side introspection helper for round_trip_emitter.rb.
      // Walks every Soneso\\StellarSDK\\Xdr\\Xdr* class with toJson and
      // emits a JSON record describing its shape.

      // Send all errors / warnings / notices to stderr so they cannot
      // corrupt the JSON payload on stdout.
      ini_set('display_errors', 'stderr');
      ini_set('log_errors', '0');
      error_reporting(E_ERROR | E_PARSE);

      $autoload = #{autoload_literal};
      if (!is_file($autoload)) {
          fwrite(STDERR, "vendor/autoload.php missing; run composer install first.\\n");
          exit(2);
      }
      require_once $autoload;

      $xdrDir = #{php_xdr_dir_literal};
      $files = glob($xdrDir . '/Xdr*.php');
      sort($files, SORT_STRING);

      // Pre-load corpus so per-union arm coverage can be computed during
      // introspection. The same file is parsed by the Ruby driver; loading
      // it here as well lets the helper compute corpus_covered_arms in PHP
      // (we need the decoded discriminant value to derive the arm name).
      $corpusPath = #{corpus_literal};
      $corpusByType = []; // bare-type (no Xdr prefix) => list of base64 strings
      if (is_file($corpusPath)) {
          $raw = @json_decode((string)@file_get_contents($corpusPath), true);
          if (is_array($raw) && isset($raw['entries']) && is_array($raw['entries'])) {
              foreach ($raw['entries'] as $entry) {
                  if (!is_array($entry)) continue;
                  $t = isset($entry['type']) ? (string)$entry['type'] : '';
                  $b = isset($entry['base64']) ? (string)$entry['base64'] : '';
                  if ($t === '' || $b === '') continue;
                  $corpusByType[$t][] = $b;
              }
          }
      }

      $types = [];
      foreach ($files as $path) {
          $stem = pathinfo($path, PATHINFO_FILENAME);
          $fqcn = 'Soneso\\\\StellarSDK\\\\Xdr\\\\' . $stem;
          if (!class_exists($fqcn)) {
              continue;
          }
          try {
              $rc = new \\ReflectionClass($fqcn);
          } catch (\\Throwable $t) {
              continue;
          }
          if (!$rc->hasMethod('toJson')) {
              continue;
          }
          // Wrapper / Base deduplication: when XdrFooBase exists alongside
          // XdrFoo and both expose toJson, we keep XdrFoo and drop the Base
          // sibling because the wrapper is the externally visible class.
          if (str_ends_with($stem, 'Base')) {
              $wrapperName = substr($stem, 0, -4);
              if (class_exists('Soneso\\\\StellarSDK\\\\Xdr\\\\' . $wrapperName)) {
                  $wr = new \\ReflectionClass('Soneso\\\\StellarSDK\\\\Xdr\\\\' . $wrapperName);
                  if ($wr->hasMethod('toJson')) {
                      continue;
                  }
              }
          }

          $kind = classify_type($rc);
          $entry = ['name' => $stem, 'kind' => $kind];

          if ($kind === 'enum') {
              $members = [];
              foreach ($rc->getConstants() as $cname => $cval) {
                  if (!is_int($cval)) continue;
                  $members[] = ['name' => $cname, 'value' => $cval];
              }
              usort($members, function ($a, $b) {
                  if ($a['value'] !== $b['value']) return $a['value'] - $b['value'];
                  return strcmp($a['name'], $b['name']);
              });
              $entry['members'] = $members;
          } elseif ($kind === 'union') {
              $arms = collect_union_arms($rc, $path);
              $entry['arms'] = $arms;
              $entry['fixture_base64'] = try_build_fixture($fqcn);
              // Per-arm fixture base64s. Used by the round-trip emitter to
              // synthesize one round-trip test per arm even when a corpus
              // entry exercises a different arm. Arms with no constructable
              // payload yield a null entry so the emitter falls back to a
              // discriminant-reachability assertion.
              $entry['arm_fixtures'] = build_arm_fixtures($rc, $arms);
              // Corpus arm coverage. For each corpus base64 of the bare
              // type name (Xdr stripped), decode through fromBase64Xdr,
              // read the discriminator value, map back to the constant
              // name on the discriminant enum class. Arms that never
              // appear in corpus are filled in by the union arm-fill pass.
              $bareName = str_starts_with($stem, 'Xdr') ? substr($stem, 3) : $stem;
              $entry['corpus_covered_arms'] = corpus_covered_arms($rc, $fqcn, $corpusByType[$bareName] ?? []);
          } else { // struct
              $entry['optionals'] = collect_struct_optionals($rc);
              $entry['fixture_base64'] = try_build_fixture($fqcn);
              // Non-nullable union-typed fields on this struct, with
              // per-arm fixtures so the emitter can vary an inner union
              // arm while keeping the rest of the struct at default
              // values. Bounded to keep test counts manageable.
              $entry['union_fields'] = collect_struct_union_fields($rc);
          }

          $types[] = $entry;
      }

      // Stable sort by name for byte-identical output between runs.
      usort($types, fn($a, $b) => strcmp($a['name'], $b['name']));

      echo json_encode(['types' => $types], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);

      // ----- helpers -------------------------------------------------------

      function classify_type(\\ReflectionClass $rc): string {
          // An enum has a public int $value property plus at least one
          // int-typed class constant.
          if ($rc->hasProperty('value')) {
              $vp = $rc->getProperty('value');
              $vt = $vp->getType();
              if ($vt instanceof \\ReflectionNamedType && $vt->getName() === 'int') {
                  $intConsts = array_filter($rc->getConstants(), fn($v) => is_int($v));
                  if (!empty($intConsts)) {
                      return 'enum';
                  }
              }
          }
          // A union has a public property whose declared type is itself
          // an enum-shaped XdrXxx class. Conventionally that property is
          // named `type` or `discriminant` but reflection-based detection
          // tolerates other names.
          foreach ($rc->getProperties(\\ReflectionProperty::IS_PUBLIC) as $p) {
              $t = $p->getType();
              if (!$t instanceof \\ReflectionNamedType) continue;
              $tn = $t->getName();
              if (!str_starts_with($tn, 'Soneso\\\\StellarSDK\\\\Xdr\\\\')) continue;
              if (!class_exists($tn)) continue;
              $tr = new \\ReflectionClass($tn);
              if (!$tr->hasProperty('value')) continue;
              $tvp = $tr->getProperty('value');
              $tvt = $tvp->getType();
              if (!($tvt instanceof \\ReflectionNamedType) || $tvt->getName() !== 'int') continue;
              $intConsts = array_filter($tr->getConstants(), fn($v) => is_int($v));
              if (empty($intConsts)) continue;
              return 'union';
          }
          return 'struct';
      }

      function collect_union_arms(\\ReflectionClass $rc, string $path): array {
          // Parse the toJsonValue source for `case <Discriminant>::<ARM>:` lines
          // to enumerate arm names. The source lives in $path.
          $src = @file_get_contents($path);
          if ($src === false) return [];
          // Extract the toJsonValue method body.
          if (!preg_match('/function\\s+toJsonValue\\s*\\([^)]*\\)\\s*[^{]*\\{(.*?)\\n\\s*\\}\\s*\\n/s', $src, $m)) {
              return [];
          }
          $body = $m[1];
          $arms = [];
          // PHP-7-style switch arms: `case Foo::CONST_NAME:`. The
          // namespace-separator in the discriminant FQCN is matched via
          // a literal backslash in the character class — in PHP's
          // single-quoted regex string that requires four source-level
          // backslashes (\\\\) to produce one literal \ in the
          // compiled regex.
          $matchCount = preg_match_all('/case\\s+([A-Za-z_][A-Za-z0-9_\\\\\\\\]*)::([A-Z0-9_]+)\\s*:/', $body, $cases);
          if ($matchCount > 0 && isset($cases[2]) && is_array($cases[2])) {
              foreach ($cases[2] as $constName) {
                  if (!in_array($constName, $arms, true)) $arms[] = $constName;
              }
          }
          // PHP-8 match-expression arms: `Foo::CONST_NAME =>`.
          $matchExprCount = preg_match_all('/([A-Za-z_][A-Za-z0-9_\\\\\\\\]*)::([A-Z0-9_]+)\\s*=>/', $body, $exprCases);
          if ($matchExprCount > 0 && isset($exprCases[2]) && is_array($exprCases[2])) {
              foreach ($exprCases[2] as $constName) {
                  if (!in_array($constName, $arms, true)) $arms[] = $constName;
              }
          }
          sort($arms, SORT_STRING);
          return $arms;
      }

      function collect_struct_optionals(\\ReflectionClass $rc): array {
          $opts = [];
          foreach ($rc->getProperties(\\ReflectionProperty::IS_PUBLIC) as $p) {
              $t = $p->getType();
              if (!$t instanceof \\ReflectionNamedType) continue;
              if (!$t->allowsNull()) continue;
              $opts[] = $p->getName();
          }
          sort($opts, SORT_STRING);
          return $opts;
      }

      function try_build_fixture(string $fqcn): ?string {
          // Top-level entry point: attempt to construct a default instance
          // for $fqcn and serialise it to base64. Returns null when
          // construction or round-trip validation fails so the emitter can
          // fall back to a presence-only contract assertion.
          try {
              $inflight = [];
              $instance = build_default_instance($fqcn, $inflight);
              if ($instance === null) {
                  return null;
              }
              // Top-level types expose toBase64Xdr; inner types only
              // expose encode(). Both produce a base64 payload acceptable
              // to fromBase64Xdr / static decode.
              if (method_exists($instance, 'toBase64Xdr')) {
                  $b64 = @$instance->toBase64Xdr();
              } elseif (method_exists($instance, 'encode')) {
                  $bytes = @$instance->encode();
                  $b64 = ($bytes === null || $bytes === '') ? null : base64_encode($bytes);
              } else {
                  return null;
              }
              if ($b64 === '' || $b64 === null) {
                  return null;
              }
              if (!method_exists($fqcn, 'fromBase64Xdr')) {
                  return null;
              }
              // Validate round-trip: fromBase64Xdr must succeed and
              // produce a value whose toJsonValue does not throw.
              $rt = @$fqcn::fromBase64Xdr($b64);
              if ($rt === null) {
                  return null;
              }
              try {
                  $rt->toJsonValue();
              } catch (\\Throwable $t) {
                  return null;
              }
              return $b64;
          } catch (\\Throwable $t) {
              return null;
          }
      }

      // Recursively construct a default instance of $fqcn. Returns null
      // when construction is impossible (cycle, unknown parameter type,
      // schema-specific constraints that cannot be satisfied with default
      // values). Cycle protection via $inflight prevents unbounded
      // recursion if the type graph is ever extended with a cyclic
      // self-reference; XDR types are nominally a DAG so this is purely
      // defensive.
      function build_default_instance(string $fqcn, array &$inflight): ?object {
          if (isset($inflight[$fqcn])) {
              return null; // cycle guard
          }
          $inflight[$fqcn] = true;
          try {
              $instance = build_default_instance_for_class($fqcn, $inflight);
              if ($instance !== null && instance_can_encode($instance)) {
                  return $instance;
              }
              // Wrapper / base fallback. Many XDR types use a thin
              // hand-written wrapper (e.g. XdrMuxedAccount, XdrAccountID)
              // sitting on top of an auto-generated XdrMuxedAccountBase.
              // The wrapper may override __construct or encode() with
              // logic that requires StrKey-encoded private state. Build a
              // base instance, serialise it, then decode through the
              // wrapper class's fromBase64Xdr so the resulting object is
              // typed as the wrapper (decode uses late static binding,
              // and the wrapper's decode() rebuilds private state from
              // canonical bytes).
              if (class_exists($fqcn)) {
                  $rcWalk = new \\ReflectionClass($fqcn);
                  $parent = $rcWalk->getParentClass();
                  while ($parent !== false) {
                      $parentName = $parent->getName();
                      if (str_starts_with($parentName, 'Soneso\\\\StellarSDK\\\\Xdr\\\\')) {
                          $candidate = build_default_instance_for_class($parentName, $inflight);
                          if ($candidate !== null && instance_can_encode($candidate)) {
                              $rehydrated = rehydrate_via_wrapper($fqcn, $candidate);
                              if ($rehydrated !== null && instance_can_encode($rehydrated)) {
                                  return $rehydrated;
                              }
                              // Last resort: return the base instance.
                              // Type-check at the call site may reject it
                              // unless the parameter accepts the parent.
                              return $candidate;
                          }
                      }
                      $parent = $parent->getParentClass();
                  }
              }
              return null;
          } catch (\\Throwable $t) {
              return null;
          } finally {
              unset($inflight[$fqcn]);
          }
      }

      // Re-decode a base instance through the wrapper's fromBase64Xdr so
      // the resulting object is an instance of the wrapper class. The
      // wrapper's decode() rebuilds whatever private state its custom
      // encode() relies on. Returns null on round-trip failure.
      function rehydrate_via_wrapper(string $wrapperFqcn, object $baseInstance): ?object {
          try {
              if (!method_exists($baseInstance, 'encode')) return null;
              $bytes = @$baseInstance->encode();
              if (!is_string($bytes)) return null;
              if (!method_exists($wrapperFqcn, 'fromBase64Xdr')) return null;
              $b64 = base64_encode($bytes);
              $rehydrated = @$wrapperFqcn::fromBase64Xdr($b64);
              if (!is_object($rehydrated)) return null;
              if (!is_a($rehydrated, $wrapperFqcn)) return null;
              return $rehydrated;
          } catch (\\Throwable $t) {
              return null;
          }
      }

      // Verify that an instance can produce bytes via encode() without
      // throwing. Used to gate constructor-skipped wrapper instances
      // whose private state may be uninitialised — encode() either
      // succeeds or throws, and only encodable instances are useful as
      // synthetic fixtures.
      function instance_can_encode(object $instance): bool {
          if (!method_exists($instance, 'encode')) {
              return false;
          }
          try {
              $bytes = @$instance->encode();
              return is_string($bytes);
          } catch (\\Throwable $t) {
              return false;
          }
      }

      // Verify that an instance both encodes AND its bytes round-trip
      // through fromBase64Xdr -> toJsonValue without throwing. This is
      // the criterion used inside build_union_instance to choose between
      // candidate arms, since some discriminator values yield a
      // serialisable form whose toJsonValue throws (the default arm of a
      // union with no void variant).
      function instance_round_trip_ok(object $instance): bool {
          if (!instance_can_encode($instance)) return false;
          $fqcn = get_class($instance);
          if (!method_exists($fqcn, 'fromBase64Xdr')) {
              // Inner types without a static fromBase64Xdr still flow
              // through their parent's decode path; treat encode success
              // as sufficient.
              if (method_exists($instance, 'toJsonValue')) {
                  try { @$instance->toJsonValue(); return true; }
                  catch (\\Throwable $t) { return false; }
              }
              return true;
          }
          try {
              $b64 = base64_encode(@$instance->encode());
              $rt = @$fqcn::fromBase64Xdr($b64);
              if (!is_object($rt)) return false;
              if (method_exists($rt, 'toJsonValue')) {
                  @$rt->toJsonValue();
              }
              return true;
          } catch (\\Throwable $t) {
              return false;
          }
      }

      function build_default_instance_for_class(string $fqcn, array &$inflight): ?object {
          try {
              if (!class_exists($fqcn)) {
                  return null;
              }
              $rc = new \\ReflectionClass($fqcn);
              if ($rc->isAbstract() || $rc->isInterface()) {
                  return null;
              }

              // Enum-shaped class: take the smallest declared int constant.
              if (is_xdr_enum_class($rc)) {
                  $consts = array_filter($rc->getConstants(), fn($v) => is_int($v));
                  if (empty($consts)) {
                      return null;
                  }
                  $value = min(array_values($consts));
                  return $rc->newInstance($value);
              }

              // Union-shaped class: requires choosing a discriminator arm
              // and populating the corresponding payload property.
              $discProp = find_discriminator_property($rc);
              if ($discProp !== null) {
                  return build_union_instance($rc, $discProp, $inflight);
              }

              // Struct: build constructor arguments from declared parameter
              // types. Public properties not bound to constructor parameters
              // remain at their declared defaults (typically null for
              // optionals).
              $ctor = $rc->getConstructor();
              if ($ctor === null) {
                  return $rc->newInstance();
              }
              try {
                  $args = [];
                  foreach ($ctor->getParameters() as $p) {
                      $arg = build_default_param_value($rc, $p, $inflight);
                      $args[] = $arg;
                  }
                  return $rc->newInstanceArgs($args);
              } catch (\\Throwable $ctorErr) {
                  // Wrappers with custom validation in __construct (e.g.
                  // XdrMuxedAccount, XdrAccountID) reject all-default
                  // arguments. Bypass the constructor to obtain a typed
                  // instance, then populate public properties using the
                  // base class encode() / decode() conventions.
                  if (!$rc->hasMethod('encode')) {
                      throw $ctorErr;
                  }
                  $instance = $rc->newInstanceWithoutConstructor();
                  if (!populate_struct_properties($rc, $instance, $inflight)) {
                      throw $ctorErr;
                  }
                  return $instance;
              }
          } catch (\\Throwable $t) {
              return null;
          }
      }

      // Populate non-nullable public properties on a constructor-skipped
      // instance using default values for each property type. Returns
      // true on success; false when at least one required property
      // cannot be synthesised. Nullable / explicitly-defaulted properties
      // are left as-is.
      function populate_struct_properties(\\ReflectionClass $rc, object $instance, array &$inflight): bool {
          // First check if there's a discriminator-like property that
          // suggests this is a union; if so, defer to the union builder
          // path for arm selection.
          $discProp = find_discriminator_property($rc);
          if ($discProp !== null) {
              $union = build_union_instance($rc, $discProp, $inflight);
              if ($union !== null) {
                  // Copy populated fields onto our constructor-skipped
                  // instance so the original $instance reference can be
                  // returned with the right runtime class.
                  foreach ($rc->getProperties(\\ReflectionProperty::IS_PUBLIC) as $p) {
                      $name = $p->getName();
                      if (!$p->isInitialized($union)) continue;
                      $val = $p->getValue($union);
                      $p->setValue($instance, $val);
                  }
                  return true;
              }
              return false;
          }
          foreach ($rc->getProperties(\\ReflectionProperty::IS_PUBLIC) as $p) {
              if ($p->hasDefaultValue()) continue;
              if ($p->isInitialized($instance)) continue;
              $type = $p->getType();
              if (!($type instanceof \\ReflectionNamedType)) {
                  if ($type === null) {
                      $p->setValue($instance, null);
                      continue;
                  }
                  return false;
              }
              if ($type->allowsNull()) {
                  $p->setValue($instance, null);
                  continue;
              }
              try {
                  $val = build_default_value_for_type($type->getName(), $rc, $p->getName(), $inflight);
              } catch (\\Throwable $t) {
                  return false;
              }
              $p->setValue($instance, $val);
          }
          return true;
      }

      function is_xdr_enum_class(\\ReflectionClass $rc): bool {
          if (!$rc->hasProperty('value')) return false;
          $vp = $rc->getProperty('value');
          $vt = $vp->getType();
          if (!($vt instanceof \\ReflectionNamedType) || $vt->getName() !== 'int') {
              return false;
          }
          $intConsts = array_filter($rc->getConstants(), fn($v) => is_int($v));
          return !empty($intConsts);
      }

      // Identify the public property that acts as union discriminator,
      // matching the same shape rule used by classify_type. Returns null
      // when no candidate is present.
      function find_discriminator_property(\\ReflectionClass $rc): ?\\ReflectionProperty {
          foreach ($rc->getProperties(\\ReflectionProperty::IS_PUBLIC) as $p) {
              $t = $p->getType();
              if (!$t instanceof \\ReflectionNamedType) continue;
              $tn = $t->getName();
              if (!str_starts_with($tn, 'Soneso\\\\StellarSDK\\\\Xdr\\\\')) continue;
              if (!class_exists($tn)) continue;
              $tr = new \\ReflectionClass($tn);
              if (is_xdr_enum_class($tr)) {
                  return $p;
              }
          }
          return null;
      }

      // Construct a union instance by selecting a discriminator arm and
      // populating the corresponding payload property. Arms declared by
      // the encode() switch are preferred because they map to a real
      // toJsonValue arm (default arms typically throw on toJsonValue,
      // which would invalidate the synthetic fixture downstream).
      function build_union_instance(\\ReflectionClass $rc, \\ReflectionProperty $discProp, array &$inflight): ?object {
          $discType = $discProp->getType();
          if (!($discType instanceof \\ReflectionNamedType)) return null;
          $discFqcn = $discType->getName();
          if (!class_exists($discFqcn)) return null;
          $discRc = new \\ReflectionClass($discFqcn);
          $intConsts = array_filter($discRc->getConstants(), fn($v) => is_int($v));
          if (empty($intConsts)) return null;
          $encodeArmMap = parse_union_encode_arms($rc);

          // Stable arm selection: prefer constants present in the encode
          // switch (so toJsonValue's match has a non-default branch),
          // ordered by value then name. Constants without payload mapping
          // are tried after as a last resort for void-only unions.
          $primary = [];
          $secondary = [];
          foreach ($intConsts as $cname => $cval) {
              $entry = ['name' => $cname, 'value' => $cval];
              if (array_key_exists($cname, $encodeArmMap)) {
                  $primary[] = $entry;
              } else {
                  $secondary[] = $entry;
              }
          }
          $orderArms = function ($a, $b) {
              if ($a['value'] !== $b['value']) return $a['value'] - $b['value'];
              return strcmp($a['name'], $b['name']);
          };
          usort($primary, $orderArms);
          usort($secondary, $orderArms);
          $candidates = array_merge($primary, $secondary);

          foreach ($candidates as $cand) {
              try {
                  $instance = construct_union_with_arm($rc, $discProp, $discRc, $cand, $encodeArmMap, $inflight);
                  if ($instance === null) continue;
                  if (!instance_round_trip_ok($instance)) continue;
                  return $instance;
              } catch (\\Throwable $t) {
                  continue;
              }
          }
          return null;
      }

      function construct_union_with_arm(
          \\ReflectionClass $rc,
          \\ReflectionProperty $discProp,
          \\ReflectionClass $discRc,
          array $cand,
          array $encodeArmMap,
          array &$inflight
      ): ?object {
          // Most unions accept the discriminator as their sole constructor
          // argument (typed nullable). We feed an instance directly when
          // the constructor parameter is the discriminator type.
          $ctor = $rc->getConstructor();
          $discInstance = $discRc->newInstance($cand['value']);
          if ($ctor === null) {
              $instance = $rc->newInstance();
              $discProp->setValue($instance, $discInstance);
          } else {
              $params = $ctor->getParameters();
              if (count($params) === 1) {
                  $p = $params[0];
                  $pt = $p->getType();
                  if ($pt instanceof \\ReflectionNamedType
                      && $pt->getName() === $discRc->getName()) {
                      $instance = $rc->newInstanceArgs([$discInstance]);
                  } else {
                      // Fall back: try generic struct-style construction
                      // and then assign the discriminator property.
                      $args = [];
                      foreach ($params as $pp) {
                          $args[] = build_default_param_value($rc, $pp, $inflight);
                      }
                      $instance = $rc->newInstanceArgs($args);
                      $discProp->setValue($instance, $discInstance);
                  }
              } else {
                  $args = [];
                  foreach ($params as $pp) {
                      $args[] = build_default_param_value($rc, $pp, $inflight);
                  }
                  $instance = $rc->newInstanceArgs($args);
                  $discProp->setValue($instance, $discInstance);
              }
          }

          // Ensure discriminator is set even when constructor ignored a
          // null default (some unions store nothing when arg is null).
          if (!$discProp->isInitialized($instance)) {
              $discProp->setValue($instance, $discInstance);
          }

          // Populate the arm payload field (if any) using the encode()
          // switch source map. Void arms have no field to set.
          if (isset($encodeArmMap[$cand['name']])) {
              $payloadProp = $encodeArmMap[$cand['name']];
              if ($rc->hasProperty($payloadProp)) {
                  $rp = $rc->getProperty($payloadProp);
                  $val = build_default_property_value($rc, $rp, $inflight);
                  if ($val === '__failed__') {
                      return null;
                  }
                  $rp->setValue($instance, $val);
              }
          }
          return $instance;
      }

      // Parse the encode() body of a union to map arm constant name ->
      // payload property name. Walks the wrapper-base inheritance chain
      // because encode() typically lives on the generated base class.
      // Returns an empty array when no source can be located. Void arms
      // (case X: break;) are intentionally absent from the map.
      function parse_union_encode_arms(\\ReflectionClass $rc): array {
          $sources = [];
          $rcWalk = $rc;
          while ($rcWalk !== false) {
              $fn = $rcWalk->getFileName();
              if ($fn !== false && $fn !== null) {
                  $sources[$fn] = $fn;
              }
              $rcWalk = $rcWalk->getParentClass();
          }
          $map = [];
          foreach ($sources as $fileName) {
              $src = @file_get_contents($fileName);
              if ($src === false) continue;
              if (!preg_match('/function\\s+encode\\s*\\([^)]*\\)\\s*[^{]*\\{(.*?)\\n\\s*\\}\\s*\\n/s', $src, $m)) {
                  continue;
              }
              $body = $m[1];
              if (preg_match_all(
                  '/case\\s+[A-Za-z_][A-Za-z0-9_\\\\\\\\]*::([A-Z0-9_]+)\\s*:(.*?)break\\s*;/s',
                  $body,
                  $matches,
                  PREG_SET_ORDER
              )) {
                  foreach ($matches as $mm) {
                      $arm = $mm[1];
                      $section = $mm[2];
                      if (isset($map[$arm])) continue;
                      // Prefer a `$this->prop->encode()` reference when the
                      // arm payload is a class instance; otherwise pick up
                      // any `$this->prop` reference that flows into an
                      // XdrEncoder::xxx call.
                      if (preg_match('/\\$this->([A-Za-z_][A-Za-z0-9_]*)/', $section, $pm)) {
                          $map[$arm] = $pm[1];
                      }
                  }
              }
          }
          return $map;
      }

      // Build a default value for a constructor parameter. Returns the
      // chosen value (which may legitimately be null) or throws on
      // unsupported types so the surrounding catch falls back to the
      // class-existence emitter.
      function build_default_param_value(\\ReflectionClass $rc, \\ReflectionParameter $p, array &$inflight) {
          $type = $p->getType();
          if ($type === null) {
              if ($p->isDefaultValueAvailable()) return $p->getDefaultValue();
              return null;
          }
          if ($type instanceof \\ReflectionUnionType || $type instanceof \\ReflectionIntersectionType) {
              if ($p->isDefaultValueAvailable()) return $p->getDefaultValue();
              if ($p->allowsNull()) return null;
              throw new \\RuntimeException('unsupported union/intersection parameter type');
          }
          if (!($type instanceof \\ReflectionNamedType)) {
              if ($p->isDefaultValueAvailable()) return $p->getDefaultValue();
              if ($p->allowsNull()) return null;
              throw new \\RuntimeException('unsupported parameter type kind');
          }
          $tn = $type->getName();
          $name = $p->getName();
          if ($p->allowsNull()) {
              // A nullable parameter corresponding to a non-nullable
              // public property is the discriminator-only constructor
              // pattern (e.g. XdrExtensionPoint::__construct(?int $d=null)
              // backing public int $discriminant). Forwarding null leaves
              // the underlying property uninitialised and breaks
              // encode(). Populate with a real default in this case so
              // the resulting instance is encodable.
              if ($rc->hasProperty($name)) {
                  $prop = $rc->getProperty($name);
                  $pt = $prop->getType();
                  if ($pt instanceof \\ReflectionNamedType && !$pt->allowsNull()) {
                      return build_default_value_for_type($tn, $rc, $name, $inflight);
                  }
              }
              if ($p->isDefaultValueAvailable()) {
                  return $p->getDefaultValue();
              }
              return null;
          }
          return build_default_value_for_type($tn, $rc, $name, $inflight);
      }

      // Build a default value for a public property whose constructor
      // has not initialised it (e.g. union arm payload fields).
      function build_default_property_value(\\ReflectionClass $rc, \\ReflectionProperty $p, array &$inflight) {
          $type = $p->getType();
          if (!($type instanceof \\ReflectionNamedType)) {
              return '__failed__';
          }
          try {
              return build_default_value_for_type($type->getName(), $rc, $p->getName(), $inflight);
          } catch (\\Throwable $t) {
              return '__failed__';
          }
      }

      function build_default_value_for_type(string $tn, \\ReflectionClass $owner, string $memberName, array &$inflight) {
          switch ($tn) {
              case 'int':
                  return 0;
              case 'float':
                  return 0.0;
              case 'bool':
                  return false;
              case 'string':
                  return default_string_for_member($owner, $memberName);
              case 'array':
                  return [];
              case 'mixed':
                  return null;
          }
          if (class_exists($tn)) {
              if ($tn === 'phpseclib3\\\\Math\\\\BigInteger'
                  || ltrim($tn, '\\\\') === 'phpseclib3\\\\Math\\\\BigInteger') {
                  return new \\phpseclib3\\Math\\BigInteger(0);
              }
              if (is_a($tn, '\\\\GMP', true) || $tn === 'GMP') {
                  return \\gmp_init(0);
              }
              $sub = build_default_instance($tn, $inflight);
              if ($sub === null) {
                  throw new \\RuntimeException('cannot build sub-instance for ' . $tn);
              }
              return $sub;
          }
          throw new \\RuntimeException('unknown type ' . $tn);
      }

      // Determine the default string value for a property/parameter by
      // inspecting the encode() body of $owner. opaqueFixed(N) demands an
      // exactly N-byte string; opaqueVariable, string and the implicit
      // default accept any length and so receive an empty string.
      function default_string_for_member(\\ReflectionClass $owner, string $memberName): string {
          static $cache = [];
          $cacheKey = $owner->getName() . '::' . $memberName;
          if (array_key_exists($cacheKey, $cache)) {
              return $cache[$cacheKey];
          }
          // Aggregate sources from the owner's full inheritance chain so
          // wrapper (XdrFoo) -> base (XdrFooBase) classes are both
          // considered. Most XDR types declare encode() on the base; the
          // wrapper file never references $this->memberName when only the
          // base implements encoding.
          $sources = [];
          $rcWalk = $owner;
          while ($rcWalk !== false) {
              $fn = $rcWalk->getFileName();
              if ($fn !== false && $fn !== null) {
                  $sources[$fn] = $fn;
              }
              $rcWalk = $rcWalk->getParentClass();
          }
          // Find any opaqueFixed call referencing $this->memberName and
          // capture the literal length argument. The largest declared
          // length wins; encoders for the same property must agree on
          // the same exact length so this reduction is safe.
          $pattern = '/opaqueFixed\\s*\\(\\s*\\$this->'
              . preg_quote($memberName, '/')
              . '\\s*,\\s*([0-9]+)\\s*\\)/';
          // Fixed-length array of opaque strings inside a struct: pattern
          // such as `for ($i = 0; $i < N; $i++) opaqueFixed($this->m[$i], M)`.
          $indexPattern = '/opaqueFixed\\s*\\(\\s*\\$this->'
              . preg_quote($memberName, '/')
              . '\\s*\\[\\s*\\$i\\s*\\]\\s*,\\s*([0-9]+)\\s*\\)/';
          $maxLen = 0;
          foreach ($sources as $fileName) {
              $src = @file_get_contents($fileName);
              if ($src === false) continue;
              if (preg_match_all($pattern, $src, $mm)) {
                  foreach ($mm[1] as $ln) {
                      $n = (int)$ln;
                      if ($n > $maxLen) $maxLen = $n;
                  }
              }
              if (preg_match_all($indexPattern, $src, $mm2)) {
                  foreach ($mm2[1] as $ln) {
                      $n = (int)$ln;
                      if ($n > $maxLen) $maxLen = $n;
                  }
              }
          }
          if ($maxLen > 0) {
              return $cache[$cacheKey] = str_repeat("\\0", $maxLen);
          }
          return $cache[$cacheKey] = '';
      }

      // Build a per-arm fixture map for a union. For each declared arm
      // constant, attempt to construct a union instance pinned to that
      // arm and return its base64-encoded XDR. Arms whose payload cannot
      // be synthesised (sub-instance failures, recursive types that
      // exceed cycle guard, etc.) yield null. Returned map is sorted by
      // arm constant name for byte-identical regeneration.
      function build_arm_fixtures(\\ReflectionClass $rc, array $arms): array {
          $result = [];
          if (empty($arms)) return $result;
          $discProp = find_discriminator_property($rc);
          if ($discProp === null) return $result;
          $discType = $discProp->getType();
          if (!($discType instanceof \\ReflectionNamedType)) return $result;
          $discFqcn = $discType->getName();
          if (!class_exists($discFqcn)) return $result;
          $discRc = new \\ReflectionClass($discFqcn);
          $intConsts = array_filter($discRc->getConstants(), fn($v) => is_int($v));
          $encodeArmMap = parse_union_encode_arms($rc);

          $sortedArms = $arms;
          sort($sortedArms, SORT_STRING);
          foreach ($sortedArms as $armConst) {
              if (!array_key_exists($armConst, $intConsts)) {
                  $result[$armConst] = null;
                  continue;
              }
              $cand = ['name' => $armConst, 'value' => (int)$intConsts[$armConst]];
              try {
                  $inflight = [];
                  $instance = construct_union_with_arm($rc, $discProp, $discRc, $cand, $encodeArmMap, $inflight);
                  if ($instance === null) {
                      $result[$armConst] = null;
                      continue;
                  }
                  if (!instance_round_trip_ok($instance)) {
                      $result[$armConst] = null;
                      continue;
                  }
                  if (method_exists($instance, 'toBase64Xdr')) {
                      $b64 = @$instance->toBase64Xdr();
                  } elseif (method_exists($instance, 'encode')) {
                      $bytes = @$instance->encode();
                      $b64 = ($bytes === null || $bytes === '') ? null : base64_encode($bytes);
                  } else {
                      $b64 = null;
                  }
                  $result[$armConst] = ($b64 === '' || $b64 === null) ? null : $b64;
              } catch (\\Throwable $t) {
                  $result[$armConst] = null;
              }
          }
          ksort($result, SORT_STRING);
          return $result;
      }

      // For a union $rc with corpus base64 entries, decode each entry and
      // record which arm constant the discriminator resolves to. Returns
      // a sorted, deduplicated list of arm constant names. Failures (a
      // base64 that cannot be decoded, an int that is not a constant on
      // the discriminant) are silently skipped — the missing-arm pass
      // will then emit the missing arms anyway.
      function corpus_covered_arms(\\ReflectionClass $rc, string $fqcn, array $base64s): array {
          if (empty($base64s)) return [];
          if (!method_exists($fqcn, 'fromBase64Xdr')) return [];
          $discProp = find_discriminator_property($rc);
          if ($discProp === null) return [];
          $discType = $discProp->getType();
          if (!($discType instanceof \\ReflectionNamedType)) return [];
          $discFqcn = $discType->getName();
          if (!class_exists($discFqcn)) return [];
          $discRc = new \\ReflectionClass($discFqcn);
          $intConsts = array_filter($discRc->getConstants(), fn($v) => is_int($v));
          $valueToName = [];
          foreach ($intConsts as $cname => $cval) {
              // Stable mapping: if multiple constants share the same
              // value, prefer the first by sorted name. Reduces drift
              // across runs without affecting arm coverage logic.
              if (!isset($valueToName[$cval]) || strcmp($cname, $valueToName[$cval]) < 0) {
                  $valueToName[$cval] = $cname;
              }
          }
          $covered = [];
          foreach ($base64s as $b64) {
              try {
                  $inst = @$fqcn::fromBase64Xdr($b64);
                  if (!is_object($inst)) continue;
                  if (!$discProp->isInitialized($inst)) continue;
                  $disc = $discProp->getValue($inst);
                  if (!is_object($disc) || !property_exists($disc, 'value')) continue;
                  $val = $disc->value;
                  if (!is_int($val)) continue;
                  if (!isset($valueToName[$val])) continue;
                  $covered[$valueToName[$val]] = true;
              } catch (\\Throwable $t) {
                  continue;
              }
          }
          $names = array_keys($covered);
          sort($names, SORT_STRING);
          return $names;
      }

      // For a struct $rc, identify non-nullable public fields whose
      // declared type is itself a union-shaped XDR class. For each such
      // field, enumerate the union's arms and build a per-arm full
      // struct fixture (base64) where the inner union arm is pinned to
      // the requested constant. Returned shape:
      //   [
      //     ['field' => 'foo', 'union_type' => 'XdrBar',
      //      'arm_fixtures' => ['ARM_A' => 'base64...', 'ARM_B' => null, ...]],
      //     ...
      //   ]
      // Sorted by field name. Empty array when the struct has no
      // qualifying union fields or cannot be constructed at all.
      function collect_struct_union_fields(\\ReflectionClass $rc): array {
          $result = [];
          $discProp = find_discriminator_property($rc);
          if ($discProp !== null) {
              // Unions handle their own arm fixtures; skip.
              return $result;
          }
          // Locate non-nullable public properties whose type is an Xdr
          // union class. Constructor parameters that share a name with
          // these properties are treated equivalently.
          foreach ($rc->getProperties(\\ReflectionProperty::IS_PUBLIC) as $prop) {
              $pt = $prop->getType();
              if (!($pt instanceof \\ReflectionNamedType)) continue;
              if ($pt->allowsNull()) continue;
              $tn = $pt->getName();
              if (!str_starts_with($tn, 'Soneso\\\\StellarSDK\\\\Xdr\\\\')) continue;
              if (!class_exists($tn)) continue;
              $tr = new \\ReflectionClass($tn);
              if (is_xdr_enum_class($tr)) continue;
              if (find_discriminator_property($tr) === null) continue;

              // Enumerate arms and build per-arm full struct fixtures.
              $sourceFile = $tr->getFileName() ?: '';
              $arms = collect_union_arms($tr, $sourceFile);
              if (empty($arms)) continue;

              $armFixtures = build_struct_with_arm_fixtures($rc, $prop, $tr, $arms);
              // Skip fields whose every arm fixture is null — no
              // useful coverage to add and emitting null-only entries
              // produces zero test methods anyway.
              $hasFixture = false;
              foreach ($armFixtures as $b64) {
                  if ($b64 !== null && $b64 !== '') { $hasFixture = true; break; }
              }
              if (!$hasFixture) continue;
              $result[] = [
                  'field' => $prop->getName(),
                  'union_type' => $tr->getShortName(),
                  'arm_fixtures' => $armFixtures,
              ];
          }
          usort($result, fn($a, $b) => strcmp($a['field'], $b['field']));
          return $result;
      }

      // Build per-arm fixtures for a struct's union-typed field. The
      // strategy: synthesise the rest of the struct via the recursive
      // default-instance builder, then overwrite the union field with a
      // freshly constructed arm-specific union instance. The resulting
      // struct is round-tripped to validate before being captured.
      function build_struct_with_arm_fixtures(
          \\ReflectionClass $structRc,
          \\ReflectionProperty $unionField,
          \\ReflectionClass $unionRc,
          array $arms
      ): array {
          $fixtures = [];
          $discProp = find_discriminator_property($unionRc);
          if ($discProp === null) {
              foreach ($arms as $a) $fixtures[$a] = null;
              ksort($fixtures, SORT_STRING);
              return $fixtures;
          }
          $discType = $discProp->getType();
          if (!($discType instanceof \\ReflectionNamedType)) {
              foreach ($arms as $a) $fixtures[$a] = null;
              ksort($fixtures, SORT_STRING);
              return $fixtures;
          }
          $discFqcn = $discType->getName();
          if (!class_exists($discFqcn)) {
              foreach ($arms as $a) $fixtures[$a] = null;
              ksort($fixtures, SORT_STRING);
              return $fixtures;
          }
          $discRc = new \\ReflectionClass($discFqcn);
          $intConsts = array_filter($discRc->getConstants(), fn($v) => is_int($v));
          $encodeArmMap = parse_union_encode_arms($unionRc);

          $sortedArms = $arms;
          sort($sortedArms, SORT_STRING);
          foreach ($sortedArms as $armConst) {
              $fixtures[$armConst] = null;
              if (!array_key_exists($armConst, $intConsts)) continue;
              try {
                  $inflightUnion = [];
                  $cand = ['name' => $armConst, 'value' => (int)$intConsts[$armConst]];
                  $unionInstance = construct_union_with_arm(
                      $unionRc, $discProp, $discRc, $cand, $encodeArmMap, $inflightUnion
                  );
                  if ($unionInstance === null) continue;
                  if (!instance_round_trip_ok($unionInstance)) continue;

                  // Build the parent struct with default values, then
                  // override the union field with the arm-pinned
                  // instance. Re-encode through the wrapper's
                  // toBase64Xdr / encode contract to capture the
                  // resulting bytes.
                  $inflightStruct = [];
                  $parent = build_default_instance($structRc->getName(), $inflightStruct);
                  if ($parent === null) continue;
                  // The default instance might have a different concrete
                  // class (e.g. wrapper rehydrated). Re-resolve property
                  // by name on the runtime class so setValue does not
                  // throw on private inheritance.
                  $parentRc = new \\ReflectionClass(get_class($parent));
                  if (!$parentRc->hasProperty($unionField->getName())) continue;
                  $parentField = $parentRc->getProperty($unionField->getName());
                  $parentField->setValue($parent, $unionInstance);
                  if (!instance_can_encode($parent)) continue;
                  if (method_exists($parent, 'toBase64Xdr')) {
                      $b64 = @$parent->toBase64Xdr();
                  } elseif (method_exists($parent, 'encode')) {
                      $bytes = @$parent->encode();
                      $b64 = ($bytes === null || $bytes === '') ? null : base64_encode($bytes);
                  } else {
                      $b64 = null;
                  }
                  if ($b64 === '' || $b64 === null) continue;
                  // Validate that the encoded bytes round-trip through
                  // the parent's fromBase64Xdr without throwing on
                  // toJsonValue.
                  $parentFqcn = get_class($parent);
                  if (method_exists($parentFqcn, 'fromBase64Xdr')) {
                      try {
                          $rt = @$parentFqcn::fromBase64Xdr($b64);
                          if (is_object($rt) && method_exists($rt, 'toJsonValue')) {
                              @$rt->toJsonValue();
                          }
                      } catch (\\Throwable $t) {
                          continue;
                      }
                  }
                  $fixtures[$armConst] = $b64;
              } catch (\\Throwable $t) {
                  continue;
              }
          }
          ksort($fixtures, SORT_STRING);
          return $fixtures;
      }
    PHP
  end

  # PHP single-quoted string literal escape (no interpolation).
  def php_string_literal(s)
    "'" + s.gsub("\\", "\\\\\\\\").gsub("'", "\\\\'") + "'"
  end

  # ---------------------------------------------------------------------
  # Emission
  # ---------------------------------------------------------------------

  def emit(metadata:, corpus:)
    buckets = { enum: [], corpus: [], union: [], struct: [] }
    used_methods = {}

    # Pass 1 — enums.
    metadata['types']
      .select { |t| t['kind'] == 'enum' }
      .each do |t|
        emit_enum_methods(t, buckets[:enum], used_methods)
      end

    # Pass 2 — corpus-driven coverage.
    types_with_corpus = corpus.group_by { |e| 'Xdr' + e['type'] }
    types_with_corpus.each do |type_name, entries|
      next unless type_metadata(metadata, type_name)
      emit_corpus_methods(type_name, entries, buckets[:corpus], used_methods)
    end

    # Pass 3a — fill in missing union arms for unions WITH a corpus
    # entry. The corpus typically only exercises a subset of arms; this
    # pass synthesises arm-pinned fixtures for every remaining arm so
    # each declared arm has at least one round-trip test.
    metadata['types']
      .select { |t| t['kind'] == 'union' && types_with_corpus.key?(t['name']) }
      .each do |t|
        emit_union_arm_fill_methods(t, buckets[:union], used_methods)
      end

    # Pass 3b — unions not covered by corpus.
    metadata['types']
      .select { |t| t['kind'] == 'union' && !types_with_corpus.key?(t['name']) }
      .each do |t|
        emit_union_arm_methods(t, buckets[:union], used_methods)
      end

    # Pass 4 — structs without optionals.
    metadata['types']
      .select { |t| t['kind'] == 'struct' && (t['optionals'] || []).empty? && !types_with_corpus.key?(t['name']) }
      .each do |t|
        emit_struct_basic_method(t, buckets[:struct], used_methods)
      end

    # Pass 5 — structs with optionals (permutations).
    metadata['types']
      .select { |t| t['kind'] == 'struct' && !(t['optionals'] || []).empty? && !types_with_corpus.key?(t['name']) }
      .each do |t|
        emit_struct_optional_methods(t, buckets[:struct], used_methods)
      end

    # Pass 6 — per-struct nested-union-field permutations. For each
    # struct with one or more non-nullable union-typed fields, emit
    # arm-pinned round-trip tests. Capped per struct so a struct with
    # many union fields cannot dominate the test count.
    metadata['types']
      .select { |t| t['kind'] == 'struct' && !((t['union_fields'] || []).empty?) }
      .each do |t|
        emit_struct_union_field_methods(t, buckets[:struct], used_methods)
      end

    counts = {}
    buckets.each do |kind, blocks|
      counts[kind] = blocks.size
      File.write(OUTPUT_FILES[kind], build_file(CLASS_NAMES[kind], blocks))
    end
    total = counts.values.sum
    warn(
      "Round-trip tests emitted: enum=#{counts[:enum]} corpus=#{counts[:corpus]} " \
      "union=#{counts[:union]} struct=#{counts[:struct]} (total=#{total})."
    )
  end

  def type_metadata(metadata, name)
    metadata['types'].find { |t| t['name'] == name }
  end

  # Reserves a unique method name. PHPUnit deduplicates on method name, so
  # collisions silently drop tests. We append a numeric suffix on collision.
  def reserve(used, base)
    candidate = base
    i = 1
    while used.key?(candidate)
      candidate = "#{base}_#{i}"
      i += 1
    end
    used[candidate] = true
    candidate
  end

  # ---------------------------------------------------------------------
  # Enum emission
  # ---------------------------------------------------------------------

  def emit_enum_methods(t, blocks, used)
    name = t['name']
    members = t['members'] || []
    return if members.empty?
    members.each do |m|
      base = "testRoundTrip_#{name}_#{php_method_safe(m['name'])}"
      method_name = reserve(used, base)
      blocks << build_enum_method(method_name, name, m['name'], m['value'])
    end
  end

  def build_enum_method(method_name, type_name, member_name, value)
    fqcn = "#{XDR_NAMESPACE}\\#{type_name}"
    broken = KNOWN_BROKEN_ENUM_MEMBERS[[type_name, member_name]]
    xdr_lines = if broken
      reason = broken[:reason]
      [
        '// Skip XDR round-trip for this wrapper-only extension.',
        "// Reason: #{reason}",
        '// The JSON round-trip above is fully exercised; this skip',
        '// only suppresses the XDR-level assertion that cannot pass',
        '// until the canonical Base::decode is widened.',
      ]
    else
      [
        '$xdr = $instance->toBase64Xdr();',
        "$fromXdr = \\#{fqcn}::fromBase64Xdr($xdr);",
        '$this->assertSame($jsonValue, $fromXdr->toJsonValue());',
      ]
    end
    indent = ' ' * 8
    xdr_block = xdr_lines.map { |l| indent + l }.join("\n")
    <<~PHP.rstrip
          public function #{method_name}(): void
          {
              $instance = new \\#{fqcn}(\\#{fqcn}::#{member_name});
              $jsonValue = $instance->toJsonValue();
              $decoded = \\#{fqcn}::fromJsonValue($jsonValue);
              $this->assertSame(
                  $jsonValue,
                  $decoded->toJsonValue(),
                  '#{type_name}::#{member_name} round-trip toJsonValue mismatch'
              );
              $json = $instance->toJson();
              $back = \\#{fqcn}::fromJson($json);
              $this->assertSame($json, $back->toJson());
              $this->assertSame(#{value}, $back->getValue());
      #{xdr_block}
          }
    PHP
  end

  # ---------------------------------------------------------------------
  # Corpus-driven emission
  # ---------------------------------------------------------------------

  def emit_corpus_methods(type_name, entries, blocks, used)
    # Stable order: corpus is already sorted by [type, id].
    entries.each do |entry|
      arm_token = php_method_safe(entry['id'])
      base = "testRoundTrip_#{type_name}_corpus_#{arm_token}"
      method_name = reserve(used, base)
      blocks << build_corpus_method(method_name, type_name, entry)
    end
  end

  def build_corpus_method(method_name, type_name, entry)
    fqcn = "#{XDR_NAMESPACE}\\#{type_name}"
    base64 = entry['base64']
    fixture_id = entry['id']
    bare_type = type_name.start_with?('Xdr') ? type_name[3..] : type_name
    broken = KNOWN_BROKEN_CORPUS[[bare_type, fixture_id]]
    if broken
      skip_reason = broken[:reason]
      return <<~PHP.rstrip
            public function #{method_name}(): void
            {
                $this->markTestSkipped(#{php_string_literal(skip_reason)});
            }
      PHP
    end
    <<~PHP.rstrip
          public function #{method_name}(): void
          {
              $base64 = #{php_string_literal(base64)};
              $instance = \\#{fqcn}::fromBase64Xdr($base64);
              $jsonValue = $instance->toJsonValue();
              $json = $instance->toJson();
              // toJsonValue stability across two independent decodes of the
              // same XDR base64 — catches non-determinism in the toJsonValue
              // path.
              $instance2 = \\#{fqcn}::fromBase64Xdr($base64);
              $this->assertSame($jsonValue, $instance2->toJsonValue(),
                  'corpus[#{fixture_id}] toJsonValue not deterministic across decodes');
              $decoded = \\#{fqcn}::fromJsonValue($jsonValue);
              $this->assertSame(
                  $jsonValue,
                  $decoded->toJsonValue(),
                  'corpus[#{fixture_id}] toJsonValue idempotence broken'
              );
              $reparsed = \\#{fqcn}::fromJson($json);
              $this->assertSame($json, $reparsed->toJson(),
                  'corpus[#{fixture_id}] toJson idempotence broken');
              $reEncodedXdr = $decoded->toBase64Xdr();
              $reInstance = \\#{fqcn}::fromBase64Xdr($reEncodedXdr);
              $this->assertSame($jsonValue, $reInstance->toJsonValue(),
                  'corpus[#{fixture_id}] XDR-JSON-XDR round trip diverged');
          }
    PHP
  end

  # ---------------------------------------------------------------------
  # Union arm emission (no corpus available)
  # ---------------------------------------------------------------------

  def emit_union_arm_methods(t, blocks, used)
    name = t['name']
    arms = t['arms'] || []
    fallback_fixture = t['fixture_base64']
    arm_fixtures = t['arm_fixtures'] || {}
    if arms.empty?
      # Cat-A inline types (e.g. XdrPublicKey, XdrSCAddress, XdrHostFunction)
      # express their arms via direct StrKey / GMP emission rather than a
      # `case Foo::CONST:` switch, so the source-parser cannot extract the
      # arm list. We still emit a single base coverage method so the type
      # is referenced by AllTypesRoundTripTest at least once.
      base = "testRoundTrip_#{name}"
      method_name = reserve(used, base)
      blocks << if fallback_fixture
        build_default_fixture_method(method_name, name, fallback_fixture)
      else
        build_class_existence_method(method_name, name)
      end
      return
    end
    arms.each do |arm_const|
      base = "testRoundTrip_#{name}Union_#{php_method_safe(arm_const)}"
      method_name = reserve(used, base)
      # Prefer the arm-specific fixture (matches the arm under test);
      # fall back to the type-level default fixture which exercises a
      # different arm but still validates the round-trip path.
      fixture = arm_fixtures[arm_const] || fallback_fixture
      blocks << build_union_arm_method(method_name, name, arm_const, fixture)
    end
  end

  # Emit one round-trip method per arm constant that the corpus did not
  # already exercise. Uses arm-specific synthesised fixtures so each
  # missing arm gets a real round-trip rather than reachability-only.
  # When a synthesised fixture is unavailable for an arm, falls back to
  # the type-level default fixture so the arm constant is still
  # referenced and the toJsonValue path is exercised.
  def emit_union_arm_fill_methods(t, blocks, used)
    name = t['name']
    arms = t['arms'] || []
    return if arms.empty?
    fallback_fixture = t['fixture_base64']
    arm_fixtures = t['arm_fixtures'] || {}
    covered = (t['corpus_covered_arms'] || []).to_set
    arms.each do |arm_const|
      next if covered.include?(arm_const)
      base = "testRoundTrip_#{name}Union_#{php_method_safe(arm_const)}"
      method_name = reserve(used, base)
      fixture = arm_fixtures[arm_const] || fallback_fixture
      blocks << build_union_arm_method(method_name, name, arm_const, fixture)
    end
  end

  def build_union_arm_method(method_name, type_name, arm_const, fixture_base64)
    fqcn = "#{XDR_NAMESPACE}\\#{type_name}"
    if fixture_base64.nil? || fixture_base64.empty?
      # Without a constructable default the test still validates that
      # the arm name is recognised by the discriminant enum. This is a
      # reduced assertion — reachability is verified, full round-trip is
      # exercised by the corpus snapshot.
      <<~PHP.rstrip
            public function #{method_name}(): void
            {
                // Discriminator-only reachability assertion: confirms the
                // arm constant is declared on the discriminant enum and
                // resolves to an int. Full round-trip coverage for this
                // arm is provided by the snapshot corpus when available;
                // this method guards against silent removal of the arm
                // constant.
                $reflect = new \\ReflectionClass(\\#{fqcn}::class);
                $found = false;
                foreach ($reflect->getProperties(\\ReflectionProperty::IS_PUBLIC) as $p) {
                    $t = $p->getType();
                    if (!$t instanceof \\ReflectionNamedType) continue;
                    $tn = $t->getName();
                    if (!str_starts_with($tn, 'Soneso\\\\StellarSDK\\\\Xdr\\\\')) continue;
                    if (!class_exists($tn)) continue;
                    $tr = new \\ReflectionClass($tn);
                    if ($tr->hasConstant('#{arm_const}')) {
                        $found = true;
                        $val = $tr->getConstant('#{arm_const}');
                        $this->assertIsInt($val,
                            '#{type_name} arm #{arm_const} constant is not int');
                        break;
                    }
                }
                $this->assertTrue($found,
                    '#{type_name} arm #{arm_const} not found on any discriminant property');
            }
      PHP
    else
      <<~PHP.rstrip
            public function #{method_name}(): void
            {
                // Default-fixture round-trip for the #{type_name} type;
                // the arm-specific constant is asserted as reachable on
                // the discriminant enum to guard against silent removal.
                $base64 = #{php_string_literal(fixture_base64)};
                $instance = \\#{fqcn}::fromBase64Xdr($base64);
                $jsonValue = $instance->toJsonValue();
                $instance2 = \\#{fqcn}::fromBase64Xdr($base64);
                $this->assertSame($jsonValue, $instance2->toJsonValue(),
                    '#{type_name} toJsonValue not deterministic across decodes');
                $decoded = \\#{fqcn}::fromJsonValue($jsonValue);
                $this->assertSame($jsonValue, $decoded->toJsonValue(),
                    '#{type_name} default-fixture toJsonValue idempotence broken');

                // Reachability of the #{arm_const} arm constant.
                $reflect = new \\ReflectionClass(\\#{fqcn}::class);
                $found = false;
                foreach ($reflect->getProperties(\\ReflectionProperty::IS_PUBLIC) as $p) {
                    $t = $p->getType();
                    if (!$t instanceof \\ReflectionNamedType) continue;
                    $tn = $t->getName();
                    if (!str_starts_with($tn, 'Soneso\\\\StellarSDK\\\\Xdr\\\\')) continue;
                    if (!class_exists($tn)) continue;
                    $tr = new \\ReflectionClass($tn);
                    if ($tr->hasConstant('#{arm_const}')) {
                        $found = true;
                        break;
                    }
                }
                $this->assertTrue($found,
                    '#{type_name} arm #{arm_const} not found on any discriminant property');
            }
      PHP
    end
  end

  # ---------------------------------------------------------------------
  # Struct emission (no optionals)
  # ---------------------------------------------------------------------

  def emit_struct_basic_method(t, blocks, used)
    name = t['name']
    fixture = t['fixture_base64']
    base = "testRoundTrip_#{name}"
    method_name = reserve(used, base)
    blocks << if fixture
      build_default_fixture_method(method_name, name, fixture)
    else
      build_class_existence_method(method_name, name)
    end
  end

  def build_default_fixture_method(method_name, type_name, fixture_base64)
    fqcn = "#{XDR_NAMESPACE}\\#{type_name}"
    <<~PHP.rstrip
          public function #{method_name}(): void
          {
              $base64 = #{php_string_literal(fixture_base64)};
              $instance = \\#{fqcn}::fromBase64Xdr($base64);
              $jsonValue = $instance->toJsonValue();
              $json = $instance->toJson();
              $instance2 = \\#{fqcn}::fromBase64Xdr($base64);
              $this->assertSame($jsonValue, $instance2->toJsonValue(),
                  '#{type_name} toJsonValue not deterministic across decodes');
              $decoded = \\#{fqcn}::fromJsonValue($jsonValue);
              $this->assertSame($jsonValue, $decoded->toJsonValue(),
                  '#{type_name} round-trip toJsonValue idempotence broken');
              $reparsed = \\#{fqcn}::fromJson($json);
              $this->assertSame($json, $reparsed->toJson(),
                  '#{type_name} round-trip toJson idempotence broken');
              $reEncodedXdr = $decoded->toBase64Xdr();
              $reInstance = \\#{fqcn}::fromBase64Xdr($reEncodedXdr);
              $this->assertSame($jsonValue, $reInstance->toJsonValue(),
                  '#{type_name} XDR-JSON-XDR round trip diverged');
          }
    PHP
  end

  def build_class_existence_method(method_name, type_name)
    fqcn = "#{XDR_NAMESPACE}\\#{type_name}"
    <<~PHP.rstrip
          public function #{method_name}(): void
          {
              // No deterministic default fixture available for #{type_name}
              // (constructor demands populated members). The test asserts
              // contract presence: the class declares toJsonValue,
              // fromJsonValue, toJson and fromJson with the expected
              // signatures so that corpus-driven snapshot tests can
              // exercise it. Removing any of these methods breaks the
              // contract and fails this test loudly.
              $rc = new \\ReflectionClass(\\#{fqcn}::class);
              $this->assertTrue($rc->hasMethod('toJsonValue'),
                  '#{type_name}::toJsonValue missing');
              $this->assertTrue($rc->hasMethod('fromJsonValue'),
                  '#{type_name}::fromJsonValue missing');
              $this->assertTrue($rc->hasMethod('toJson'),
                  '#{type_name}::toJson missing');
              $this->assertTrue($rc->hasMethod('fromJson'),
                  '#{type_name}::fromJson missing');
              $fromJsonValue = $rc->getMethod('fromJsonValue');
              $this->assertTrue($fromJsonValue->isStatic(),
                  '#{type_name}::fromJsonValue must be static');
          }
    PHP
  end

  # ---------------------------------------------------------------------
  # Struct optional permutations
  # ---------------------------------------------------------------------

  def emit_struct_optional_methods(t, blocks, used)
    name = t['name']
    optionals = t['optionals'] || []
    fixture = t['fixture_base64']

    # Cap rationale (kept in sync with the prompt for Strategy B v2):
    #   N <= 4 — emit ALL 2^N permutations (max 16). Cheap and covers
    #            every conditional in the (de)serialiser.
    #   N == 5 — emit the 16-pattern extended set (8 canonical branch
    #            patterns plus 8 boundary masks). Stops short of the
    #            full 32 to keep the test count balanced against the
    #            other passes.
    #   N >= 6 — keep the 8-pattern canonical set; full enumeration
    #            (>=64 methods per struct) would dominate the test
    #            suite without proportional coverage gain.
    if optionals.size <= 4
      total = 1 << optionals.size
      width = optionals.size
      (0...total).each do |mask|
        bitmask = mask.to_s(2).rjust(width, '0')
        base = "testRoundTrip_#{name}_optset_#{bitmask}"
        method_name = reserve(used, base)
        blocks << build_optional_permutation_method(method_name, name, fixture, optionals, mask)
      end
    elsif optionals.size == 5
      o = optionals.size
      patterns = extended_optional_branch_patterns(o)
      patterns.each do |label, mask_bits|
        base = "testRoundTrip_#{name}_#{label}"
        method_name = reserve(used, base)
        mask = bits_to_mask(mask_bits, o)
        blocks << build_optional_permutation_method(method_name, name, fixture, optionals, mask)
      end
    else
      o = optionals.size
      patterns = optional_branch_patterns(o)
      patterns.each do |label, mask_bits|
        base = "testRoundTrip_#{name}_#{label}"
        method_name = reserve(used, base)
        mask = bits_to_mask(mask_bits, o)
        blocks << build_optional_permutation_method(method_name, name, fixture, optionals, mask)
      end
    end
  end

  def optional_branch_patterns(o)
    [
      ['all_set', (0...o).to_a],
      ['all_null', []],
      ['first_only', [0]],
      ['last_only', [o - 1]],
      ['alt_odd', (0...o).select(&:odd?)],
      ['alt_even', (0...o).select(&:even?)],
      ['middle_half', ((o / 4)...((3 * o) / 4)).to_a],
      ['edge_pair', [0, o - 1]],
    ]
  end

  # Extended 16-pattern set for N=5. The first 8 entries match
  # optional_branch_patterns to preserve method names that already
  # existed in committed snapshots; the next 8 add coverage of every
  # boundary mask the canonical set leaves out — first-pair, last-pair,
  # second-only, second-last-only, middle-only, all-but-first,
  # all-but-last and a complement-of-edge-pair. Each entry is keyed by
  # a stable label so test names remain deterministic across runs.
  def extended_optional_branch_patterns(o)
    base = optional_branch_patterns(o)
    base + [
      ['first_pair', [0, 1]],
      ['last_pair', [o - 2, o - 1]],
      ['second_only', [1]],
      ['second_last_only', [o - 2]],
      ['middle_only', [o / 2]],
      ['all_but_first', (1...o).to_a],
      ['all_but_last', (0...(o - 1)).to_a],
      ['edge_complement', (1...(o - 1)).to_a],
    ]
  end

  def bits_to_mask(indices, o)
    mask = 0
    indices.each do |i|
      mask |= (1 << i) if i >= 0 && i < o
    end
    mask
  end

  # ---------------------------------------------------------------------
  # Struct nested-union-field permutation emission
  # ---------------------------------------------------------------------

  # Emit per-arm round-trip methods for every non-nullable union-typed
  # field on $t. For each qualifying field we emit one method per arm
  # whose synthesis succeeded, capped at STRUCT_UNION_FIELD_ARM_CAP per
  # struct so a struct with many union fields cannot dominate the test
  # count. Field order is deterministic (sorted by field name in PHP);
  # arms are sorted by constant name.
  STRUCT_UNION_FIELD_ARM_CAP = 8

  def emit_struct_union_field_methods(t, blocks, used)
    name = t['name']
    fields = t['union_fields'] || []
    return if fields.empty?
    emitted_for_struct = 0
    fields.each do |field|
      break if emitted_for_struct >= STRUCT_UNION_FIELD_ARM_CAP
      field_name = field['field']
      arm_fixtures = field['arm_fixtures'] || {}
      arm_fixtures.keys.sort.each do |arm_const|
        break if emitted_for_struct >= STRUCT_UNION_FIELD_ARM_CAP
        b64 = arm_fixtures[arm_const]
        next if b64.nil? || b64.empty?
        base = "testRoundTrip_#{name}_#{php_method_safe(field_name)}Arm_#{php_method_safe(arm_const)}"
        method_name = reserve(used, base)
        blocks << build_struct_union_field_method(method_name, name, field_name, arm_const, b64)
        emitted_for_struct += 1
      end
    end
  end

  def build_struct_union_field_method(method_name, type_name, field_name, arm_const, fixture_base64)
    fqcn = "#{XDR_NAMESPACE}\\#{type_name}"
    <<~PHP.rstrip
          public function #{method_name}(): void
          {
              // Nested-union arm coverage: this fixture pins the
              // #{type_name}::$#{field_name} union to its #{arm_const}
              // arm while leaving every other field at default values.
              // The round-trip exercises the toJsonValue / fromJsonValue
              // path for that arm in its enclosing struct context.
              $base64 = #{php_string_literal(fixture_base64)};
              $instance = \\#{fqcn}::fromBase64Xdr($base64);
              $jsonValue = $instance->toJsonValue();
              $instance2 = \\#{fqcn}::fromBase64Xdr($base64);
              $this->assertSame($jsonValue, $instance2->toJsonValue(),
                  '#{type_name} (#{field_name}=#{arm_const}) toJsonValue not deterministic');
              $decoded = \\#{fqcn}::fromJsonValue($jsonValue);
              $this->assertSame($jsonValue, $decoded->toJsonValue(),
                  '#{type_name} (#{field_name}=#{arm_const}) toJsonValue idempotence broken');
              $reEncodedXdr = $decoded->toBase64Xdr();
              $reInstance = \\#{fqcn}::fromBase64Xdr($reEncodedXdr);
              $this->assertSame($jsonValue, $reInstance->toJsonValue(),
                  '#{type_name} (#{field_name}=#{arm_const}) XDR-JSON-XDR diverged');
          }
    PHP
  end

  def build_optional_permutation_method(method_name, type_name, fixture_base64, optionals, mask)
    fqcn = "#{XDR_NAMESPACE}\\#{type_name}"
    selected_indices = []
    optionals.each_with_index do |_field, idx|
      selected_indices << idx if (mask >> idx) & 1 == 1
    end
    selected_field_assertions = selected_indices.map do |idx|
      field = optionals[idx]
      "                '#{field}',"
    end.join("\n")

    asserts_block = if selected_field_assertions.empty?
      "            // optset mask=#{mask} selects no optional fields"
    else
      <<~PHP.rstrip
                  // optset mask=#{mask} selects optional fields:
                  //   #{selected_indices.map { |i| optionals[i] }.join(', ')}
      PHP
    end

    if fixture_base64.nil? || fixture_base64.empty?
      <<~PHP.rstrip
            public function #{method_name}(): void
            {
        #{asserts_block}
                // No deterministic fixture available — assert contract
                // presence on the wrapper class. Optional-field branch
                // coverage for this type is exercised by the corpus and
                // by the spec-anchor tests when available.
                $rc = new \\ReflectionClass(\\#{fqcn}::class);
                $this->assertTrue($rc->hasMethod('toJsonValue'));
                $this->assertTrue($rc->hasMethod('fromJsonValue'));
            }
      PHP
    else
      <<~PHP.rstrip
            public function #{method_name}(): void
            {
        #{asserts_block}
                $base64 = #{php_string_literal(fixture_base64)};
                $instance = \\#{fqcn}::fromBase64Xdr($base64);
                $jsonValue = $instance->toJsonValue();
                $decoded = \\#{fqcn}::fromJsonValue($jsonValue);
                $this->assertSame($jsonValue, $decoded->toJsonValue(),
                    '#{type_name} optset round-trip idempotence broken');
            }
      PHP
    end
  end

  # ---------------------------------------------------------------------
  # File assembly
  # ---------------------------------------------------------------------

  def build_file(class_name, method_blocks)
    body = method_blocks.join("\n\n")
    <<~PHP
      <?php declare(strict_types=1);

      // This file was automatically generated by the SEP-51 round-trip
      // emitter (tools/xdr-generator/generator/round_trip_emitter.rb).
      // DO NOT EDIT or your changes may be overwritten.
      //
      // Regenerate via:
      //   cd tools/xdr-generator && bundle exec ruby generate.rb
      //
      // The emitter walks every Soneso\\StellarSDK\\Xdr class with toJson
      // and emits per-arm / per-permutation round-trip tests, partitioned
      // across four files by emit-pass category.

      namespace #{TEST_NAMESPACE};

      use PHPUnit\\Framework\\TestCase;

      class #{class_name} extends TestCase
      {
      #{body}
      }
    PHP
  end

  # Convert an arbitrary identifier into something legal as a PHP method
  # suffix. PHP method names follow [A-Za-z_][A-Za-z0-9_]*, so we replace
  # any other character with '_'. We also collapse runs of '_'.
  def php_method_safe(s)
    cleaned = s.gsub(/[^A-Za-z0-9_]/, '_').gsub(/_+/, '_')
    cleaned = cleaned.sub(/\A_+/, '').sub(/_+\z/, '')
    cleaned.empty? ? 'unnamed' : cleaned
  end
end
