# frozen_string_literal: true

# Defines which XDR types need TxRep serialization methods (toTxRep/fromTxRep).
#
# Computed by tracing the type graph from TransactionEnvelope, Transaction,
# FeeBumpTransaction, and DecoratedSignature roots. Only types reachable from
# a transaction envelope are included. Types resolved away by TYPE_OVERRIDES
# (XdrTimePoint, XdrDuration, etc.) are excluded because they map to PHP
# primitives and do not generate separate class files.
#
# All names use PHP SDK class names (after NAME_OVERRIDES), not raw XDR names.

require 'set'

# ---------------------------------------------------------------------------
# TXREP_XDR_NAMES
# Raw XDR canonical names (without Xdr prefix) of types that need TxRep.
# Used by should_generate_txrep? to check whether a type needs TxRep methods.
# ---------------------------------------------------------------------------
TXREP_XDR_NAMES = Set[
  'AccountID',
  'AllowTrustOp',
  'AssetCode',
  'Asset',
  'AlphaNum12',
  'AlphaNum4',
  'AssetType',
  'BeginSponsoringFutureReservesOp',
  'BumpSequenceOp',
  'ChangeTrustAsset',
  'ChangeTrustOp',
  'ClaimClaimableBalanceOp',
  'ClaimPredicate',
  'ClaimPredicateType',
  'ClaimableBalanceID',
  'ClaimableBalanceIDType',
  'Claimant',
  'ClaimantType',
  'ClaimantV0',
  'ClawbackClaimableBalanceOp',
  'ClawbackOp',
  'ConfigSettingID',
  'ContractDataDurability',
  'ContractExecutable',
  'ContractExecutableType',
  'ContractIDPreimage',
  'ContractIDPreimageFromAddress',
  'ContractIDPreimageType',
  'CreateAccountOp',
  'CreateClaimableBalanceOp',
  'CreateContractArgs',
  'CreateContractArgsV2',
  'CreatePassiveSellOfferOp',
  'CryptoKeyType',
  'DataValue',
  'DecoratedSignature',
  'EnvelopeType',
  'ExtendFootprintTTLOp',
  'ExtensionPoint',
  'FeeBumpTransaction',
  'FeeBumpTransactionEnvelope',
  'FeeBumpTransactionExt',
  'FeeBumpTransactionInnerTx',
  'Hash',
  'HostFunction',
  'HostFunctionType',
  'Int128Parts',
  'Int256Parts',
  'Int32',
  'Int64',
  'InvokeContractArgs',
  'InvokeHostFunctionOp',
  'LedgerBounds',
  'LedgerEntryType',
  'LedgerFootprint',
  'LedgerKey',
  'LedgerKeyAccount',
  'LedgerKeyClaimableBalance',
  'LedgerKeyConfigSetting',
  'LedgerKeyContractCode',
  'LedgerKeyContractData',
  'LedgerKeyData',
  'LedgerKeyLiquidityPool',
  'LedgerKeyOffer',
  'LedgerKeyTtl',
  'LedgerKeyTrustLine',
  'LiquidityPoolConstantProductParameters',
  'LiquidityPoolDepositOp',
  'LiquidityPoolParameters',
  'LiquidityPoolType',
  'LiquidityPoolWithdrawOp',
  'ManageBuyOfferOp',
  'ManageDataOp',
  'ManageSellOfferOp',
  'Memo',
  'MemoType',
  'MuxedAccount',
  'MuxedEd25519Account',
  'Operation',
  'OperationBody',
  'OperationType',
  'PathPaymentStrictReceiveOp',
  'PathPaymentStrictSendOp',
  'PaymentOp',
  'PreconditionType',
  'Preconditions',
  'PreconditionsV2',
  'Price',
  'PublicKey',
  'PublicKeyType',
  'RestoreFootprintOp',
  'RevokeSponsorshipOp',
  'RevokeSponsorshipOpSigner',
  'RevokeSponsorshipType',
  'SCAddress',
  'SCAddressType',
  'SCBytes',
  'SCContractInstance',
  'SCError',
  'SCErrorCode',
  'SCErrorType',
  'SCMapEntry',
  'SCNonceKey',
  'SCVal',
  'SCValType',
  'SequenceNumber',
  'SetOptionsOp',
  'SetTrustLineFlagsOp',
  'Signature',
  'SignatureHint',
  'SignerKeyEd25519SignedPayload',
  'Signer',
  'SignerKey',
  'SignerKeyType',
  'SorobanAddressCredentials',
  'SorobanAuthorizationEntries',
  'SorobanAuthorizationEntry',
  'SorobanAuthorizedFunction',
  'SorobanAuthorizedFunctionType',
  'SorobanAuthorizedInvocation',
  'SorobanCredentials',
  'SorobanCredentialsType',
  'SorobanResources',
  'SorobanResourcesExtV0',
  'SorobanTransactionData',
  'SorobanTransactionDataExt',
  'String32',
  'String64',
  'TimeBounds',
  'Transaction',
  'TransactionEnvelope',
  'TransactionExt',
  'TransactionV0',
  'TransactionV0Envelope',
  'TransactionV0Ext',
  'TransactionV1Envelope',
  'TrustLineAsset',
  'UInt128Parts',
  'UInt256Parts',
  'Uint256',
  'Uint32',
  'Uint64',
].freeze

# ---------------------------------------------------------------------------
# TXREP_TYPES
# PHP SDK class names of types that need TxRep serialization (143 types).
# These are the resolved names after NAME_OVERRIDES are applied.
# ---------------------------------------------------------------------------
TXREP_TYPES = Set[
  'XdrAccountID',
  'XdrAllowTrustOperation',
  'XdrAllowTrustOperationAsset',
  'XdrAsset',
  'XdrAssetAlphaNum12',
  'XdrAssetAlphaNum4',
  'XdrAssetType',
  'XdrBeginSponsoringFutureReservesOperation',
  'XdrBumpSequenceOperation',
  'XdrChangeTrustAsset',
  'XdrChangeTrustOperation',
  'XdrClaimClaimableBalanceOperation',
  'XdrClaimPredicate',
  'XdrClaimPredicateType',
  'XdrClaimableBalanceID',
  'XdrClaimableBalanceIDType',
  'XdrClaimant',
  'XdrClaimantType',
  'XdrClaimantV0',
  'XdrClawbackClaimableBalanceOperation',
  'XdrClawbackOperation',
  'XdrConfigSettingID',
  'XdrContractDataDurability',
  'XdrContractExecutable',
  'XdrContractExecutableType',
  'XdrContractIDPreimage',
  'XdrContractIDPreimageFromAddress',
  'XdrContractIDPreimageType',
  'XdrCreateAccountOperation',
  'XdrCreateClaimableBalanceOperation',
  'XdrCreateContractArgs',
  'XdrCreateContractArgsV2',
  'XdrCreatePassiveSellOfferOperation',
  'XdrCryptoKeyType',
  'XdrDataValue',
  'XdrDecoratedSignature',
  'XdrEnvelopeType',
  'XdrExtendFootprintTTLOp',
  'XdrExtensionPoint',
  'XdrFeeBumpTransaction',
  'XdrFeeBumpTransactionEnvelope',
  'XdrFeeBumpTransactionExt',
  'XdrFeeBumpTransactionInnerTx',
  'XdrHash',
  'XdrHostFunction',
  'XdrHostFunctionType',
  'XdrInt128Parts',
  'XdrInt256Parts',
  'XdrInt32',
  'XdrInt64',
  'XdrInvokeContractArgs',
  'XdrInvokeHostFunctionOp',
  'XdrLedgerBounds',
  'XdrLedgerEntryType',
  'XdrLedgerFootprint',
  'XdrLedgerKey',
  'XdrLedgerKeyAccount',
  'XdrLedgerKeyClaimableBalance',
  'XdrLedgerKeyConfigSetting',
  'XdrLedgerKeyContractCode',
  'XdrLedgerKeyContractData',
  'XdrLedgerKeyData',
  'XdrLedgerKeyLiquidityPool',
  'XdrLedgerKeyOffer',
  'XdrLedgerKeyTTL',
  'XdrLedgerKeyTrustLine',
  'XdrLiquidityPoolConstantProductParameters',
  'XdrLiquidityPoolDepositOperation',
  'XdrLiquidityPoolParameters',
  'XdrLiquidityPoolType',
  'XdrLiquidityPoolWithdrawOperation',
  'XdrManageBuyOfferOperation',
  'XdrManageDataOperation',
  'XdrManageSellOfferOperation',
  'XdrMemo',
  'XdrMemoType',
  'XdrMuxedAccount',
  'XdrMuxedAccountMed25519',
  'XdrOperation',
  'XdrOperationBody',
  'XdrOperationType',
  'XdrPathPaymentStrictReceiveOperation',
  'XdrPathPaymentStrictSendOperation',
  'XdrPaymentOperation',
  'XdrPreconditionType',
  'XdrPreconditions',
  'XdrPreconditionsV2',
  'XdrPrice',
  'XdrPublicKey',
  'XdrPublicKeyType',
  'XdrRestoreFootprintOp',
  'XdrRevokeSponsorshipOperation',
  'XdrRevokeSponsorshipSigner',
  'XdrRevokeSponsorshipType',
  'XdrSCAddress',
  'XdrSCAddressType',
  'XdrSCBytes',
  'XdrSCContractInstance',
  'XdrSCError',
  'XdrSCErrorCode',
  'XdrSCErrorType',
  'XdrSCMapEntry',
  'XdrSCNonceKey',
  'XdrSCVal',
  'XdrSCValType',
  'XdrSequenceNumber',
  'XdrSetOptionsOperation',
  'XdrSetTrustLineFlagsOperation',
  'XdrSignature',
  'XdrSignatureHint',
  'XdrSignedPayload',
  'XdrSigner',
  'XdrSignerKey',
  'XdrSignerKeyType',
  'XdrSorobanAddressCredentials',
  'XdrSorobanAuthorizationEntries',
  'XdrSorobanAuthorizationEntry',
  'XdrSorobanAuthorizedFunction',
  'XdrSorobanAuthorizedFunctionType',
  'XdrSorobanAuthorizedInvocation',
  'XdrSorobanCredentials',
  'XdrSorobanCredentialsType',
  'XdrSorobanResources',
  'XdrSorobanResourcesExtV0',
  'XdrSorobanTransactionData',
  'XdrSorobanTransactionDataExt',
  'XdrString32',
  'XdrString64',
  'XdrTimeBounds',
  'XdrTransaction',
  'XdrTransactionEnvelope',
  'XdrTransactionExt',
  'XdrTransactionV0',
  'XdrTransactionV0Envelope',
  'XdrTransactionV0Ext',
  'XdrTransactionV1Envelope',
  'XdrTrustlineAsset',
  'XdrUInt128Parts',
  'XdrUInt256Parts',
  'XdrUint256',
  'XdrUint32',
  'XdrUint64',
].freeze

# ---------------------------------------------------------------------------
# TXREP_COMPACT_TYPES
# Types that serialize as a single compact value instead of expanding their
# sub-fields. Maps PHP class name to format/parse helper method references.
# ---------------------------------------------------------------------------
TXREP_COMPACT_TYPES = {
  'XdrAccountID'                => { format: 'TxRepHelper::formatAccountId',       parse: 'TxRepHelper::parseAccountId' },
  'XdrAllowTrustOperationAsset' => { format: 'TxRepHelper::formatAllowTrustAsset', parse: 'TxRepHelper::parseAllowTrustAsset' },
  'XdrAsset'                    => { format: 'TxRepHelper::formatAsset',           parse: 'TxRepHelper::parseAsset' },
  'XdrMuxedAccount'             => { format: 'TxRepHelper::formatMuxedAccount',    parse: 'TxRepHelper::parseMuxedAccount' },
  'XdrSignerKey'                => { format: 'TxRepHelper::formatSignerKey',       parse: 'TxRepHelper::parseSignerKey' },
}.freeze

# ---------------------------------------------------------------------------
# Helper method: checks whether a resolved PHP class name needs TxRep methods.
# Accepts the resolved PHP name (e.g., 'XdrPaymentOperation') and returns true
# if its XDR origin is in TXREP_XDR_NAMES or the PHP name is in TXREP_TYPES.
# ---------------------------------------------------------------------------
def should_generate_txrep?(php_name)
  TXREP_TYPES.include?(php_name)
end
