<?php declare(strict_types=1);

// Copyright 2022 The Stellar PHP SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

namespace Soneso\StellarSDK\SEP\KYCService;

/**
 * Request parameters for retrieving customer information and KYC status via SEP-12
 *
 * This class represents the request parameters for querying customer information
 * from the anchor's SEP-12 KYC endpoint. It can be used to check the verification
 * status of a customer, retrieve required fields for registration, or get current
 * customer data.
 *
 * Customers can be identified by an anchor-assigned ID, a Stellar account (with
 * optional memo for shared accounts), or a transaction ID when verification
 * requirements depend on transaction details.
 *
 * The response will indicate whether the customer is accepted, pending verification,
 * needs additional information, or has been rejected. It will also list any required
 * or optional fields that need to be provided or updated.
 *
 * @package Soneso\StellarSDK\SEP\KYCService
 * @see https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md SEP-12 Specification
 * @see KYCService::getCustomerInfo() For executing this request
 * @see GetCustomerInfoResponse For the response structure
 */
class GetCustomerInfoRequest
{
    /**
     * @var string|null $id The ID of the customer as returned in the response of a previous PUT request. If the customer has not been registered, they do not yet have an id.
     */
    public ?string $id = null;

    /**
     * @var string|null $account (deprecated, optional) This field should match the sub value of the decoded SEP-10 JWT.
     * The Stellar account ID used to identify this customer. If many customers share the same Stellar account, the memo and memo_type parameters should be included as well.
     */
    public ?string $account = null;

    /**
     * @var string|null $memo a properly formatted memo that uniquely identifies a customer. This value is generated by the client making the request. This parameter and memo_type are identical to the PUT request parameters of the same name.
     * see: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md#shared-omnibus-or-pooled-accounts
     */
    public ?string $memo = null;

    /**
     * @var string|null $memoType (deprecated, optional) type of memo. One of text, id or hash. Deprecated because memos should always be of type id, although anchors should continue to support this parameter for outdated clients. If hash, memo should be base64-encoded. If a memo is present in the decoded SEP-10 JWT's sub value, this parameter can be ignored. See the Shared Accounts section for more information.
     * see: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md#shared-omnibus-or-pooled-accounts
     */
    public ?string $memoType = null;

    /**
     * @var string|null $type the type of action the customer is being KYCd for. See the Type Specification here:
     * https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md#type-specification
     */
    public ?string $type = null;

    /**
     * @var string|null $transactionId The transaction id with which the customer's info is associated. When information
     * from the customer depends on the transaction (e.g., more information is required for larger amounts)
     */
    public ?string $transactionId = null;

    /**
     * @var string|null $lang Defaults to en. Language code specified using ISO 639-1. Human-readable descriptions, choices, and messages should be in this language.
     */
    public ?string $lang = null;

    /**
     * @var string|null $jwt jwt token previously received from the anchor via the SEP-10 authentication flow
     */
    public ?string $jwt = null;

}