<?php declare(strict_types=1);

// Copyright 2025 The Stellar PHP SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

namespace Soneso\StellarSDK\Soroban\Contract;

use Soneso\StellarSDK\AbstractTransaction;
use Soneso\StellarSDK\Constants\StellarConstants;
use Soneso\StellarSDK\Constants\NetworkConstants;

/**
 * Configuration options for smart contract method invocation
 *
 * This class defines transaction parameters and behavior for calling Soroban smart contract
 * methods. It controls transaction fees, timeouts, simulation behavior, and automatic state
 * restoration for archived contract data.
 *
 * @package Soneso\StellarSDK\Soroban\Contract
 * @see AssembledTransaction For the transaction class that uses these options
 * @see AssembledTransactionOptions For combined transaction configuration
 * @since 1.0.0
 */
class MethodOptions
{

    /**
     * @var int $fee The fee to pay for the transaction in Stroops. Must be at least the base fee
     * (100 stroops). Higher fees may be needed for complex operations. Resource fees are added
     * automatically during simulation. Default 100.
     */
    public int $fee;

    /**
     * @var int $timeoutInSeconds The timebounds which should be set for transactions generated by the
     * contract client. Must be positive. Transactions not included in a ledger within this time
     * will expire and cannot be submitted. Default 300.
     */
    public int $timeoutInSeconds;

    /**
     * @var bool $simulate Whether to automatically simulate the transaction when constructing the
     * AssembledTransaction. Set to false if you need to modify the transaction builder before
     * simulation. Default true.
     */
    public bool $simulate;

    /**
     * @var bool $restore If true, will automatically attempt to restore archived ledger entries
     * that need renewal. Requires source account with private key. Default true.
     */
    public bool $restore;

    /**
     * @param int $fee The fee to pay for the transaction in Stroops. Must be at least the base fee
     *                 (100 stroops). Higher fees may be needed for complex operations. Resource fees
     *                 are added automatically during simulation. Default 100.
     * @param int $timeoutInSeconds The timebounds which should be set for transactions generated by the
     *                              contract client. Must be positive. Transactions not included in a ledger
     *                              within this time will expire and cannot be submitted. Default 300.
     * @param bool $simulate Whether to automatically simulate the transaction when constructing the
     *                       AssembledTransaction. Set to false if you need to modify the transaction
     *                       builder before simulation. Default true.
     * @param bool $restore If true, will automatically attempt to restore archived ledger entries
     *                      that need renewal. Requires source account with private key. Default true.
     */
    public function __construct(int $fee = StellarConstants::MIN_BASE_FEE_STROOPS,
                                int $timeoutInSeconds = NetworkConstants::DEFAULT_SOROBAN_TIMEOUT_SECONDS,
                                bool $simulate = true,
                                bool $restore = true)
    {
        $this->fee = $fee;
        $this->timeoutInSeconds = $timeoutInSeconds;
        $this->simulate = $simulate;
        $this->restore = $restore;
    }

}